### PR TITLE
Reva update v1.4.1-0.20201127111856-e6a6212c1b7b

### PR DESCRIPTION
**Pull request by refs**
* Fix capabilities response for multiple client versions #1331 [cs3org/reva#1331](Fix capabilities response for multiple client versions #1331)
* Fix home storage redirect for remote.php/dav/files [cs3org/reva#1342](https://github.com/cs3org/reva/pull/1342)

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
❤️

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/1812/26/7
```
  Scenario Outline: Uploading file to a user read/write share folder works                                             # /srv/app/testrunner/tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature:95
    Given using <dav-path> DAV path                                                                                    # FeatureContext::usingOldOrNewDavPath()
    And user "Brian" has been created with default attributes and skeleton files                                       # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
    And user "Alice" has created a share with settings                                                                 # FeatureContext::userHasCreatedAShareWithSettings()
      | path        | FOLDER |
      | shareType   | user   |
      | permissions | change |
      | shareWith   | Brian  |
    And user "Brian" has accepted share "/FOLDER" offered by user "Alice"                                              # FeatureContext::userHasReactedToShareOfferedBy()
    When user "Brian" uploads file "filesForUpload/textfile.txt" to "/Shares/FOLDER/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
    Then the HTTP status code should be "201"                                                                          # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the content of file "/FOLDER/textfile.txt" for user "Alice" should be:                                         # FeatureContext::contentOfFileForUserShouldBePyString()
      """
      This is a testfile.
      
      Cheers.
      """

    Examples:
      | dav-path |
      | old      |
      | new      |
        The downloaded content was expected to be 'This is a testfile.
        
        Cheers.', but actually is ''. HTTP status was 500
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'This is a testfile.\n
        -\n
        -Cheers.'
        +''
```

Hmmm - is that 500 status a new thing, or a "random" fail of something?

**Comment by refs** [comment]
> [drone.owncloud.com/owncloud/ocis/1812/26/7](https://drone.owncloud.com/owncloud/ocis/1812/26/7)
> 
> ```
>   Scenario Outline: Uploading file to a user read/write share folder works                                             # /srv/app/testrunner/tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature:95
>     Given using <dav-path> DAV path                                                                                    # FeatureContext::usingOldOrNewDavPath()
>     And user "Brian" has been created with default attributes and skeleton files                                       # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
>     And user "Alice" has created a share with settings                                                                 # FeatureContext::userHasCreatedAShareWithSettings()
>       | path        | FOLDER |
>       | shareType   | user   |
>       | permissions | change |
>       | shareWith   | Brian  |
>     And user "Brian" has accepted share "/FOLDER" offered by user "Alice"                                              # FeatureContext::userHasReactedToShareOfferedBy()
>     When user "Brian" uploads file "filesForUpload/textfile.txt" to "/Shares/FOLDER/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
>     Then the HTTP status code should be "201"                                                                          # FeatureContext::thenTheHTTPStatusCodeShouldBe()
>     And the content of file "/FOLDER/textfile.txt" for user "Alice" should be:                                         # FeatureContext::contentOfFileForUserShouldBePyString()
>       """
>       This is a testfile.
>       
>       Cheers.
>       """
> 
>     Examples:
>       | dav-path |
>       | old      |
>       | new      |
>         The downloaded content was expected to be 'This is a testfile.
>         
>         Cheers.', but actually is ''. HTTP status was 500
>         Failed asserting that two strings are equal.
>         --- Expected
>         +++ Actual
>         @@ @@
>         -'This is a testfile.\n
>         -\n
>         -Cheers.'
>         +''
> ```
> 
> Hmmm - is that 500 status a new thing, or a "random" fail of something?
> 
> I restarted drone CI.

oh wow, weird, thanks for restarting

**Comment by kulmann** [comment]
> https://drone.owncloud.com/owncloud/ocis/1812/26/7
> 
> ```
>   Scenario Outline: Uploading file to a user read/write share folder works                                             # /srv/app/testrunner/tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature:95
>     Given using <dav-path> DAV path                                                                                    # FeatureContext::usingOldOrNewDavPath()
>     And user "Brian" has been created with default attributes and skeleton files                                       # FeatureContext::userHasBeenCreatedWithDefaultAttributes()
>     And user "Alice" has created a share with settings                                                                 # FeatureContext::userHasCreatedAShareWithSettings()
>       | path        | FOLDER |
>       | shareType   | user   |
>       | permissions | change |
>       | shareWith   | Brian  |
>     And user "Brian" has accepted share "/FOLDER" offered by user "Alice"                                              # FeatureContext::userHasReactedToShareOfferedBy()
>     When user "Brian" uploads file "filesForUpload/textfile.txt" to "/Shares/FOLDER/textfile.txt" using the WebDAV API # FeatureContext::userUploadsAFileTo()
>     Then the HTTP status code should be "201"                                                                          # FeatureContext::thenTheHTTPStatusCodeShouldBe()
>     And the content of file "/FOLDER/textfile.txt" for user "Alice" should be:                                         # FeatureContext::contentOfFileForUserShouldBePyString()
>       """
>       This is a testfile.
>       
>       Cheers.
>       """
> 
>     Examples:
>       | dav-path |
>       | old      |
>       | new      |
>         The downloaded content was expected to be 'This is a testfile.
>         
>         Cheers.', but actually is ''. HTTP status was 500
>         Failed asserting that two strings are equal.
>         --- Expected
>         +++ Actual
>         @@ @@
>         -'This is a testfile.\n
>         -\n
>         -Cheers.'
>         +''
> ```
> 
> Hmmm - is that 500 status a new thing, or a "random" fail of something?
> 
> I restarted drone CI.

It passed on the second run (and I restarted as well without paying close attention.. but passed there as well). So it seems to  be a random failure @phil-davis

**Pull request merged**
