### PR TITLE
graph: Add accountEnabled flag to ldap backend.

### LINKED ISSUE #5553: graph: Add accountEnabled property to /users
- Update the libregraph API spec
- implement support of the account Enabled flag in the LDAP identity backend
- allow to configure a single boolean LDAP attribute, reflecting the enabled/disable state of the user

### PR DESCRIPTION
**Pull request by Excds**
## Description
Add boolean accountEnabled property to users in the ldap backend.

## Related Issue
- Fixes #5553 

## How Has This Been Tested?
Tested manually with curl and added unit tests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>wopiValidatorTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/19160/40/1) failed. Further test are cancelled...

**Review by rhafer — DISMISSED** [review]
Seems that the flag is not returned yet when listing users.

```
curl -k  -u admin:admin 'https://localhost:9200/graph/v1.0/use/058bff95-6708-4fe5-91e4-9ea3d377588b`
```
works while

```
curl -k  -u admin:admin 'https://localhost:9200/graph/v1.0/users'
```

doesn't

**Comment by Excds** [comment]
> Seems that the flag is not returned yet when listing users.
> 
> ```
> curl -k  -u admin:admin 'https://localhost:9200/graph/v1.0/use/058bff95-6708-4fe5-91e4-9ea3d377588b`
> ```
> 
> works while
> 
> ```
> curl -k  -u admin:admin 'https://localhost:9200/graph/v1.0/users'
> ```
> 
> doesn't

Added the missed flag to listing user. Note that it can still be nil, and therefore not returned as it will be skipped in the libregraph struct.

**Comment by Excds** [comment]
Facepalm. "comment and close" closes the PR, not the comment thread.

**Review by butonic — APPROVED** [review]

**Pull request merged**
