### PR TITLE
[tests-only] [full-ci] Adjust triggers for chat-notifications pipeline

### LINKED ISSUE #4460: CI: duplicate CI run with only chat notification
## Describe the bug

When creating pull request https://github.com/owncloud/ocis/pull/4459 I noticed that two independent CI runs were started:
1. https://drone.owncloud.com/owncloud/ocis/14958 (seemingly normal CI run)
2. https://drone.owncloud.com/owncloud/ocis/14957 (only chat notification, nothing else)

## Steps to reproduce

See linked pull request. I don't know what triggered the second CI run.

## Expected behavior
Only one CI run.

## Actual behavior
A seemingly normal CI run and one that only performs a chat notification.

cc @individual-it @phil-davis

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Ref: https://docs.drone.io/pipeline/triggers/

A pipeline can only specify a single "grouping combination" of triggers. For example, the trigger can list some events, and some branches - trigger on event "A", "B", branch "X", "Y" . The logic that is implemented is to run the pipeline if ((event "A" OR event "B") AND (branch "X" or branch "Y"). So we get the pipeline running on all 4 combinations.

There is no way to express just (event "A"  AND branch "X") OR (event "B" AND branch "Y").

The work-around in this PR is to insert two "copies" of the pipeline - one that triggers on (event "A"  AND branch "X"), and one that triggers on (event "B" AND branch "Y") - only at most one of the pipelines will ever run, and the notification should run now under just the combinations required. See the comments that I put in the code.

## Related Issue
- Fixes #4460 

## How Has This Been Tested?
CI - on this PR the chat-notification pipeline does not run, as required.

After merge, we need to observe what happens - the chat-notification step should be one of the pipelines.

Then we need to create a "dummy" release-xxx branch, put a commit in it, and push it to GitHub - no CI should run for the push.

Then create a "dummy" PR from release-xxx - CI should run including a chat-notification pipeline.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
https://docs.drone.io/pipeline/triggers/
"Please note that the target branch is evaluated for pull requests" - so the code here will not work. When the event is `pull_request` and it is the PR in the `release-n.n.n` branch, then the pull request is actually from `release-n.n.n` and to `master`.

Maybe I can write some actual starlark code to evaluate the event and branch name, and do the logic in starlark rather than in the drone trigger data structures.

**Comment by kulmann** [comment]
Please don't invest too much time. It's also feasible to just not use `release-` as a branch name prefix.

**Comment by kulmann** [comment]
> > Please don't invest too much time. It's also feasible to just not use `release-` as a branch name prefix.
> 
> What it is the requirement? Under what conditions/situations should CI report failures to rocket-chat?
> 
> I assumed that the issue was raised because the current drone starlark code does not meet the requirement, so we need to get it right and meet the requirements of the developers.

at the moment it just "reports too much". There was an entirely new drone job triggered with only a notification-task. but the other drone job (the one that looked normal) behaved like it should afaik.

**Comment by individual-it** [comment]
@phil-davis should we close this for now?

**Comment by individual-it** [comment]
I will close this for now as its not very important and there has not been any progress for a while

**Pull request closed without merging**
