### PR TITLE
Update web commit. fix flaky e2e

### PR DESCRIPTION
**Pull request by ScharfViktor**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ScharfViktor** [comment]
e2e is green https://drone.owncloud.com/owncloud/ocis/16723/59/10
without flaky

**Review by phil-davis — APPROVED** [review]
LGTM - how is this sort of thing being managed now that there is also a "stable" branch? Do we also apply this to the other branch?

**Comment by kulmann** [comment]
> LGTM - how is this sort of thing being managed now that there is also a "stable" branch? Do we also apply this to the other branch?

Yes, exactly. I cherry-picked the two commits into the `stable-6.0` branch when I created the branch. Now for ocis, if @micbar decides to have a `stable-2.0` branch we'd need to set `stable-6.0` as the web branch in `.drone.env` (only for the ocis stable branch, not for ocis master, obviously) and the commit id respectively.

**Review by kulmann — APPROVED** [review]
Normally needs a `[full-ci]` run. Since there are no other changes in web, I'm fine without it.

**Pull request merged**
