### PR TITLE
ci debug

### PR DESCRIPTION
**Pull request by dpakach**

### CODE REVIEW

**Comment by butonic** [comment]
@dpakach AFAICT the tests are failing because they are expected to fail, but the actually work (uploads work). I did not find a failure related to `ListAccounts` permissions ...

**Comment by dpakach** [comment]
Issue reproduced in the pipeline https://drone.owncloud.com/owncloud/ocis/1308/19/5

**Comment by refs** [comment]
@dpakach we cherry picked #6c9005e into this and were not able to reproduce the failure anymore. We opened a PR (#835) and are waiting for CI to end.

**Comment by dpakach** [comment]
@refs That's really cool. Thanks a lot. 
I will rerun it again just to make sure. @phil-davis fixed the bash scripts in core so we shouldn't have the red CI this time.

**Comment by dpakach** [comment]
fixed

**Pull request closed without merging**
