### PR TITLE
remove root Makefile and get rid of cd in drone ci

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
Looks OK.
Note: The `test-acceptance-api` make target and related code... is in `ocis/Makefile` already. So this PR reduces duplication by removing the root `Makefile`

**Comment by phil-davis** [comment]
Will this change the way to run acceptance tests? And maybe other things?
For example, instructions in https://github.com/owncloud/ocis/blob/master/docs/ocis/development/testing.md will need updating in this PR.

**Comment by wkloucek** [comment]
> Will this change the way to run acceptance tests? And maybe other things?
> For example, instructions in https://github.com/owncloud/ocis/blob/master/docs/ocis/development/testing.md will need updating in this PR.

I added a hint to the referenced testing docs.

There are tons of things to improve or even correct the docs, but I see this as out of scope for this PR. There is more progress going on like in #874

**Comment by phil-davis** [comment]
> There are tons of things to improve or even correct the docs, but I see this as out of scope for this PR

Yes, agree. Just make whatever changes are "obviously" needed because of this PR.

**Review by micbar — APPROVED** [review]

**Pull request merged**
