### PR TITLE
fix: always show full svg width

### PR DESCRIPTION
**Pull request by pReya**
## Description
Currently, SVG images are cut off on the right side of the viewport, depending on the size of your screen. Setting the width to `100%` will always scale the svg to fit the whole screen width.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

### CODE REVIEW

**Comment by butonic** [comment]
true, but on small screens `width="100%"` would make the text unreadable, right?

**Comment by wkloucek** [comment]
@pReya thanks for looking into this. I tried out your PR, but it seems like svg has no width... I did another PR which fixes the sizing, by using the figures instead of the svg tag https://github.com/owncloud/ocis/pull/3520

**Comment by wkloucek** [comment]
@pReya could you please check https://owncloud.dev again if it works for you now? You also can now use right-click -> open image in new tab. That wasn't possible before

**Comment by pReya** [comment]
@wkloucek Yes it works very well. Thanks for fixing this.

**Pull request closed without merging**
