### PR TITLE
Use MICRO_REGISTRY_ADDRESS env var for etcd address

### PR DESCRIPTION
**Pull request by ybr-nx**
## Description

`MICRO_REGISTRY_ADDRESS` used only in `ocis-pkg/registry/registry` and not here. It tried to connect to 127.0.0.1 instead.

### CODE REVIEW

**Comment by wkloucek** [comment]
@ybr-nx shouldn't this be sufficient and less code duplication?
```
func newGrpcClient() mclient.Client {
	r := *registry.GetRegistry()

	c := grpc.NewClient(
		mclient.RequestTimeout(10*time.Second),
		mclient.Registry(r),
	)
	return c
}
```

**Review by wkloucek — CHANGES_REQUESTED** [review]
Couldn't this be replaced by following?

```
func newGrpcClient() mclient.Client {
	r := *registry.GetRegistry()

	c := grpc.NewClient(
		mclient.RequestTimeout(10*time.Second),
		mclient.Registry(r),
	)
	return c
}
```

**Comment by ybr-nx** [comment]
Yes, it seems cleaner. I'll test it right away

**Comment by wkloucek** [comment]
Used test steps:
run etcd on non localhost / 127.0.0.1 interface. Eg. use your wifi or ethernet ip address:
```
docker run \
  -p 192.168.0.29:2379:2379 \
  -p 192.168.0.29:2380:2380 \
  --name etcd-v3.2.8 \
  --volume=/tmp/etcd-data.tmp:/etcd-data \
  gcr.io/etcd-development/etcd:v3.2.8 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://0.0.0.0:2379 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls http://0.0.0.0:2380 \
  --initial-cluster s1=http://0.0.0.0:2380 \
  --initial-cluster-token tkn
```

run oCIS:
```
export MICRO_REGISTRY=etcd
export MICRO_REGISTRY_ADDRESS=192.168.0.29
go run ./cmd/ocis
```

Try to log in on the web UI. Fails before this fix and works after this fix.

**Comment by wkloucek** [comment]
@ybr-nx Could you please add a change log in the folder `changelog` 

My proposal:

```
Bugfix: Fix etcd address configuration

The etcd server address in `MICRO_REGISTRY_ADDRESS` was not picked up when etcd was set as service discovery registry `MICRO_REGISTRY=etcd`. Therefore etcd was only working if available on localhost / 127.0.0.1.

https://github.com/owncloud/ocis/pull/1546
```

**Review by wkloucek — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by wkloucek** [comment]
@ybr-nx sorry that I need to come back to you again. Can you rebase your current branch or merge our master branch back to your branch? We had some big changes our master branch which caused that this PR can not be merged in the current state.

**Pull request merged**
