### PR TITLE
[docs-only] added services communication diagram

### PR DESCRIPTION
**Pull request by C0rby**
Added this diagram to the docs to show how our different services communicate with each other.
It's not complete, e.g. the nats service just "hangs in the air" because I didn't include the events stuff. There might also be some lines missing because it would make the diagram harder to grasp.

ocis-services-communication drawio

### CODE REVIEW

**Comment by rhafer** [comment]
Great! You might wanna add some arrows from the ocis/ocs service to accounts and the reva gateway

Now we just need to remember to keep this up to date everytime we change something. ;-)

**Review by dragotin — APPROVED** [review]
I love it! Thanks!

**Comment by micbar** [comment]
awesome! Small nitpick: next time remove the width and height attributes from the svg https://www.creativebloq.com/how-to/10-golden-rules-for-responsive-svgs

**Comment by C0rby** [comment]
Oh thanks for the hint. I'll do it next time.

**Pull request merged**
