### PR TITLE
[Tests-Only] enable ocs http integration tests

### PR DESCRIPTION
**Pull request by dpakach**
Enable OCS HTTP API tests
These tests were skipped when moving ocis to monorepo.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
I rebased. The last CI run was with a drone starlark that did not have #630 or #633 in it.
Maybe CI will be happy now?

**Comment by micbar** [comment]
Please rebase again. Good stuff!

**Comment by phil-davis** [comment]
Rebased again - let's see what CI thinks.

**Comment by micbar** [comment]
@refs Seems that some import paths havee problems

Seeing a lot of these
```
2020-10-02 13:55:06.112918 I | WARNING: proto: message proto.ListRoleAssignmentsRequest is already registered
	previously from: "github.com/owncloud/ocis/settings/pkg/proto/v0"
	currently from:  "github.com/owncloud/ocis-settings/pkg/proto/v0"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict```

**Comment by micbar** [comment]
@butonic @IljaN @refs IMO we should change the log level here. Should not be `ERR`

```
=== RUN   TestDeleteUserInvalidId
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/invalid: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0minvalid [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/3434234233: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m3434234233 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1am41validUs3r: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1am41validUs3r [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/_-@@--$$__: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m_-@@--$$__ [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/invalid: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0minvalid [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/3434234233: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m3434234233 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1am41validUs3r: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1am41validUs3r [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/_-@@--$$__: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m_-@@--$$__ [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/invalid: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0minvalid [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/3434234233: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m3434234233 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1am41validUs3r: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1am41validUs3r [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/_-@@--$$__: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m_-@@--$$__ [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/invalid: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0minvalid [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/3434234233: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m3434234233 [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/1am41validUs3r: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m1am41validUs3r [36mservice=[0maccounts
[90m2020-10-02T13:55:07Z[0m [1m[31mERR[0m[0m could not load account [31merror=[0m[31m"{\"id\":\".\",\"code\":404,\"detail\":\"could not read account: open accounts-store/accounts/_-@@--$$__: no such file or directory\",\"status\":\"Not Found\"}"[0m [36mid=[0m_-@@--$$__ [36mservice=[0maccounts
--- PASS: TestDeleteUserInvalidId (0.05s)
```

**Comment by refs** [comment]
> @refs @phil-davis Seems that some import paths have problems
> 
> Seeing a lot of these
> 
> ```
> 2020-10-02 13:55:06.112918 I | WARNING: proto: message proto.ListRoleAssignmentsRequest is already registered
> 	previously from: "github.com/owncloud/ocis/settings/pkg/proto/v0"
> 	currently from:  "github.com/owncloud/ocis-settings/pkg/proto/v0"
> A future release will panic on registration conflicts. See:
> https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
> ```

yup having a look at the deps added just saw this:

https://github.com/owncloud/ocis/pull/634/files#diff-2a05942340db9712f0b7c3d439c21bceR1238

**Comment by refs** [comment]
@micbar and that is because I think `ocs` is missing a replace for `ocis-settings` in its go.mod:

https://github.com/owncloud/ocis/blob/enable-ocs-http-tests/ocs/go.mod

**Review by micbar — CHANGES_REQUESTED** [review]
See comments.

**Comment by refs** [comment]
this bit:

```
replace (
	github.com/owncloud/ocis/accounts => ../accounts
	github.com/owncloud/ocis/ocis-pkg => ../ocis-pkg
	github.com/owncloud/ocis/store => ../store
	google.golang.org/grpc => google.golang.org/grpc v1.26.0
)
```

should include this:

```
replace (
	github.com/owncloud/ocis/accounts => ../accounts
	github.com/owncloud/ocis/ocis-pkg => ../ocis-pkg
	github.com/owncloud/ocis/settings => ../settings
	github.com/owncloud/ocis/store => ../store
	google.golang.org/grpc => google.golang.org/grpc v1.26.0
)
```

**Comment by dpakach** [comment]
@micbar @refs, Fixed the replace path in go.mod. Please review :+1:

**Comment by dpakach** [comment]
Tests passed without any complaining
https://drone.owncloud.com/owncloud/ocis/253/7/6

**Review by micbar — APPROVED** [review]
Great!

**Pull request merged**
