### PR TITLE
graph: add identities property to non-admin response of GetUsers

### PR DESCRIPTION
**Pull request by rhafer**
Fixes: #9813

### CODE REVIEW

**Comment by rhafer** [comment]
Hm, I just noticed that  the demo users don't have the 'Identities' value configured yet. I'll add a fix.

**Comment by ScharfViktor** [comment]
- I switched to your branch
- `make -C ocis clean generate build`
- run test `TEST_SERVER_URL="https://ocis-server:9200" TEST_SERVER_FED_URL="https://federation-ocis-server:10200" BEHAT_FEATURE="tests/acceptance/features/apiOcm/searchFederationUsers.feature:16" make test-acceptance-api`

Actual: response doesn't contain identities
image

**Comment by rhafer** [comment]
> Actual: response doesn't contain identities

Currently only federated users are guaranteed to have the `identities` property. Users of type `Member` only have `identities` if explicitly set when creating them.

I guess we should adjust that so that the `identities` property is automatically populated when creating a user.

**Comment by ScharfViktor** [comment]
now it's work 👍 thank you
image

**Comment by ScharfViktor** [comment]
> Hm, I just noticed that the demo users don't have the 'Identities' value configured yet. I'll add a fix.

tested it. works fine 👍 

I'll merge your PR and change my tests https://github.com/owncloud/ocis/pull/9812

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
