### PR TITLE
[tests-only] [full-ci] Test for mail notification to group members if a space is shared

### PR DESCRIPTION
**Pull request by ghost**
Description

This PR back ports https://github.com/owncloud/ocis/pull/6633

### CODE REVIEW

**Review by SwikritiT — APPROVED** [review]
LGTM if ci is also happy

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/23692/52/1) failed. Further test are cancelled...

**Review by SagarGi — APPROVED** [review]

**Review by grgprarup — APPROVED** [review]
:+1:

**Comment by grgprarup** [comment]
The failure is in `Codacy Static Code Analysis`, `It seems like the branch stable-3.0 is not being analyzed.`, other looks good. So merging this PR.

**Pull request merged**
