### PR TITLE
To fix ocis ps the default name of go micro runtime is set to com.own…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…cloud.runtime

### CODE REVIEW

**Comment by refs** [comment]
Is this intended to fix `ocis ps`?

**Comment by DeepDiver1975** [comment]
> Is this intended to fix `ocis ps`?

yes - with this I at least no longer get an error when trying to connect to micro .... but there is no return either .... :man_shrugging:

**Comment by DeepDiver1975** [comment]
@refs no idea if this is the right thing to do ....

**Comment by DeepDiver1975** [comment]
I'll close this - no prio ....

**Pull request closed without merging**
