### PR TITLE
Update accounts, idp, settings JS dependencies

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
- will supersede a bunch of dependabot PRs
- bumps ODS in `accounts` & `settings` to current version
- cleaned up (dev)Dependencies in `settings`

### CODE REVIEW

**Comment by C0rby** [comment]
I think you still need to run `make generate` to make the changes be used.

**Comment by pascalwengerter** [comment]
> I think you still need to run `make generate` to make the changes be used.

I did run `make generate` in repo root (same goes for the last PR that did something similar) yet there was nothing more to commit both times (which struck me as odd since usually there would be modified `embed.go` files coming with those changes, but I didn't think too much about it). Could you investigate?

**Comment by phil-davis** [comment]
Pipeline https://drone.owncloud.com/owncloud/ocis/6447/7/5 died with:
```
{"level":"error","service":"storage","error":"listen tcp 0.0.0.0:9215: bind: address already in use","time":"2021-08-19T11:07:54.940806083Z","message":"error getting sockets"}
```

I restarted CI.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by pascalwengerter** [comment]
@C0rby @kulmann can I get a very careful review from you if CI is happy with this one? Rebased on current master, removed the `onlyoffice` stuff, refactored dependencies in `settings` and wildly upgraded dependencies (and fixed nightwatch-based stuff for now so CI doesn't break, Florian has a pending fix that allows a nightwatch bump in https://github.com/owncloud/web/pull/5675)

**Review by kulmann — APPROVED** [review]
LGTM 👍 also gave it a try locally, which looked fine as well. 🚀

**Pull request merged**
