### PR TITLE
[tests-only] bump phoenix commit it to current top of master

### PR DESCRIPTION
**Pull request by individual-it**
there are more suites running currently in the phoenix repo (specially sharing tests), I will add those to this repo in a separate PR

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
It will be great if it is this easy.

**Comment by phil-davis** [comment]
`phoenixWebUI4` has a lot of suites in it, and they now have lots of scenarios enabled. So that pipeline is running for a long time.
It is probably work splitting it in this PR.

**Comment by individual-it** [comment]
I've split the UI tests once more and additionally bumped the commit id again to get the changes of https://github.com/owncloud/phoenix/commit/2fabcb8bf376dbbdff9bb7e787dbee5c334b4a7b
issue to follow up with the waiting for negative checks https://github.com/owncloud/phoenix/issues/4232

**Review by phil-davis — COMMENTED** [review]
Note: the comment "All tests in the following suites are skipped currently" is not correct any more - `.drone.star` lines 44 and 45 can be deleted some time to avoid future confusion.

**Comment by phil-davis** [comment]
phoenixWebUI4 took 43 minutes
phoenixWebUI5 took >50 minutes

I split them again.

**Comment by phil-davis** [comment]
phoenixWebUI7 is taking a bit long. But that should be improved by adjusting step timeouts issue https://github.com/owncloud/phoenix/issues/4231

**Pull request merged**
