### PR TITLE
[tests-only][full-ci]Remove GitHub comment from ci

### PR DESCRIPTION
**Pull request by SwikritiT**
Backport: https://github.com/owncloud/ocis/pull/6783

## Description
Last week we removed the drone code to stop previous PR builds, and to cancel a build early when a single pipeline fails.

The remaining special CI feature that we have is the drone code that posts a comment to GitHub about a failing acceptance test pipeline. That no longer works because it needs a GitHub token with too many permissions, and we do not make that available to PRs.

This PR removes the GitHub comment code from the drone CI. The `earlyFail` setting is also removed, because there is nothing that uses it any more

the link for tracing result is shown in the console instead of comments

Part of: https://github.com/owncloud/QA/issues/820

### CODE REVIEW

**Comment by SwikritiT** [comment]
`docs downstream` wasn't present in this branch

**Comment by SwikritiT** [comment]
I've cherry picked https://github.com/owncloud/ocis/pull/6789/commits

**Review by micbar — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/24306/65/5
```
runsh: Total unexpected failed scenarios throughout the test run:
coreApiWebdavPreviews/previews.feature:146
```
Is that a known flaky test scenario?
I will restart CI.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
