### PR TITLE
Refactor extensions to services.

### PR DESCRIPTION
**Pull request by dragonchaser**
We have decided to name all extensions, we maintain and provide with ocis,
services from here on to avoid confusion between external extensions and code
we provide and maintain.

fixes: #3926 

/cc @mmattel

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/12646/38/1) failed. Further test are cancelled...

**Review by wkloucek — APPROVED** [review]
LGTM, there may be still some "extensions" references in the docs. We can check that after the merge.

**Review by phil-davis — APPROVED** [review]
LGTM

**Review by micbar — CHANGES_REQUESTED** [review]
Let us discuss the perfect time please

**Comment by dragonchaser** [comment]
@phil-davis && @micbar we suggest rebasing & merging this tomorrow afternoon (around 3PM CET) to avoid greater chaos :boom:

**Comment by dragonchaser** [comment]
do not merge before .beta4 is released!

**Review by wkloucek — CHANGES_REQUESTED** [review]
merge only after beta.4 release

**Review by wkloucek — APPROVED** [review]
Let's merge it now that beta.4 was released

**Pull request merged**
