### PR TITLE
verify all system accounts are set

### PR DESCRIPTION
**Pull request by butonic**
while we are configuring them in ocis init, we are not verifying if they are set. This allows the service to start with a broken configuration that leads to failing requests.

### CODE REVIEW

**Review by 2403905 — APPROVED** [review]

**Comment by 2403905** [comment]
Should we also validate for the `ocm` ?
[https://github.com/owncloud/ocis/blob/4427c9f032c816e5f9cbc7a091dc6e545f7f2bec/services/ocm/pkg/config/config.go#L61](https://github.com/owncloud/ocis/blob/4427c9f032c816e5f9cbc7a091dc6e545f7f2bec/services/ocm/pkg/config/config.go#L61)

**Comment by butonic** [comment]
related: https://github.com/owncloud/ocis/issues/8107

**Comment by butonic** [comment]
init does not set the service account for ocm, so this needs to go into v5 as well

**Comment by butonic** [comment]
@2403905 thx, added, please rereview

**Comment by micbar** [comment]
please backport to stable-5.0

**Pull request merged**
