### PR TITLE
Remove expires header for no-cache assets

### PR DESCRIPTION
**Pull request by fschade**
## Description
Expires header was set even if no-cache header is present, this pr removes it.

### CODE REVIEW

**Review by kobergj — APPROVED** [review]

**Comment by fschade** [comment]
@micbar yes, but not before monday :)

**Comment by micbar** [comment]
@fschade now backport? 😄

**Comment by micbar** [comment]
@kulmann @fschade ping :-)

**Comment by fschade** [comment]
@micbar ✅ https://github.com/owncloud/ocis/pull/4942

**Pull request merged**
