### PR TITLE
Set english as default language

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Show English as default language in the settings

## Related Issue
https://github.com/owncloud/ocis/issues/2126

## How Has This Been Tested?
Manually tested in a fresh environment

1. Login with a user
2. Check the settings page

English is selected a language

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Review by refs — APPROVED** [review]

**Comment by jvillafanez** [comment]
It seems drone needs some kicking... I don't think we need to touch any additional code for the tests.

**Review by pascalwengerter — APPROVED** [review]
Thanks for taking care!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by pascalwengerter** [comment]
Needs a fix in `ocis/settings/ui/tests/acceptance/features/settings.feature:16`, most probably `Then the setting "Language" should have value "English"`

**Pull request merged**
