### PR TITLE
ci: split e2e test pipeline (#6817)

### PR DESCRIPTION
**Pull request by saw-jan**
Port of https://github.com/owncloud/ocis/pull/6817

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
`tikaNeeded` is not being used.
That is different to what was done in master.

**Comment by ScharfViktor** [comment]
> `tikaNeeded` is not being used. That is different to what was done in master.

let me port https://github.com/owncloud/ocis/pull/6797 to stable-3.0 before

**Comment by ScharfViktor** [comment]
@saw-jan rebase please after merging: https://github.com/owncloud/ocis/pull/6827

**Comment by saw-jan** [comment]
> rebase please after merging: #6827

Okey, I will bring back the tika step as well

**Comment by phil-davis** [comment]
@saw-jan the other PR has been merged. You can rebase this and resolves the conflict in `.drone.star`

**Review by phil-davis — APPROVED** [review]

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
