### PR TITLE
[full-ci] Bump reva

### PR DESCRIPTION
**Pull request by aduffeck**
Bump reva to bring in the the latest fixes.

Fixes https://github.com/owncloud/ocis/issues/5025
Fixes https://github.com/owncloud/ocis/issues/5027
Fixes https://github.com/owncloud/ocis/issues/4506

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/16772/42/1) failed. Further test are cancelled...

**Review by micbar — APPROVED** [review]
LGTM

**Comment by butonic** [comment]
https://drone.owncloud.com/owncloud/ocis/16787/42/6
```
runsh: Total unexpected failed scenarios throughout the test run:
apiSpaces/changeSpaces.feature:222
apiSpaces/changeSpaces.feature:223
apiSpaces/changeSpaces.feature:224
apiSpaces/changeSpaces.feature:225
```


https://drone.owncloud.com/owncloud/ocis/16787/43/6
```
runsh: Total unexpected failed scenarios throughout the test run:
apiSpacesShares/shareOperations.feature:317
apiSpacesShares/shareOperations.feature:331
apiSpacesShares/shareOperations.feature:345
```

**Comment by butonic** [comment]
```
  Scenario Outline: An admin user set an user personal space quota of via the Graph API                                                       # /drone/src/tests/acceptance/features/apiSpaces/changeSpaces.feature:215
    When user "Admin" changes the quota of the "Brian Murphy" space to "<quotaValue>"                                                         # SpacesContext::updateSpaceQuota()
    Then the HTTP status code should be "200"                                                                                                 # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    When user "Brian" uploads a file inside space "Brian Murphy" with content "file is more than 15 bytes" to "file.txt" using the WebDAV API # SpacesContext::theUserUploadsAFileToSpace()
    Then the HTTP status code should be <code>                                                                                                # FeatureContext::thenTheHTTPStatusCodeShouldBe()

    Examples:
      | quotaValue | code                    |
      | 15         | "507"                   |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 404 is not the expected value 200
        Failed asserting that 404 matches expected '200'.
      | 10000      | between "201" and "204" |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 404 is not the expected value 200
        Failed asserting that 404 matches expected '200'.
      | 0          | between "201" and "204" |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 404 is not the expected value 200
        Failed asserting that 404 matches expected '200'.
      | -1         | between "201" and "204" |
        Failed step: Then the HTTP status code should be "200"
        HTTP status code 404 is not the expected value 200
        Failed asserting that 404 matches expected '200'.
```

**Comment by butonic** [comment]
local api tests turning green: https://drone.owncloud.com/owncloud/ocis/16791
🤞

**Comment by ScharfViktor** [comment]
test https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiSpaces/search.feature#L96 still failed and I could not find space by name localy

**Comment by ScharfViktor** [comment]
re-tested #5027 and  #5027 - work correct

**Pull request merged**
