### PR TITLE
[full-ci] chore: bump web to v9.1.0-alpha.1

### PR DESCRIPTION
**Pull request by kulmann**
bumping web to pre-release `v9.1.0-alpha.1`

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Review by AlexAndBear — APPROVED** [review]

**Comment by micbar** [comment]
License check is failing.

**Comment by kulmann** [comment]
> License check is failing.

Tried different web commit ids now... either the license check is failing or a whole lot of e2e tests are failing. All that despite all CI runs in web were successful. I don't get it...

**Comment by kulmann** [comment]
Running a `[full-ci]` without bumping web here: https://github.com/owncloud/ocis/pull/9502

**Comment by ScharfViktor** [comment]
image

@kulmann  that seems to be problem.

`RuntimeError: cannot load application, web-app-markdown-editor, RuntimeError: cannot load application as only a name (and no path) is given and that name is not known to the application import map`

**Comment by ScharfViktor** [comment]
and the place where it failed: https://github.com/owncloud/web/pull/11103/files#diff-6e1c7ab5d6495d865bb158ce549fef1c2cd6e63516c7509b4dafd49990c94bc3

**Comment by SagarGi** [comment]
> and the place where it failed: https://github.com/owncloud/web/pull/11103/files#diff-6e1c7ab5d6495d865bb158ce549fef1c2cd6e63516c7509b4dafd49990c94bc3

May be @ScharfViktor finding can be useful for you @grgprarup since you are looking over it.

**Comment by kulmann** [comment]
Aaaaaah thank you! The app name is the deprecated app name. It was removed meanwhile. So that's a config issue. It needs to be `text-editor`, not `markdown-editor`.

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
