### PR TITLE
[Tests-Only] Add StepThroughExtension to acceptance test runner

### PR DESCRIPTION
**Pull request by phil-davis**
Support for this in the core acceptance test runner was added in https://github.com/owncloud/core/pull/37915 (see that PR for details - tests can be can be run 1 step at a time)

- bump the core commit to get that
- add the extension to the Behat pieces here for the test runner

### CODE REVIEW

**Review by micbar — APPROVED** [review]
I trust your expertise. What is the benefit?

**Comment by phil-davis** [comment]
A developer can set `STEP_THROUGH=true` when running a test scenario locally. The test runner will execute 1 step, prompt the developer to continue. So you can leave the test stopped at any point while you look around on the system-under-test to see what is happening.

@butonic was interested in this sort of thing for debugging. I found the extension for it and it turned out to be really easy to add it to Behat.

**Comment by phil-davis** [comment]
It will be easy to add to the upcoming mono repo.

**Comment by phil-davis** [comment]
drone problems - restarting

**Pull request merged**
