### PR TITLE
Update phoenix 0.29.0

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
generate assets are broken. Could you please run `cd ocis-phoenix && rm -r assets && make generate`?

**Comment by LukasHirt** [comment]
> generated assets are broken. Could you please run cd ocis-phoenix && rm -r assets && make generate?

Done. I've changed slightly the makefile to run even if the `assets` folder exists and to delete it before pulling the assets.

**Review by kulmann — APPROVED** [review]
🚀

**Comment by kulmann** [comment]
> Done. I've changed slightly the makefile to run even if the `assets` folder exists and to delete it before pulling the assets.

Awesome! :-)

**Pull request merged**
