### PR TITLE
fix shareroot path in REPORT responses

### PR DESCRIPTION
**Pull request by C0rby**
When doing a REPORT request the `shareroot` attribute contained the path `/folder/test.txt` even though only `test.txt` was shared with a user.
Now the response contains `/test.txt`.

Responses look like this now:
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:s="http://sabredav.org/ns" xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:37249330-862f-44f5-8736-eea58feadb46</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!3cbbda33-1e52-4aca-b9e7-4dd27981f567</oc:fileid>
        <oc:file-parent>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!42503198-a6e9-4975-bd07-5f7fcdaf239c</oc:file-parent>
        <oc:shareid>1284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:37249330-862f-44f5-8736-eea58feadb46</oc:shareid>
        <oc:shareroot>/test.txt</oc:shareroot>
        <oc:name>test.txt</oc:name>
        <d:getlastmodified>2022-10-18T13:22:29Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>SRM</oc:permissions>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>13</d:getcontentlength>
        <oc:score>1.803070306777954</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:5e95ec29-77b8-40b7-9e4c-55f8c42bcd87</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!7f26798b-b29b-4018-a7dd-b1c8fa238ba6</oc:fileid>
        <oc:file-parent>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!01a54531-bf53-440e-972e-01a5f053c0d7</oc:file-parent>
        <oc:shareid>1284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:5e95ec29-77b8-40b7-9e4c-55f8c42bcd87</oc:shareid>
        <oc:shareroot>/test.txt</oc:shareroot>
        <oc:name>test.txt</oc:name>
        <d:getlastmodified>2022-10-18T13:22:11Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>SRM</oc:permissions>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>8</d:getcontentlength>
        <oc:score>1.803070306777954</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:a637933e-1298-4e7d-b8d9-4ae5db34826e/folder3test.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!00e6e92b-a3aa-4e27-aa2a-2fb98625dbde</oc:fileid>
        <oc:file-parent>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!915bf533-f215-4e81-8e5c-f8b99d3e01e7</oc:file-parent>
        <oc:shareid>1284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:a637933e-1298-4e7d-b8d9-4ae5db34826e</oc:shareid>
        <oc:shareroot>/folder3</oc:shareroot>
        <oc:name>folder3test.txt</oc:name>
        <d:getlastmodified>2022-10-19T12:57:35Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>SR</oc:permissions>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>7</d:getcontentlength>
        <oc:score>1.1522295475006104</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:9b80c8b8-4045-44f7-8dd9-13b5fc617cd8/folder2test.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!5c7b2e53-42d8-424e-842c-f7127ead03b1</oc:fileid>
        <oc:file-parent>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!1d02ac2b-ff7c-4f1b-99f0-b74720c90327</oc:file-parent>
        <oc:shareid>1284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:9b80c8b8-4045-44f7-8dd9-13b5fc617cd8</oc:shareid>
        <oc:shareroot>/folder2</oc:shareroot>
        <oc:name>folder2test.txt</oc:name>
        <d:getlastmodified>2022-10-19T12:57:03Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>SR</oc:permissions>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>7</d:getcontentlength>
        <oc:score>0.7507680058479309</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668%211284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:9b80c8b8-4045-44f7-8dd9-13b5fc617cd8/subfolder2/subfolder2test.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:fileid>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!c8c173dc-596e-4334-aac8-c673faf854cf</oc:fileid>
        <oc:file-parent>1284d238-aa92-42ce-bdc4-0b0000009157$01a54531-bf53-440e-972e-01a5f053c0d7!6e4b9353-d889-4323-8dbb-bcf00f7576f4</oc:file-parent>
        <oc:shareid>1284d238-aa92-42ce-bdc4-0b0000009157:01a54531-bf53-440e-972e-01a5f053c0d7:9b80c8b8-4045-44f7-8dd9-13b5fc617cd8</oc:shareid>
        <oc:shareroot>/folder2</oc:shareroot>
        <oc:name>subfolder2test.txt</oc:name>
        <d:getlastmodified>2022-10-19T14:48:53Z</d:getlastmodified>
        <d:getcontenttype>text/plain</d:getcontenttype>
        <oc:permissions>SR</oc:permissions>
        <d:getetag/>
        <d:resourcetype/>
        <d:getcontentlength>10</d:getcontentlength>
        <oc:score>0.7507680058479309</oc:score>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/4796

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Code changes

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by ScharfViktor** [comment]
CI is red due https://github.com/owncloud/ocis/issues/4849 Try to restart

**Comment by ScharfViktor** [comment]
or can we bump `WEB_COMMIT=1e20bc5fbaf396930ca5b9c5c584b3ad2a9dc1c6` here?

**Comment by C0rby** [comment]
> or can we bump `WEB_COMMIT=1e20bc5fbaf396930ca5b9c5c584b3ad2a9dc1c6` here?

I'll try that here. Let's see if that already fixes it. :+1:

**Comment by ScharfViktor** [comment]
new fail (another test). User-viewer of the project space has an available "delete" in the trash bin:
Screenshot 2022-10-20 at 11 36 27

expected behavior: no available button "delete" on the web
image

**Comment by C0rby** [comment]
Let's hope this works now. :+1:

**Comment by C0rby** [comment]
Perfect, thank you very much. :+1:

**Pull request merged**
