### PR TITLE
update extensions

### PR DESCRIPTION
**Pull request by micbar**
## Description
We've updated various extensions to a tagged release:
- ocis-phoenix v0.4.0 (phoenix v0.7.0)
- ocis-pkg v2.2.0
- ocis-proxy v0.3.1
- ocis-reva v0.1.1
- ocis-thumbnails v0.1.0
- ocis-webdav v0.1.0

### CODE REVIEW

**Comment by micbar** [comment]
@C0rby Do we need extra config for the thumbnails?

on my instance i cannot see them

**Comment by micbar** [comment]
ah sh*t
Phoenix is still on 0.6.0

I forgot to update the assets

**Comment by labkode** [comment]
For Reva:
https://github.com/cs3org/reva/issues/614

**Comment by micbar** [comment]
@C0rby Can you check the phoenix version?

If I build locally, I still get `v0.6.0`

**Comment by micbar** [comment]
Updated ocis-phoenix to `v0.4.1`

**Pull request merged**
