### PR TITLE
Restoring spaces graph endpoint

### PR DESCRIPTION
**Pull request by kobergj**
## Description
Restore spaces by sending to the Patch Drive Graph endpoint. Get information when a drive is deleted (Check it's root for "deleted" flag) 

### Step 1: Find spaceID
```bash
curl -k https://localhost:9200/graph/v1.0/me/drives -u admin:admin 
```
```json
...
{
      "driveType": "project",
      "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
      "lastModifiedDateTime": "2022-02-04T09:07:45.824270628+01:00",
      "name": "Project PUPPELE",
      "owner": {
        "user": {
          "id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
        }
      },
      "quota": {
        "remaining": 1000000000,
        "state": "normal",
        "total": 1000000000,
        "used": 0
      },
      "root": {
        "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
        "webDavUrl": "https://localhost:9200/dav/spaces/db589b97-f2ea-4864-bf5f-55a43325f77a"
      }
}
...
```

### Step 2: Disable the space
```bash
curl -X DELETE -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin
```
Note that response on GET endpoint changes. It contains information that the drive is trashed. Calling curl from Step1 would return:
```json
 {
      "driveType": "project",
      "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
      "lastModifiedDateTime": "2022-02-04T09:07:45.824270628+01:00",
      "name": "Project PUPPELE",
      "owner": {
        "user": {
          "id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
        }
      },
      "quota": {
        "remaining": 1000000000,
        "state": "normal",
        "total": 1000000000,
        "used": 0
      },
      "root": {
        "deleted": {
          "state": "trashed"
        },
        "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
        "webDavUrl": "https://localhost:9200/dav/spaces/db589b97-f2ea-4864-bf5f-55a43325f77a"
      }
}
``` 
### Step 3a: Restore the space
This will restore the space and everything will be like before
```bash
curl -X PATCH -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin -H "restore: true" -d '{}'
```
### Step 3b: Delete the space
This will remove the space completely
```bash
curl -X DELETE -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin -H "purge: true"
```

Note that delete and purge requests now use the same URL, just a different header. Purging an enabled space will still not work. Step 2 is mandatory.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/9112/20/1) failed. Further test are cancelled...

**Comment by kobergj** [comment]
Short example for space restore/delete

### Step 1: Find spaceID
```bash
curl -k https://localhost:9200/graph/v1.0/me/drives -u admin:admin 
```
```json
...
{
      "driveType": "project",
      "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
      "lastModifiedDateTime": "2022-02-04T09:07:45.824270628+01:00",
      "name": "Project PUPPELE",
      "owner": {
        "user": {
          "id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
        }
      },
      "quota": {
        "remaining": 1000000000,
        "state": "normal",
        "total": 1000000000,
        "used": 0
      },
      "root": {
        "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
        "webDavUrl": "https://localhost:9200/dav/spaces/db589b97-f2ea-4864-bf5f-55a43325f77a"
      }
}
...
```

### Step 2: Disable the space
```bash
curl -X DELETE -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin
```
Note that response on GET endpoint changes. It contains information that the drive is trashed. Calling curl from Step1 would return:
```json
 {
      "driveType": "project",
      "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
      "lastModifiedDateTime": "2022-02-04T09:07:45.824270628+01:00",
      "name": "Project PUPPELE",
      "owner": {
        "user": {
          "id": "ddc2004c-0977-11eb-9d3f-a793888cd0f8"
        }
      },
      "quota": {
        "remaining": 1000000000,
        "state": "normal",
        "total": 1000000000,
        "used": 0
      },
      "root": {
        "deleted": {
          "state": "trashed"
        },
        "id": "db589b97-f2ea-4864-bf5f-55a43325f77a",
        "webDavUrl": "https://localhost:9200/dav/spaces/db589b97-f2ea-4864-bf5f-55a43325f77a"
      }
}
``` 
### Step 3a: Restore the space
This will restore the space and everything will be like before
```bash
curl -X PATCH -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin -H "restore: true" -d '{}'
```
### Step 3b: Delete the space
This will remove the space completely
```bash
curl -X DELETE -k https://localhost:9200/graph/v1.0/drives/db589b97-f2ea-4864-bf5f-55a43325f77a -u admin:admin -H "purge: true"
```

Note that delete and purge requests now use the same URL, just a different header. Purging an enabled space will still not work. Step 2 is mandatory.

**Review by micbar — APPROVED** [review]
LGTM

**Comment by micbar** [comment]
@kobergj can you move the description into the top post please? That makes it easier in the future.

**Pull request merged**
