### PR TITLE
Fix accounts list scroll

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Like you said, assets need to be re-generated. Also, I noticed that - at least for me - the accounts list doesn't show scrollbars on scrolling.

**Comment by LukasHirt** [comment]
> Also, I noticed that - at least for me - the accounts list doesn't show scrollbars on scrolling.

Odd. I see it nicely.

image

**Comment by kulmann** [comment]
> > Also, I noticed that - at least for me - the accounts list doesn't show scrollbars on scrolling.
> 
> Odd. I see it nicely.

Weird. Now I have the scrollbar as well...
Anyway, assets are updated.

**Review by kulmann — APPROVED** [review]
🚀

**Pull request merged**
