### PR TITLE
graph: Add support for "or" filter on /users

### PR DESCRIPTION
**Pull request by rhafer**
This add support for combining filters on the /users with a logical "or" operation. E.g. the filter:

"filter=(memberOf/any(m:m/id eq 509a9dcd-bb37-4f4f-a01a-19dca27d9cfa) or memberOf/any(m:m/id eq 262982c1-2362-4afa-bfdf-8cbfef64a06e)"

will return all users that are a member of either of the referenced group.

Closes: #5667

Examples added to the libregraph spec in: https://github.com/owncloud/libre-graph-api/pull/96

### CODE REVIEW

**Comment by rhafer** [comment]
@JammingBen This should make or filters for groups work:

```
(memberOf/any(x:x/id eq 910367f9-4041-4db1-961b-d1e98f708eaf) or memberOf/any(x:x/id eq 4cceeace-b8ca-472a-9788-e73da11de14c)) and appRoleAssignments/any(x:x/appRoleId eq 910367f9-4041-4db1-961b-d1e98f708eaf)
```

Please note the `()` around the or query. Without them the `and` would take precedence.

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-2</strong>](https://drone.owncloud.com/owncloud/ocis/19661/63/1) failed. Further test are cancelled...

**Comment by mmattel** [comment]
Hooking myself in just because to review the admin docs for possible changes

**Review by JammingBen — COMMENTED** [review]
Works like a charm! As always, can't review the technical side though.

**Review by Excds — APPROVED** [review]

**Pull request merged**
