### PR TITLE
[full-ci] update web to v5.7.0-rc.10

### PR DESCRIPTION
**Pull request by kulmann**
bump ownCloud Web to v5.7.0-rc.10

### CODE REVIEW

**Comment by C0rby** [comment]
I don't really get the CI errors... :confused: 
When I run oCIS locally it works fine but I'm not yet running the UI test suite so maybe I'm missing some crucial setup option or so.

**Comment by C0rby** [comment]
Ok, even with the test suite it's working locally... :confused:

**Comment by fschade** [comment]
@C0rby, i see a lot of fishy errors... https://drone.owncloud.com/owncloud/ocis/14829/54/9

**Comment by C0rby** [comment]
> @C0rby, i see a lot of fishy errors... https://drone.owncloud.com/owncloud/ocis/14829/54/9

Do you mean the events errors or something else?

**Comment by kulmann** [comment]
> @individual-it, can you please have a look, we do not find why the tests are failing...

a little more context for that:
- web CI on the linked commit id was successful
- ocis commit id in web is not up to date (5 days old)
- all web scenarios in this PR are failing
- test middleware is up to date

I'd suspect that this is some kind of config issue, but I don't see anything that has changed in that regard. Maybe you have an idea...

**Comment by kulmann** [comment]
Just now I realized that the e2e tests are passing. So the issue is only with the nightwatch acceptance tests apparently.

**Comment by kulmann** [comment]
Create [a PR in web](https://github.com/owncloud/web/pull/7509) with screenshots from CI enabled. maybe that gives us a clue...

**Comment by kulmann** [comment]
> Created [a PR in web](https://github.com/owncloud/web/pull/7509) with screenshots from CI enabled. maybe that gives us a clue...

aaand acceptance tests for this PR here seem to pass in the web CI.

**Comment by SwikritiT** [comment]
I'll take a look at what's happening

**Comment by phil-davis** [comment]
Note: This branch is [3 commits ahead](https://github.com/owncloud/ocis/compare/master...update-web-v5.7.0-rc.10), [3 commits behind](https://github.com/owncloud/ocis/compare/update-web-v5.7.0-rc.10...master) master.

This branch does not have #4444 "update reva". It would be good to also know/test that this web update works with the really latest reva.

**Comment by kulmann** [comment]
> Note: This branch is [3 commits ahead](https://github.com/owncloud/ocis/compare/master...update-web-v5.7.0-rc.10), [3 commits behind](https://github.com/owncloud/ocis/compare/update-web-v5.7.0-rc.10...master) master.
> 
> 
> 
> This branch does not have #4444 "update reva". It would be good to also know/test that this web update works with the really latest reva.

Yes, true. Feel free to rebase :-)

**Comment by SwikritiT** [comment]
Locally while running the tests there's this popup 
test

And the test fail in the similar way as in CI 
```
Scenario: Delete multiple files at once on a public share # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:204
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/data.zip" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/simple-empty-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ When the public uses the webUI to access the last public link created by user "Alice" in a new session # stepDefinitions/publicLinkContext.js:51
   ✖ And the user batch deletes these files using the webUI # stepDefinitions/filesContext.js:487
       | name                |
       | data.zip            |
       | lorem.txt           |
       | simple-empty-folder |
       Timed out while waiting for element <//button[contains(@class, "oc-files-actions-delete-")]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10025ms)
           at Proxy.deleteAllCheckedFiles (/home/swikriti/www/web/tests/acceptance/pageObjects/personalPage.js:232:19)
           at World.<anonymous> (/home/swikriti/www/web/tests/acceptance/stepDefinitions/filesContext.js:493:37)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
   - Then as "Alice" file "simple-folder/data.zip" should not exist in the server # stepDefinitions/middlewareContext.js:66
   - And as "Alice" file "simple-folder/lorem.txt" should not exist in the server # stepDefinitions/middlewareContext.js:66
   - And as "Alice" folder "simple-folder/simple-empty-folder" should not exist in the server # stepDefinitions/middlewareContext.js:66
   - And the deleted elements should not be listed on the webUI # stepDefinitions/filesContext.js:402
   - And the deleted elements should not be listed on the webUI after a page reload # stepDefinitions/filesContext.js:406
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:262
   ✔ After # stepDefinitions/generalContext.js:231
   ✔ After # stepDefinitions/generalContext.js:172
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80
```
I'll rebase and push and look more into it

**Comment by SwikritiT** [comment]
`golangci-lint` keeps on failing in one pipeline or another in every run 😢

**Comment by kulmann** [comment]
@SwikritiT could you tell me which requests are failing with a 401 (see network tab in browser dev tools) if you cancel the basic auth popup?

**Comment by SwikritiT** [comment]
@kulmann This is failing with `401`

```
Request URL: https://host.docker.internal:9200/accounts.js
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 127.0.0.1:9200
Referrer Policy: strict-origin-when-cross-origin
```
## OCIS LOG
```console
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60008: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60012: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60014: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60016: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60020: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60018: remote error: tls: unknown certificate
2022/08/24 12:50:35 http: TLS handshake error from 127.0.0.1:60024: remote error: tls: unknown certificate

```

**Comment by SwikritiT** [comment]
The Ci has already failed in `generate-go` and `golint`. I'll restart the build

**Comment by kulmann** [comment]
@C0rby When I open the settings app via the user menu (top right) and do a page reload I also get a 401 + basic auth popup.

**Comment by SwikritiT** [comment]
The CI failed again at https://drone.owncloud.com/owncloud/ocis/14883/35/3 `go-generate` and `golangci-lint` has become really annoying lately. Is there nothing we do about it?

**Comment by C0rby** [comment]
> @C0rby When I open the settings app via the user menu (top right) and do a page reload I also get a 401 + basic auth popup.

Ah interesting. That means another path is missing. I'll add it.

**Comment by C0rby** [comment]
> @C0rby this brings up another issue: can we have a wildcard allowance for certain file types, like .js, .css, .html? Because any external app that gets added to the config.json would fail with a 401 at the moment, right?

I wouldn't really implement a wildcard for security reasons but yeah we need to refactor the proxy quite a bit to make this easier.

**Comment by kulmann** [comment]
> > @C0rby this brings up another issue: can we have a wildcard allowance for certain file types, like .js, .css, .html? Because any external app that gets added to the config.json would fail with a 401 at the moment, right?
> 
> I wouldn't really implement a wildcard for security reasons but yeah we need to refactor the proxy quite a bit to make this easier.

Then we probably need to be able to register unprotected routes...

**Comment by C0rby** [comment]
> Then we probably need to be able to register unprotected routes

Yeah, that is the plan. To use the proxy routes and mark certain routes as "unprotected".

**Comment by kulmann** [comment]
@SwikritiT @C0rby nice, settings ui tests are passing now. All the other pipelines were green in the run before. Should be good now. Thanks for your efforts!

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
