### PR TITLE
update reva to v1.6.1-0.20210218130854-a954e7242e7a

### PR DESCRIPTION
**Pull request by C0rby**
Update reva. This includes:

* quota querying and tree accounting [cs3org/reva#1405](https://github.com/cs3org/reva/pull/1405)

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/3579/73/7
ebUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:59 failed - that is an annoying intermittent failure, issue #1492 - I restarted CI.

**Comment by C0rby** [comment]
The windows binary build fails because we are using `syscall.Statfs_t{}` in some places which is not available in windows.

https://github.com/cs3org/reva/blob/a954e7242e7a7068e6951601d3826d93b0e043c1/pkg/storage/utils/localfs/localfs.go#L525
https://github.com/cs3org/reva/blob/a954e7242e7a7068e6951601d3826d93b0e043c1/pkg/storage/fs/ocis/ocis.go#L222

This needs to be fixed in reva. Something for next week...

**Comment by C0rby** [comment]
For windows we could to it like this: https://stackoverflow.com/a/60724929

**Review by wkloucek — APPROVED** [review]
LGTM

**Pull request merged**
