### PR TITLE
[full-ci] Fix nats authentication & Improvements

### PR DESCRIPTION
**Pull request by kobergj**
- Fixes authentication for nats
- Fixes store TTL
- Removes statcache
- Sets natsjskv registry to inmemory instead file persistence

### CODE REVIEW

**Comment by kobergj** [comment]
@dragonchaser I needed to introduce some extra envvars to make authentication work. I followed the old guidelines for envvars

Q1: Should I follow a new scheme already? E.g. not introducing ennvars like `GATEWAY_PROVIDER_CACHE_AUTH_PASSWORD` but only using the global ones instead?

Q2: Where can I find this list of new envvars in `5.0` release you made? I'll need to add the ones from this PR.

**Comment by dragonchaser** [comment]
> @dragonchaser I needed to introduce some extra envvars to make authentication work. I followed the old guidelines for envvars
> 
> Q1: Should I follow a new scheme already? E.g. not introducing ennvars like `GATEWAY_PROVIDER_CACHE_AUTH_PASSWORD` but only using the global ones instead?

makes sense imho

> 
> Q2: Where can I find this list of new envvars in `5.0` release you made? I'll need to add the ones from this PR.

will send it to you on rc

**Review by 2403905 — APPROVED** [review]
Looks good for me

**Comment by kobergj** [comment]
Only rebased to master. No further code changes

**Pull request merged**
