### PR TITLE
[docs-only] add log rotation to deploy examples

### PR DESCRIPTION
**Pull request by wkloucek**
## Description

This PR adds log rotation for Docker logs to our deployment examples. This is helpful to prevent endless log accumulation on our (not yet available) test servers and failures which are caused by this.

## Related Issue

- Log accumulation already happend on ocis.owncloud.works and caused various errors when the disk was full.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by C0rby** [comment]
Do we really want to you the json driver instead of the local driver?
I'm not experienced so I don't know what's the best practice here but if I understood correctly this will wrap our json messages in another json object. Don't know why that would be useful.

**Comment by wkloucek** [comment]
> Do we really want to you the json driver instead of the local driver?
> I'm not experienced so I don't know what's the best practice here but if I understood correctly this will wrap our json messages in another json object. Don't know why that would be useful.

Ok, switched to local driver. This has already log rotation enabled as default, so no need anymore fore the annoying yaml pointers to deduplicate config.

I wonder if we should leave it up to the docker host to configure the default logging driver properly (with log rotation)? But I worry that some people will not do this and having this configuration doesn't any harm. So I feel that we should add this.

**Review by C0rby — APPROVED** [review]
Cool :+1:

**Comment by wkloucek** [comment]
@C0rby just ran into this: https://github.com/docker/compose/issues/7420. Should be fixed with docker-compose 1.27.0 and up.

**Pull request merged**
