### PR TITLE
[full-ci] [tests-only] Remove core bug demonstration scenarios

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
Removal of bug demonstration scenarios of core.

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/5337

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by SwikritiT — APPROVED** [review]
LGTM

**Comment by grgprarup** [comment]
- [ ] Forward port to master

**Comment by amrita-shrestha** [comment]
@grgprarup please don't remove @skipOnOcis for now because it will be hard for me to work on PR if @skipOnOcis

**Review by amrita-shrestha — APPROVED** [review]
lgtm

**Pull request merged**
