### PR TITLE
[tests-only] [full-ci] ApiTest. after each test users-manager delete their project space

### PR DESCRIPTION
**Pull request by ScharfViktor**
Part2 of issue https://github.com/owncloud/ocis/issues/4390

- method works well and clears project spaces

But there is one little problem when we run tests without creating project space and method https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/bootstrap/SpacesContext.php#L897-L904 tries to remember no spaces:

Screenshot 2022-08-23 at 13 55 29

### CODE REVIEW

**Comment by ScharfViktor** [comment]
CI is green but stucks due docker arm https://drone.owncloud.com/owncloud/ocis/14823

**Comment by phil-davis** [comment]
I'm not sure why we need the `assertArrayHasKey` check in `rememberTheAvailableSpaces()` - if `$drives` is empty, then that means there are none that matched whatever was the last query/filter. The same with `Assert::assertNotEmpty($spaces, "No spaces have been found");` - it might be normal that there are no spaces found. It needs some refactoring to maybe know when it should expect to find something, and when it is being called in a situation where there might be nothing.

**Comment by ScharfViktor** [comment]
> I'm not sure why we need the `assertArrayHasKey` check in `rememberTheAvailableSpaces()` - if `$drives` is empty, then that means there are none that matched whatever was the last query/filter. The same with `Assert::assertNotEmpty($spaces, "No spaces have been found");` - it might be normal that there are no spaces found. It needs some refactoring to maybe know when it should expect to find something, and when it is being called in a situation where there might be nothing.

I deleted asserts in rememberSpaces method. now pr's ready for review.

**Review by phil-davis — APPROVED** [review]
LGTM

**Pull request merged**
