### PR TITLE
[full-ci] chore: bump web to v11.0.1

### PR DESCRIPTION
**Pull request by kulmann**
Bump web to v11.0.1

@kobergj this also includes that thumbnails for .ggp files are requested.

### CODE REVIEW

**Review by micbar — APPROVED** [review]
LGTM 🚀

**Comment by kulmann** [comment]
looks like the federated instance that web needs for an OCM e2e test is not set up in the ocis ci, yet.

**Comment by ScharfViktor** [comment]
e2e is green now but we have problem with wopi validator and api-collaboration suite https://drone.owncloud.com/owncloud/ocis/40673/44/13

response: `{"BaseFileName":"textfile0.txt","DisablePrint":false,"OwnerId":"36653730333962352d663464642d343861322d623064612d3132396661376462363532354068747470733a2f2f6f6369732d7365727665723a39323030","PostMessageOrigin":"https://localhost:9200","Size":11,"UserCanWrite":true,"UserCanNotWriteRelative":false,"UserId":"36653730333962352d663464642d343861322d623064612d3132396661376462363532354068747470733a2f2f6f6369732d7365727665723a39323030","UserFriendlyName":"Alice Hansen","EnableOwnerTermination":true,"SupportsLocks":true,"SupportsRename":true,"UserCanRename":true,"BreadcrumbDocName":"textfile0.txt"}`

test check this items in the response body but some like SupportsCobalt, SupportsContainers ... are missing: 
```
"required": [
          "BaseFileName",
          "OwnerId",
          "Size",
          "UserId",
          "Version",
          "SupportsCobalt",
          "SupportsContainers",
          "SupportsDeleteFile",
          "SupportsEcosystem",
          "SupportsExtendedLockLength",
          "SupportsFolders",
          "SupportsGetLock",
          "SupportsLocks",
          "SupportsRename",
          "SupportsUpdate",
          "SupportsUserInfo",
          "UserFriendlyName",
          "ReadOnly",
          "RestrictedWebViewOnly",
          "UserCanAttend",
          "UserCanNotWriteRelative",
          "UserCanPresent",
          "UserCanRename",
          "UserCanWrite",
          "AllowAdditionalMicrosoftServices",
          "AllowExternalMarketplace",
          "DisablePrint",
          "DisableTranslation",
          "BreadcrumbDocName"
```

**Comment by ScharfViktor** [comment]
> @ScharfViktor Can you rebase?
I did. let see what says CI now

**Pull request merged**
