### PR TITLE
[tests-only] [full-ci] Update web id 20210712

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- updated line numbers in expected failures file (web UI on ocis storage)
- replaced closed issues with open ones
- Follow up after https://github.com/owncloud/web/pull/5463/files

## Motivation and Context
Closed issues should not be included in the expected failures list.

## How Has This Been Tested?

- 🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5979/53/6

@kiranparajuli589 line number change needed in expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md

**Comment by kiranparajuli589** [comment]
> https://drone.owncloud.com/owncloud/ocis/5979/53/6
> 
> @kiranparajuli589 line number change needed in expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md

The line numbers have been updated, CI should now pass.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
I added an extra commit to update the web commit id again, so that the test code fix from web PR https://github.com/owncloud/web/pull/5511 is included. We need that for the reva update PR.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5982/59/2
docker-amd64: Error response from daemon: No such image: owncloudci/nodejs:14

Painful - have to restart CI and hope for better next time.

**Comment by kiranparajuli589** [comment]
ci crashed while generating nodejs https://drone.owncloud.com/owncloud/ocis/5983/12/2

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5984/59/5
Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

All the tests have passed again. But another stupid network error in docker-amd64.

@micbar can you force-merge this? Otherwise it is another hour of rerunning CI, and getting another random network error in these final docker-* pipelines.

**Pull request merged**
