### PR TITLE
[do-not-merge-now][full-ci] [tests-only] Balance drone pipelines time

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
This PR separates the shares-related test from `apiSpaces` suite to `apiSpacesSuites`.

## Related Issue

- Part of https://github.com/owncloud/QA/issues/765#issuecomment-1247646666

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by grgprarup** [comment]
This PR needs the bumping of the `latest web master` on OCIS. So till then, it's blocked.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/15801/76/13
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIUpload/upload.feature:94
webUIUpload/upload.feature:111
```

https://drone.owncloud.com/owncloud/ocis/15801/80/9
The failing scenarios are failing on an upload step.

I guess something changed recently in `owncloud/web` related to uploading, and so new web code needs to be pulled into oCIS at the same time as a web commit id update is done.

**Comment by grgprarup** [comment]
The changes related to the local API tests of oCIS are moved to PR https://github.com/owncloud/ocis/pull/4707.

**Comment by SwikritiT** [comment]
@grgprarup maybe we can close this PR. When the web id gets bumped in ocis then the CI will fail with unexpected passes or changed line numbers. Either we or some dev can look into it when that happens or take this PR as a guide. I don't see the need of keeping it open. HOwever, you can decide. I'm moving it to the backlog for now

**Review by kulmann — COMMENTED** [review]
web commit id bump (to a recent commit id) and your changes regarding expected failures are now part of https://github.com/owncloud/ocis/pull/4779 and can be removed here. should also unblock this PR if I'm not mistaken.

**Comment by kulmann** [comment]
Ah, the pipeline changes have been done in another PR. Then this PR is not needed anymore. Thanks for keeping it open, was indeed helpful for the web commit id bump in https://github.com/owncloud/ocis/pull/4779 👍

**Pull request closed without merging**
