### PR TITLE
Update web to 2.0.0

### PR DESCRIPTION
**Pull request by kulmann**
## Description
Update ownCloud Web to v2.0.0

## Related Issue

- https://github.com/owncloud/ocis/issues/1654

## Motivation and Context
Release

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by LukasHirt — APPROVED** [review]
Is generating the assets manually still required since #1580 got merged?

**Comment by LukasHirt** [comment]
Btw, requires #1597

**Comment by kulmann** [comment]
> Is generating the assets manually still required since #1580 got merged?

For trying it locally, yes. For having it up to date in the repo after merge, no AFAIK.

**Comment by wkloucek** [comment]
> > Is generating the assets manually still required since #1580 got merged?
> 
> For trying it locally, yes. For having it up to date in the repo after merge, no AFAIK.
Actually the generated files still should be commited as long as we don't have this as an automatic step after a merge to master. But we are building them automatically in CI too, in order to ensure that our binaries represent the code (if somebody forgot to commit the generated files)

**Comment by LukasHirt** [comment]
> Actually the generated files still should be commited as long as we don't have this as an automatic step after a merge to master. But we are building them automatically in CI too, in order to ensure that our binaries represent the code (if somebody forgot to commit the generated files)

Ah, okay. I thought the process now will be:

- if working locally pull latest changes and generate
- if pushing, do not commit the generated files and let CI take care of that

**Comment by wkloucek** [comment]
> > Actually the generated files still should be commited as long as we don't have this as an automatic step after a merge to master. But we are building them automatically in CI too, in order to ensure that our binaries represent the code (if somebody forgot to commit the generated files)
> 
> Ah, okay. I thought the process now will be:
> 
> * if working locally pull latest changes and generate
> * if pushing, do not commit the generated files and let CI take care of that

I would not like this since always generating them before developing is time consuming. Also the need do be used from external extensions and therefore be present in the git repository. It was just the first step do generate them also in CI. Auto commiting them after merge to master needs some more changes and time.

**Pull request merged**
