### PR TITLE
add token to LinkAccessedEvent

### PR DESCRIPTION
**Pull request by dragonchaser**
We added the link token to the LinkAccessedEvent

refs #3753

### CODE REVIEW

**Comment by dragonchaser** [comment]
**NOTE:** requires https://github.com/cs3org/reva/pull/3993

**Comment by kobergj** [comment]
Merging this will allow the sysadmin to access all files that have a public link. In my opinion this is a major security issue. We should not log the token at all, even if it means we don't know which link was being accessed. 

@butonic @micbar @tbsbdr

**Review by kobergj — CHANGES_REQUESTED** [review]
Good looks good. Just blocking until above comment is resolved

**Comment by butonic** [comment]
> Merging this will allow the sysadmin to access all files that have a public link. In my opinion this is a major security issue. We should not log the token at all, even if it means we don't know which link was being accessed.

The public link token is part of the url and will already show up in access logs anyway. So, I understand your concern, but I don't see a decrease in security. If users don't want their public links to be accessed ... set a password.

**Comment by kobergj** [comment]
IMO we should not log the token at all. And already having a security issue doesn't mean we should open another one.

I also don't see the point in having the token logged. What is the admin supposed to do with that information? They would need to know whose link it is to be able to do any action.

**Comment by dragonchaser** [comment]
> IMO we should not log the token at all. And already having a security issue doesn't mean we should open another one.
> 
> I also don't see the point in having the token logged. What is the admin supposed to do with that information? They would need to know whose link it is to be able to do any action.

Seeing tokens in the access log is not a security issue per se, works as designed....

**Comment by kobergj** [comment]
> Seeing tokens in the access log is not a security issue per se, works as designed....

Not so sure about that, smells like bug to me.

Anyways the access log is not part of this PR. So we should leave that out of discussion. Logging the access tokens in one place doesn't make it better to log them in another.

**Comment by dragonchaser** [comment]
I think this is a decision pm should make... @kobergj I see and understand your concerns, but this is more of a general decision how this should be handled. 

/cc @tbsbdr

**Comment by kobergj** [comment]
I wouldn't day this is a `general` decision. Opening backdoors should always be a case to case decision.

But I agree. We need a product decision. 

/cc @micbar

**Comment by micbar** [comment]
From my pov, this is not critical.

We need to remember that "Public Links" are designed to be "public".

**Review by kobergj — APPROVED** [review]

**Comment by dragonchaser** [comment]
@micbar so shall we merge this now?

**Comment by micbar** [comment]
Yes.

**Pull request merged**
