### PR TITLE
[tests-only] bump phoenix commit id for tests and add new suites

### PR DESCRIPTION
**Pull request by individual-it**
update the phoenix commit id for the tests and add new suites that have been added in https://github.com/owncloud/phoenix/commit/4b7cd01a3dc2065fff369f896ed87cb135ed3469 (use the same list that is used in phoenix repo)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by dpakach** [comment]
Seems like it got merged as I was reviewing, Since most pipelines have only one suite I would suggest changing it to 
```
        'webUIFavorites':  'webUIFavorites',
        'webUIFiles':  'webUIFiles'
```
instead of 
```
       'webUIFavorites': [
            'webUIFavorites',
        ],
        'webUIFiles': [
            'webUIFiles',
        ],
```
But maybe we can do that on another PR.

**Comment by individual-it** [comment]
@dpakach I tried that, but that does not work in here, only in phoenix.

**Comment by phil-davis** [comment]
The Phoenix starlark code probably got written to check if the item is just a string, or a list, and handle both appropriately.

**Comment by dpakach** [comment]
https://github.com/owncloud/phoenix/blob/0760efba10f388d5b3ed734a18bafb0d2034d038/.drone.star#L1526
Just need to check the type

**Pull request merged**
