### PR TITLE
[tests-only][full-ci]Use `traits` in correct way for `JsonAssertion`

### PR DESCRIPTION
**Pull request by SagarGi**
### Description
This PR refactors the use of `JsonAssertion traits` in correct way for the tests.

### Related Issues 
Fixes https://github.com/owncloud/ocis/issues/6404

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-10</strong>](https://drone.owncloud.com/owncloud/ocis/22871/66/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-3</strong>](https://drone.owncloud.com/owncloud/ocis/22871/59/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiArchiver-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/22871/49/1) failed. Further test are cancelled...

**Review by SwikritiT — APPROVED** [review]
LGTM

**Pull request merged**
