### PR TITLE
add secureview flag when listing apps via http

### PR DESCRIPTION
**Pull request by butonic**
To allow clients to see which application supports secure view we add a flag to the http response when the app name matches a configured secure view app. The app can be configured by setting `FRONTEND_APP_HANDLER_SECURE_VIEW_APP` to the name of the app registered as a CS3 app provider.

Part of https://github.com/owncloud/ocis/issues/9272

Only effective when https://github.com/cs3org/reva/pull/4703 got merged and reva bumped

### CODE REVIEW

**Review by AlexAndBear — COMMENTED** [review]
Hm, don't we need a default value here for Collabora, I don't want force people to configure it manually. Things should work out of the box.

**Review by AlexAndBear — DISMISSED** [review]

**Comment by butonic** [comment]
True. AFAIR @tbsbdr @micbar and @dragotin wanted to default to collabora as the online office solution. We could change the default here and in the collaboration service in a subsequent PR though.

**Review by AlexAndBear — APPROVED** [review]

**Comment by AlexAndBear** [comment]
Can you wait for cs3 and bump in this pr?

**Comment by butonic** [comment]
sure

**Comment by micbar** [comment]
307 changed files?

**Comment by butonic** [comment]
go back to your holiday! ;-) the reva bump pulled in the deps for the posix driver as well.

**Comment by AlexAndBear** [comment]
unfortunately secure_view flag is false in apps/list API 
image

**Comment by micbar** [comment]
Default value is wrong, should be Collabora not Collabora Online.

**Pull request merged**
