### PR TITLE
[docs-only] fix: remove colons after an env var, to form proper path names in descriptions

### PR DESCRIPTION
**Pull request by jnweiger**
Quite consistently, description strings and documentation uses the syntax `$OCIS_CONFIG_DIR:/filename.yaml`
to describe how paths in the system are influenced by environment variables. 

While fully understandable in meaning, this is nevertheless not proper shell syntax.
I'd suggest to remove the colon (:) after the environment variable name.

### CODE REVIEW

**Comment by mmattel** [comment]
@jnweiger have you grep'ed thru the services which would catch all possible occurrences in readme's?

**Comment by jnweiger** [comment]
> @jnweiger have you grep'ed thru the services folder which would catch all possible occurrences in readme's?

Thanks for the hint. Indeed, there is more! PR expanded.

**Comment by mmattel** [comment]
@jnweiger pls revert the changes made in:
* `env-vars.yaml`:
this file is manually maintained and has its own process for this
* `4.0.0-5.0.0-added.adoc`, `4.0.0-5.0.0-added.md`:
these files are related to stable 5, this here is 6

**Review by mmattel — APPROVED** [review]
LGTM 👍

**Pull request merged**
