### PR TITLE
[WIP] Add a SharesStorageProvider and an oc10 sql share manager

### PR DESCRIPTION
**Pull request by aduffeck**
This is WIP to access oc10 shares from ocis.

Requires https://github.com/cs3org/reva/pull/2023

\cc @butonic

### CODE REVIEW

**Comment by aduffeck** [comment]
@butonic please note (as discussed) that the database information is currently hardcoded in `storage/pkg/command/storageshares.go`

**Comment by aduffeck** [comment]
Just for reference, the according reva draft pr can be found at https://github.com/cs3org/reva/pull/1846

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-owncloud-storage-8</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-owncloud-storage-3</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiBugDemonstration-ocis</strong> failed. The build is cancelled...</summary>

**Comment by wkloucek** [comment]
@aduffeck can you make this PR ready? :-)

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Web-Tests-ocis-ocis-storage-2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>settingsUITests</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-7</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Web-Tests-ocis-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-3</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-10</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-10</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-9</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-6</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
please update or close.

**Pull request closed without merging**
