### PR TITLE
Update ocis-reva to v0.2.2 pre-release

### PR DESCRIPTION
**Pull request by PVince81**
There are some CI failures that require this update earlier.

### CODE REVIEW

**Comment by micbar** [comment]
Seems tricky. UI acceptance tests are now failing.

**Comment by PVince81** [comment]
Strange, API tests all passed but Phoenix UI tests failed with:
```
Error: Could not create the file "test_sort/z.txt" for user "user1". Status:500 Internal Server Error
```

I've restarted it just in case.

**Comment by PVince81** [comment]
now failing differently, without final results, with a weird sort of infinite loop with timeout:
image

@individual-it any idea ?

**Comment by PVince81** [comment]
seems it has been failing weirdly already since more than a day on several things

the fix might be https://github.com/owncloud/ocis/pull/254, will rebase

**Comment by PVince81** [comment]
combined PR here: https://github.com/owncloud/ocis/pull/261

**Comment by PVince81** [comment]
Assigning @dpakach to look into the Phoenix issues (see https://github.com/owncloud/ocis/pull/261#issuecomment-626525525)

**Comment by PVince81** [comment]
ref https://github.com/owncloud/ocis-reva/issues/188 which might be a regression when creating/uploading files, maybe because of TUS. To be looked into in the next sprint.

**Comment by michaelstingl** [comment]
I can confirm, this includes the correct capabilities, and Desktop 2.7 and Android 2.15 won't try Chunking V1 or NG:

```
% curl -k -u einstein:relativity 'https://192.168.103.195:9200/ocs/v1.php/cloud/capabilities?format=json' | jq | grep -i -e  chunk -e tus | grep -i -v status  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1353  100  1353    0     0  31465      0 --:--:-- --:--:-- --:--:-- 31465
          "bigfilechunking": false,
          "chunking": "",
          "chunkingParallelUploadDisabled": false
```

**Comment by PVince81** [comment]
PR for updating ocis-reva with the test fixes: https://github.com/owncloud/ocis-reva/pull/192

**Comment by PVince81** [comment]
```
      Timed out while waiting for element <//div[@id="files-list-row-actions-dropdown"]//button[@aria-label="Delete"]> to be present for 20000 milliseconds. - expected "visible" but got: "not found" (20004ms)
          at Page.performFileAction (/srv/app/phoenix/tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js:39:10)
          at Page._callee2$ (/srv/app/phoenix/tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js:64:12)
          at new Promise (<anonymous>)
          at Page._delete [as delete] (/srv/app/phoenix/tests/acceptance/pageObjects/FilesPageElement/fileActionsMenu.js:63:11)
          at Proxy._callee3$ (/srv/app/phoenix/tests/acceptance/pageObjects/FilesPageElement/filesList.js:51:13)
    Then the error message with header 'Error while deleting "simple-folder"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
    And folder "simple-folder" should not be listed on the webUI
    - skipped
    And as "user1" file "lorem.txt" should not exist
    - skipped
    And as "user1" folder "simple-folder" should not exist
    - skipped
```

restarting...

**Comment by PVince81** [comment]
wait, I'm looking at the wrong thing

**Pull request closed without merging**
