### PR TITLE
Unify config parsing

### PR DESCRIPTION
**Pull request by refs**
fixing #671 
fixing #672 

	- responsibility for config parsing should be on the subcommand
	- if there is a config file in the environment location, env var should take precedence
	- general rule of thumb: the more explicit the config file is that would be picked up. Order from less to more explicit:
	    - config location (/etc/ocis)
	    - environment variable
	    - cli flag

It should work both in the standalone `proxy` command and embedded in the `ocis` command (as a subcommand). Here are some examples and expected behaviors:

## As a standalone `proxy` command (cd `proxy`):
precondition: create a `proxy.json` file on `/etc/ocis`. The easiest way is to move the one on `/proxy`: `mv config/proxy-example-migration.json /etc/ocis/proxy.json`

|                                                                                                                                                                                                                                            | path | env | cli | loaded |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|-----|-----|--------|
| go run cmd/proxy/main.go --log-level=debug server                                                                                                                                                                                          | ✅    |     |     | path   |
| PROXY_CONFIG_FILE=config/proxy-example-migration.json go run cmd/proxy/main.go --log-level=debug server                                                                                                                           | ✅    | ✅   |     | env    |
| PROXY_CONFIG_FILE=config/proxy-example-migration.json go run cmd/proxy/main.go --log-level=debug server --config-file config/proxy-example-migration.json-this-file-doesnt-exist-but-will-be-picked-up-as-it-is-the-more-explicit | ✅    | ✅   | ✅   | cli    |

## As an embedded subcommand on `ocis` `proxy` command (cd `proxy`):

|                                                                                                                                                                                                                                          | path | env | cli | parsed |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|-----|-----|--------|
| go run cmd/ocis/main.go --log-level=debug proxy                                                                                                                                                                                          | ✅    |     |     | path   |
| PROXY_CONFIG_FILE=../proxy/config/proxy-example-migration.json go run cmd/ocis/main.go --log-level=debug proxy                                                                                                                           | ✅    | ✅   |     | env    |
| PROXY_CONFIG_FILE=../proxy/config/proxy-example-migration.json go run cmd/ocis/main.go --log-level=debug proxy --config-file config/proxy-example-migration.json-this-file-doesnt-exist-but-will-be-picked-up-as-it-is-the-more-explicit | ✅    | ✅   | ✅   | cli    |


## Other things this PR address

The ocis root command was never parsing any config whatsoever. This PR allows for configuring high level settings for the root command in the same fashion as its extensions, with the only difference being these global options cascade down to ocis extensions it embeds.

A clear example of this is the following scenario:

1. create a config file for `ocis` on `/etc/ocis/ocis.json` with the following contents:

![ocis-11d6a46146](https://user-images.githubusercontent.com/6905948/98235084-9fe7f600-1f61-11eb-93fa-a4c0f172610d.png)

2. run ocis server

By this point, you should see a log wall similar to this:

![grafik](https://user-images.githubusercontent.com/6905948/98229974-e423c800-1f5a-11eb-9de9-429a5d61a5a1.png)
_(please note that this is but a portion of the entire logs...)_

The point being all extensions configuring the same logging configuration. Now, while cascading works as expected, extensions can still override them using their own config files / environment variables. Let's see an example of it.

1. with the existing ocis json config file in the correct location
2. create a `proxy.json` config file, also on `/etc/ocis` with the following contents:

![proxy-3134355ba2](https://user-images.githubusercontent.com/6905948/98234913-6c0cd080-1f61-11eb-9f71-767cfa598770.png)


3. run ocis server

Now the log wall should look familiar to the previous step, with the only difference being the proxy service loading its log values from its own configuration file on `/etc/ocis/proxy.json`:

![carbon(2)](https://user-images.githubusercontent.com/6905948/98235924-cd816f00-1f62-11eb-9788-e0b8b2f94c7b.png)

Please note that the premise of this PR on keeping parsing order stays present. In fact with both config files existing from previous steps, running the following command

```bash
PROXY_LOG_LEVEL=info go run cmd/ocis/main.go server
```

will effectively override the value on `/etc/ocis/proxy.json` regarding the log level, the ones that are not overridden remain as parsed from the config file.

### CODE REVIEW

**Comment by kulmann** [comment]
> * responsibility for config parsing should be on the subcommand
> * if there is a config file in the environment location, env var should take precedence
> * general rule of thumb: the more explicit the config file is that would be picked up. Order from less to more explicit:
>   
>   * config location (/etc/ocis)
>   * environment variable
>   * cli flag

full ack

**Review by felixboehm — APPROVED** [review]
Nice, explains it!

**Comment by phil-davis** [comment]
Should this have a changelog, or not?

**Comment by refs** [comment]
> Should this have a changelog, or not?

@phil-davis yes absolutely. And before merging it I would like to update all the other extensions aligned to these changes. Please do not merge yet :)

**Comment by phil-davis** [comment]
@refs good to know - I saw the green approval tick from @felixboehm and I'm glad I asked.

**Review by IljaN — APPROVED** [review]

**Pull request merged**
