### PR TITLE
[Tests-Only]Bumped commit ids in ocis

### PR DESCRIPTION
**Pull request by Talank**
Bumped web commit id in ocis

## Issues
- Part of https://github.com/owncloud/QA/issues/662
- fixes https://github.com/owncloud/QA/issues/665

### CODE REVIEW

**Comment by Talank** [comment]
Created a new issue to complete the bump. https://github.com/owncloud/QA/issues/665 it is much complicated than regular bumping.

**Review by HariBhandari07 — COMMENTED** [review]
LGTM (if CI passes)

**Review by phil-davis — APPROVED** [review]
Looks OK if CI passes.

**Comment by individual-it** [comment]
I expect this to fail because of https://github.com/owncloud/web/pull/4627 not being in ocis yet

**Review by individual-it — COMMENTED** [review]
blocked by waiting for an web update in ocis

**Pull request merged**
