### PR TITLE
[full-ci] Thumbnails for GGP files

### PR DESCRIPTION
**Pull request by kobergj**
Fixes https://github.com/owncloud/enterprise/issues/6907

Also bumps reva

### CODE REVIEW

**Comment by kulmann** [comment]
@kobergj do you have an example file available?

**Comment by kobergj** [comment]
Unfortunately not. I requested one though. PR on hold.

**Comment by kulmann** [comment]
> Unfortunately not. I requested one though. PR on hold.

Cool. We need a PR to web similar to this: https://github.com/owncloud/web/pull/11583/files
The list of previewable mimetypes is hardcoded in web (because there is no good server mechanism and we can't request thumbnails for each and every file)

**Comment by kulmann** [comment]
@kobergj do you plan to get this in for ocis 7.0? I made a PR in web so that .ggp previews get requested (result in a 404 at the moment). See https://github.com/owncloud/web/pull/11829 - I'd revert it if it won't be part of ocis 7.0.

**Comment by kobergj** [comment]
@kulmann Thanks! Would be cool if it could make 7.0. I also have an example file now, so we can test.

**Comment by kulmann** [comment]
> @rhafer I added the file
> 
> @kulmann can we merge the web PR? Then it is easier for me to test (and fix) it.

@kobergj web PR was merged and is included in web `11.0.1`, which was bumped in ocis yesterday with https://github.com/owncloud/ocis/pull/10467 - you should be able to test with this PR after a rebase.

**Review by micbar — APPROVED** [review]

**Pull request merged**
