### PR TITLE
fix the docker-compose wopi

### PR DESCRIPTION
**Pull request by 2403905**
## Related Issue

- Fixes [https://github.com/owncloud/ocis/issues/8474](https://github.com/owncloud/ocis/issues/8474)

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by micbar — CHANGES_REQUESTED** [review]
I would rather try to find a solution wihout the curl workaround in the entrypoint override.

This example is used by community for production deployments.

Can we use the compose depends_on logic here?

**Comment by 2403905** [comment]
@micbar 
The `depends_on` will work correctly if we use it with the  condition `service_healthy`  and in this case we have to perform the healthcheck somehow in a collabora and onlyoffice.
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

`services:
  ocis-appprovider-collabora:
    image: ocis
    depends_on:
      collabora:
        condition: service_healthy
        
  collabora:
    image: collabora
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
      timeout: 3s
      retries: 30`

**Comment by 2403905** [comment]
So in both cases, we must add a curl in the app provider or in the office client container. I would prefer not to change the office client containers.

**Comment by wkloucek** [comment]
Is this a duplicate of https://github.com/owncloud/ocis/pull/8144 ?

Instead of working around it, we should properly fix it: https://github.com/owncloud/ocis/issues/3832#issuecomment-1953567913

**Comment by 2403905** [comment]
Looks like it is a duplicate of https://github.com/owncloud/ocis/pull/8144

**Review by butonic — APPROVED** [review]

**Comment by butonic** [comment]
how do we move forward?

**Comment by wkloucek** [comment]
@kulmann I already reviewed it:

> Instead of working around it, we should properly fix it: [#3832 (comment)](https://github.com/owncloud/ocis/issues/3832#issuecomment-1953567913)

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
Tested :heavy_check_mark: and collabora shows up in the file action menu right away and it can be opened.
But it cries about no disk space .... but I guess this is unrelated
image

**Comment by 2403905** [comment]
It works well for me!
Screenshot 2024-04-25 at 18 14 01

**Comment by DeepDiver1975** [comment]
tested again after rebase - collabora is shown in the file action menu right away.
but i still get the disk space issue - but this is a different ropic.

let's merge this ...

**Comment by micbar** [comment]
No!
I was against merging that.

You put user:0 on the container which is a total no go.

Please revert.

**Comment by DeepDiver1975** [comment]
but then you need to revert onlyoffice as well and the whole example is useless.

**Comment by wkloucek** [comment]
Which brings us back to https://github.com/owncloud/ocis/issues/3832

But there is also another workaround:

```
healthcheck:
  test:
    - CMD
    - /bin/sh
    - -c
    - curl --silent -- fail http://ocis:9200/app/list | grep '"name":"Collabora"'
```

It similar to the workaround in the oCIS Helm Chart: https://github.com/owncloud/ocis-charts/blob/ca7f57a448adfd2aed3c28e1b0c0146d226547ae/charts/ocis/templates/appprovider/deployment.yaml#L88-L93

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/ocis/pull/8984

**Pull request merged**
