### PR TITLE
Nats tls

### PR DESCRIPTION
**Pull request by C0rby**
## Description

Enable TLS encryption for the connection between the nats server and clients.
The server can either use provided certificates, or if the certificate file doesn't exist, a self-signed certificate will be generated.

## Motivation and Context

In a production deployment no connection between servers should be unencrypted.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Code changes

## Todo before ready:
- [x] remove reva replace (requires this https://github.com/cs3org/reva/pull/3334)
- [x] add changelog

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-6</strong>](https://drone.owncloud.com/owncloud/ocis/16015/52/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>cs3ApiTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/16015/41/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-4</strong>](https://drone.owncloud.com/owncloud/ocis/16015/50/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiGraph-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/16015/46/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiAccountsHashDifficulty-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/16015/42/1) failed. Further test are cancelled...

**Review by butonic — APPROVED** [review]

**Pull request merged**
