### PR TITLE
[full-ci] [tests-only] Remove depthinfinity related steps from occ context

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
This PR removes the following steps and their implementations:
- `When the administrator has set depth_infinity_allowed to :depth_infinity_allowed`

- [ ] Forward port to master https://github.com/owncloud/ocis/pull/5679

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/5337

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by amrita-shrestha — APPROVED** [review]
lgtm

**Review by saw-jan — COMMENTED** [review]
:+1:

**Review by individual-it — COMMENTED** [review]
The tests still fail, does that mean ocis does not support depth=infinity?
If that is the case and that behavior is intended, we should delete the tests alltogether

**Comment by micbar** [comment]
ocis should support depth:infinity

**Review by individual-it — APPROVED** [review]

**Comment by grgprarup** [comment]
> 

Ocis supports depth infinity and the default is enabled, but it cannot be disabled or change the configuration. So scenarios for disabled cases are added in expected failures.

**Comment by grgprarup** [comment]
> The tests still fail, does that mean ocis does not support depth=infinity? If that is the case and that behavior is intended, we should delete the tests alltogether

@individual-it Ocis supports depth infinity and the default is enabled, but it cannot be disabled or change the configuration. So scenarios for disabled cases are added in expected failures.

@micbar Can we disable the depth:infinity? or depth:infinity is always enabled in oCIS? If the latter is the case, we can remove scenarios for the disabled case.

**Comment by micbar** [comment]
@grgprarup 
We should add that setting to the ocdav service. It will be an environment variable. @individual-it you pointed out that that could be difficult to test 😄

**Comment by individual-it** [comment]
we could have an extra pipeline that only runs these tests and sets the correct env. variable

**Pull request merged**
