### PR TITLE
Autoincrement index

### PR DESCRIPTION
**Pull request by kulmann**
Brings the new index implementation and generates UIDs and GIDs based on an autoincrement index.

Fixing issues:
- closes https://github.com/owncloud/ocis-accounts/issues/62
- closes https://github.com/owncloud/ocis-accounts/issues/77
- closes https://github.com/owncloud/ocis-ocs/issues/45
- closes https://github.com/owncloud/ocis-ocs/issues/46
- closes https://github.com/owncloud/ocis-ocs/issues/51
- closes https://github.com/owncloud/ocis-ocs/issues/55
- closes https://github.com/owncloud/ocis/issues/733

This PR also:
- updates the golang image from `webhippie/golang:1.13` to `webhippie/golang:1.14`

### CODE REVIEW

**Comment by kulmann** [comment]
Somehow the cs3 index integration tests are failing on drone (can't connect to metadata storage), but succeeding locally.

**Comment by kulmann** [comment]
Most API and webUI tests are failing, because we have an issue in the index regarding the provisioning API. When trying to delete an account via OCS endpoint, this happens:
```
2020-10-15T22:25:42Z ERR could not remove account from index error="github.com.owncloud.ocis.accounts.pkg.proto.v0.Account with DisplayName= not found" accountId=user1 id=user1 service=accounts
```

**Comment by kulmann** [comment]
Still nearly all API and webUI test pipelines failing. The regexes for listing users are not splitting on `and` and `or`, so this results in reva trying to find files with query parts still in it, instead of just the account name. E.g.:
```
2020-10-16T08:14:13Z ERR datasvc: file not found error="error: not found: /srv/app/tmp/ocis/storage/users/data/index.cs3/unique.github.com.owncloud.ocis.accounts.pkg.proto.v0.Account.OnPremisesSamAccountName/user1' or mail eq 'user1" pkg=rhttp service=storage traceid=7440e6b0f3b0b438b8910e5a6d8e7dcb
```
Notice that there is `' or mail eq 'user1` in the path of the file that is to be loaded. That is because we match queries from start to end instead of splitting on `and` and `or` first. Fixing regexes next...

**Comment by refs** [comment]
please no force push 🙏

**Comment by kulmann** [comment]
This PR had a successful CI run, except from a known random failure because of a phoenix logout issue in CI, here: https://drone.owncloud.com/owncloud/ocis/888

**Review by refs — APPROVED** [review]

**Pull request merged**
