### PR TITLE
add expose to docker images

### PR DESCRIPTION
**Pull request by wkloucek**
## Description

This PR adds port exposure information to our released docker images. Expose see: https://docs.docker.com/engine/reference/builder/#expose

## Motivation and Context

This adds information only. But for the user it is nice to see which ports of a docker container offer services.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by xoxys** [comment]
As tcp is the default and to keep it (somehow) in sync with https://github.com/owncloud-docker/ should we strip `/tcp`? What do you think?

**Comment by wkloucek** [comment]
> As tcp is the default and to keep it (somehow) in sync with https://github.com/owncloud-docker/ should we strip `/tcp`? What do you think?

I like it more explicitly but if you prefer to remove it I am fine with it too.

**Comment by xoxys** [comment]
No, fine for me 🙂

**Review by xoxys — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/2776/23/7
```
runsh: Total unexpected failed scenarios throughout the test run:
apiProvisioning-v1/disableUser.feature:179
```
"random" test fail! I will restart drone.

**Comment by phil-davis** [comment]
I merged another PR to OCIS. So I rebased here again. Maybe you will win the race this time.

**Pull request merged**
