### PR TITLE
ensure the same data on /ocs/v?.php/config like oC10 [full-ci]

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
together with https://github.com/cs3org/reva/pull/2692/files, we now return the same (weird / wrong) info as oC10:

oCIS /ocs/v2.php/config
```xml
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <version>1.7</version>
    <website>ownCloud</website>
    <host>localhost:9200</host>
    <contact/>
    <ssl>false</ssl>
  </data>
</ocs>
 ```

https://cloud.owncloud.com/ocs/v2.php/config:

```xml
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>200</statuscode>
    <message/>
    <totalitems/>
    <itemsperpage/>
  </meta>
  <data>
    <version>1.7</version>
    <website>ownCloud</website>
    <host>cloud.owncloud.com</host>
    <contact/>
    <ssl>false</ssl>
  </data>
</ocs>
```

## Related Issue

- Related to https://github.com/owncloud/ocis/issues/1338

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-2</strong>](https://drone.owncloud.com/owncloud/ocis/9180/33/1) failed. Further test are cancelled...

**Review by C0rby — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/9619/21/4
```
+ ocis/bin/ocis server

can't connect to nats (stan) server, retrying in 746.090823ms

{"level":"error","error":"remove /srv/app/tmp/ocis/storage/metadata/nodes/root.flock: no such file or directory","time":"2022-02-24T10:17:43Z","caller":"/go/pkg/mod/github.com/cs3org/reva@v1.16.1-0.20220221135950-8cc813ecfc4c/pkg/storage/fs/ocis/ocis.go:48","message":"could not setup tree"}

{"level":"error","service":"storage","error":"http service dataprovider could not be started,: could not setup tree: remove /srv/app/tmp/ocis/storage/metadata/nodes/root.flock: no such file or directory","time":"2022-02-24T10:17:43Z","message":"error starting the http server"}

```
ocis fell over with the "flock" problem. CI needs to be run again - maybe rebase anyway?

**Comment by phil-davis** [comment]
"This branch is 1 commit ahead, 33 commits behind master. "
https://github.com/owncloud/ocis/tree/ocs-config-like-oc10

It would be good to rebase this - there were good fixes in oCIS late yesterday.

**Comment by wkloucek** [comment]
@phil-davis could you please have look, since I get weird errors in https://drone.owncloud.com/owncloud/ocis/9683/26/6, eg.:

```
    Examples:
      | ocs_api_version | ocs_status_code |
      | 1               | 100             |
        │ url has unexpected value 'ocis-server:9200/#/s/UNJVPbPUBTxEUzj'
        │ 
        url doesn't have value 'AN_URL'
        Failed asserting that false is true.
      | 2               | 200             |
        │ url has unexpected value 'ocis-server:9200/#/s/VWEIREAmnDlXdFo'
        │ 
        url doesn't have value 'AN_URL'
        Failed asserting that false is true.
```

**Comment by kulmann** [comment]
> @phil-davis could you please have look, since I get weird errors in https://drone.owncloud.com/owncloud/ocis/9683/26/6, eg.:
> 
> ```
>     Examples:
>       | ocs_api_version | ocs_status_code |
>       | 1               | 100             |
>         │ url has unexpected value 'ocis-server:9200/#/s/UNJVPbPUBTxEUzj'
>         │ 
>         url doesn't have value 'AN_URL'
>         Failed asserting that false is true.
>       | 2               | 200             |
>         │ url has unexpected value 'ocis-server:9200/#/s/VWEIREAmnDlXdFo'
>         │ 
>         url doesn't have value 'AN_URL'
>         Failed asserting that false is true.
> ```

That looks like the respective test mocks data on the (now) wrong config vars, right?

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/FeatureContext.php has:
```
	public function isAPublicLinkUrl(string $url):bool {
		if (OcisHelper::isTestingOnReva()) {
			$urlEnding = \ltrim($url, '/');
		} else {
			if (\substr($url, 0, 4) !== "http") {
				return false;
			}
			$urlEnding = \substr($url, \strlen($this->getBaseUrl() . '/'));
		}

		if (OcisHelper::isTestingOnOcisOrReva()) {
			$matchResult = \preg_match("%^(#/)?s/([a-zA-Z0-9]{15})$%", $urlEnding);
		} else {
			$matchResult = \preg_match("%^(index.php/)?s/([a-zA-Z0-9]{15})$%", $urlEnding);
		}

		// preg_match returns (int) 1 for a match, we want to return a boolean.
		if ($matchResult === 1) {
			$isPublicLinkUrl = true;
		} else {
			$isPublicLinkUrl = false;
		}
		return $isPublicLinkUrl;
	}
```

For oCIS, the value is expected to be a string that starts with `#/s/` or just `s/` (the `#/` is optional, I think there was discussion in the past about that). But the test code does not expect that the public link URL has the host and port part at the front.

I guess that in current master that `ocis-server:9200/` does not appear at the start, but in this PR `ocis-server:9200/` does appear at the start of the URL?

On oC10, public links are just specified as `index.php/s/xxxxxxxxxxxxxxx` - they do not have the "base url" mentioned.

What is the requirement? (and we can easily make the tests expect it)

**Pull request merged**
