### PR TITLE
[full-ci] bump reva to test the spaceid change

### PR DESCRIPTION
**Pull request by butonic**
testing https://github.com/cs3org/reva/pull/4407

cc @kobergj @individual-it

### CODE REVIEW

**Comment by individual-it** [comment]
cannot build it
```
go build -v -tags 'disable_crypt' -ldflags '-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn -s -w -X "github.com/owncloud/ocis/v2/ocis-pkg/version.String=9c00f2c73d" -X "github.com/owncloud/ocis/v2/ocis-pkg/version.Tag=" -X "github.com/owncloud/ocis/v2/ocis-pkg/version.Date=20231214"' -o bin/ocis ./cmd/ocis
github.com/cs3org/reva/v2/pkg/ocm/storage/received
# github.com/cs3org/reva/v2/pkg/ocm/storage/received
../vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/ocm.go:88:9: cannot use BearerAuthenticator{} (value of type BearerAuthenticator) as gowebdav.Authenticator value in return statement: BearerAuthenticator does not implement gowebdav.Authenticator (wrong type for method Authorize)
		have Authorize(*http.Client, *http.Request, string) error
		want Authorize(*http.Request, string, string)
../vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/ocm.go:191:16: undefined: gowebdav.NewAuthClient
../vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/ocm.go:191:49: undefined: gowebdav.NewPreemptiveAuth
../vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/ocm.go:290:22: client.StatWithProps undefined (type *gowebdav.Client has no field or method StatWithProps)
../vendor/github.com/cs3org/reva/v2/pkg/ocm/storage/received/ocm.go:307:22: client.ReadDirWithProps undefined (type *gowebdav.Client has no field or method ReadDirWithProps)
make: *** [../.make/go.mk:102: bin/ocis] Fehler 1

**Comment by butonic** [comment]
@aduffeck ocm got merged in reva ... is there a pr that bumps reva for that?

**Comment by aduffeck** [comment]
@butonic yes, that's: https://github.com/owncloud/ocis/pull/7973 Still fighting CI however

**Review by individual-it — COMMENTED** [review]
:+1: works for me as expected

**Review by individual-it — APPROVED** [review]
works, used in https://github.com/owncloud/ocis-php-sdk/pull/130

**Comment by micbar** [comment]
please rebase

**Comment by butonic** [comment]
https://github.com/cs3org/reva/pull/4407 was merged as part of https://github.com/owncloud/ocis/pull/7989

**Pull request closed without merging**
