### PR TITLE
make ocis on eos great again

### PR DESCRIPTION
**Pull request by butonic**
- makes eos-start work on macos
- adds host.docker.internal to eos mgm and cli hosts to allow configuring it as the LDAP host
- updates the ocis-reva dependency to master to get eos gateway related fixes

### CODE REVIEW

**Comment by micbar** [comment]
I get an error 

```9:30PM ERR Users/mbarz/go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200416050838-5fc8adf27f83/internal/grpc/services/storageprovider/storageprovider.go:318 > error creating home error="eos: error creating nominal home: eos: error chowning directory: user: unknown user einstein" pid=76880 pkg=rgrpc traceid=1048d0c08d003817d6b6e3eba5339bab
9:30PM ERR Users/mbarz/go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200416050838-5fc8adf27f83/internal/grpc/services/storageprovider/storageprovider.go:319 > storageprovider: error calling CreateHome of storage driver error="eos: error creating nominal home: eos: error chowning directory: user: unknown user einstein" pid=76880 pkg=rgrpc traceid=1048d0c08d003817d6b6e3eba5339bab```

**Comment by refs** [comment]
while `make eos-start` seems to work, I'm trying to run `make eos-ocis`, but attempting to log with `einstein:relativity` just results on an unauthorized request:

Having a look at the logs it seems the auth provider finds the user, but the storage provider is not available (?):

image

**Comment by butonic** [comment]
@micbar @refs @kulmann make sure you killed all ocis processes and eos docker containers before running `make eos-start`.

the login error you are seeing is caused by ldap net being accessible from within the container...

please post the output of `docker exec -i eos-mgm1 authconfig --test`. verify it is the same en the container running the storageporvider with `docker exec -i eos-cli1 authconfig --test`

**Comment by butonic** [comment]
also `docker exec -it eos-mgm1 id einstein` and `docker exec -it eos-cli1 id einstein` should immediately return `uid=20000(einstein) gid=30000(users) groups=30000(users),30001(sailing-lovers),30002(violin-haters),30007(physics-lovers)`

**Pull request merged**
