### PR TITLE
Use CS3 user object fields to store UID and GID

### PR DESCRIPTION
**Pull request by ishank011**

### CODE REVIEW

**Comment by micbar** [comment]
can you remove the go.mod replace?

**Comment by ishank011** [comment]
@micbar something was broken in reva. Will fix and merge the corresponding commit in reva and then point ocis to the master.

**Review by butonic — APPROVED** [review]

**Comment by micbar** [comment]
@ishank011 Reva got updated to v1.9.0 in ocis.

Can you rebase? I would like to merge it before the release.

**Comment by ishank011** [comment]
@micbar I don't think a rebase is needed. Since the reva version was updated, this should work as is. Can you also review and merge https://github.com/owncloud/ocis/pull/2199?

**Pull request merged**
