### PR TITLE
Simple Ocis Binary

### PR DESCRIPTION
**Pull request by refs**
# Simple Ocis

To generate the simple-ocis binary:

```console
TAGS=simple make build
```

run it:

```console
./bin/ocis server
```

Services running
```
com.owncloud.api
com.owncloud.api.hello
com.owncloud.http.broker
com.owncloud.proxy
com.owncloud.registry
com.owncloud.router
com.owncloud.runtime
com.owncloud.web
com.owncloud.web.hello
com.owncloud.web.konnectd
com.owncloud.web.phoenix
```

Build ocis with the subset of services for easy extensions development.

I also went ahead and disabled some services I found we don't need at this stage, not only for simple ocis but for the entire binary.

# TODO

- [x] update docs

### CODE REVIEW

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/simple.go  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by butonic** [comment]
fixes https://github.com/owncloud/ocis/issues/75

**Comment by butonic** [comment]
for ocis simple we want to chenge the PhoenixCommand ... or introduce a PhoenixSimpleCommand that uses a different build flag ... not sure how to minimize code duplication.
```
	cfg.Phoenix.Phoenix.Config.Apps = []string{}
	cfg.Phoenix.Phoenix.Config.ExternalApps = []svcconfig.ExternalApp{
		svcconfig.ExternalApp{
			Name: "hello",
			Path: "http://localhost:9105/hello.js",
			Config: map[string]interface{}{
				"url": "http://localhost:9105",
			},
		},
	}
```
but can be dune in a subsequent PR

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/simple.go  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by refs** [comment]
> for ocis simple we want to change the PhoenixCommand ... or introduce a PhoenixSimpleCommand that uses a different build flag ... not sure how to minimize code duplication.
> 
> ```
> 	cfg.Phoenix.Phoenix.Config.Apps = []string{}
> 	cfg.Phoenix.Phoenix.Config.ExternalApps = []svcconfig.ExternalApp{
> 		svcconfig.ExternalApp{
> 			Name: "hello",
> 			Path: "http://localhost:9105/hello.js",
> 			Config: map[string]interface{}{
> 				"url": "http://localhost:9105",
> 			},
> 		},
> 	}
> ```
> 
> but can be done in a subsequent PR

cannot avoid code duplication, not without getting into some nasty logic using [go/build](https://golang.org/pkg/go/build/) for handling conditions on build flags.

In my opinion this duplication is at least accepted for this purpose. It can however be better structured and be separated on it's own folder (pkg) but then you'd have the same. The idiom of adding the `_simple` suffix to the filename makes clear that this files are only included for the `simple` build tags.

The confusing bit is the `!simple` on the excluded files. For the time being this PR fulfills the requirements we desire and I propose we ship it as it is, then build on top of it.

**Comment by refs** [comment]
@butonic do you want to include the phoenix simple command to this PR?

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/server_simple.go  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by butonic** [comment]
@refs no ... let us get the build tags in place first. we can then think about configuring phoenix and adding konnectd & devldap

**Comment by refs** [comment]
👍 I'll finish a few details and merge this.

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/server_simple.go  3
- pkg/tracing/tracing.go  9
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/server_simple.go  3
- pkg/tracing/tracing.go  9
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- pkg/tracing/tracing.go  9
- pkg/command/server_simple.go  3
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/server_simple.go  3
- pkg/tracing/tracing.go  9
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4791770&bid=15953404)

**Pull request merged**
