### PR TITLE
switch to opencontainers annotation for docker images

### PR DESCRIPTION
**Pull request by wkloucek**
## Description

Switch Docker image annotation scheme to org.opencontainers standard because org.label-schema is depreciated.

See: https://github.com/opencontainers/image-spec/blob/master/annotations.md
and: https://github.com/label-schema/label-schema.org/commit/737d003fcae1bf8380c68e57e3a107327eed9104

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by wkloucek** [comment]
@xoxys do you have an idea how to create a RFC 3339 formatted timestamp in starlark / drone ci?

**Comment by xoxys** [comment]
Hmm... not sure, after paying around with it, I can't get it to work

**Comment by wkloucek** [comment]
> Hmm... not sure, after paying around with it, I can't get it to work

I think then we need to leave it out and wait for drone to do it. You mentioned you have done it in your own plugin? Would that be something to contribute to upstream?

**Comment by wkloucek** [comment]
PR in drone-docker which adds opencontainer labels: https://github.com/drone-plugins/drone-docker/pull/313

**Comment by wkloucek** [comment]
@xoxys I removed the `org.opencontainers.image.created` label and for me it would be fine to merge

**Review by xoxys — APPROVED** [review]
LGTM

**Review by xoxys — CHANGES_REQUESTED** [review]
@wkloucek wait there is a typo in the documentation url `https://owncloud.github.io/ocis.git` should be `https://owncloud.github.io`

**Comment by wkloucek** [comment]
> @wkloucek wait there is a typo in the documentation url `https://owncloud.github.io/ocis.git` should be `https://owncloud.github.io`

is fixed

**Review by xoxys — APPROVED** [review]

**Pull request merged**
