### PR TITLE
introduce dedicated reva commands

### PR DESCRIPTION
**Pull request by butonic**
all prerequisitesn merged
- https://github.com/owncloud/ocis-reva/pull/4
- https://github.com/owncloud/ocis-phoenix/pull/29

### CODE REVIEW

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/revastoragehomedata.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revasharing.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revagateway.go  1
- pkg/command/revausers.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/phoenix_simple.go  -2
+ pkg/command/phoenix_ocis.go  -3
         

Clones added
============
- pkg/command/revastoragehomedata.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revasharing.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revagateway.go  1
- pkg/command/revausers.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4836621&bid=16063420)

**Comment by labkode** [comment]
@butonic @tboerger you can simplify even more the config now that https://github.com/cs3org/reva/pull/469 has been merged.

The simplified configs are in the usual place:
https://github.com/cs3org/reva/tree/master/examples/separate

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/revastorageoc.go  1
- pkg/command/revausers.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revasharing.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revafrontend.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/phoenix_ocis.go  -3
+ pkg/command/phoenix_simple.go  -2
         

Clones added
============
- pkg/command/revastorageoc.go  1
- pkg/command/revausers.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revasharing.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revafrontend.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4836621&bid=16063420)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/revaauthbearer.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revasharing.go  1
- pkg/command/revausers.go  1
- pkg/command/revastorageroot.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/phoenix_ocis.go  -3
+ pkg/command/phoenix_simple.go  -2
         

Clones added
============
- pkg/command/revaauthbearer.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revasharing.go  1
- pkg/command/revausers.go  1
- pkg/command/revastorageroot.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4836621&bid=16063420)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revasharing.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revausers.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revaauthbasic.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/phoenix_simple.go  -2
+ pkg/command/phoenix_ocis.go  -3
         

Clones added
============
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageoc.go  1
- pkg/command/revasharing.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revausers.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastoragehome.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revaauthbasic.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4836621&bid=16063420)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/revastoragehome.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revasharing.go  1
- pkg/command/revausers.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastorageoc.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/phoenix_simple.go  -2
+ pkg/command/phoenix_ocis.go  -3
         

Clones added
============
- pkg/command/revastoragehome.go  1
- pkg/command/revastoragehomedata.go  1
- pkg/command/revastorageocdata.go  1
- pkg/command/revafrontend.go  1
- pkg/command/revaauthbasic.go  1
- pkg/command/revasharing.go  1
- pkg/command/revausers.go  1
- pkg/command/revastorageroot.go  1
- pkg/command/revaauthbearer.go  1
- pkg/command/revagateway.go  1
- pkg/command/revastorageoc.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4836621&bid=16063420)

**Pull request merged**
