### PR TITLE
Improve idp login acessibility

### PR DESCRIPTION
**Pull request by JanAckermann**
Removed aria-labeledby from text input because for attribute already describes it. 

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by JanAckermann** [comment]
@UpdateBot no I won't there is already an existing changelog item.

**Comment by kulmann** [comment]
> @updatebot no I won't there is already an existing changelog item.

Add the link of the PR to the existing changelog item ;-)

**Comment by JanAckermann** [comment]
done

**Review by kulmann — APPROVED** [review]
👍

**Pull request merged**
