### PR TITLE
Allow config parsing on supervise mode only with `run` subcommand

### PR DESCRIPTION
**Pull request by refs**
## What?

What the descriptions says. Currenntly it is not possible to parse a single config file from an extension when running on supervised mode.

a) global ocis config file on /etc/ocis/ocis.yaml with the contents:

```yaml
proxy:
  http:
    addr: "0.0.0.0:6200"
accounts:
  http:
    addr: "0.0.0.0:8888"
Storage:
  Reva:
    StorageMetadata:
      Port:
        HTTPAddr: "0.0.0.0:7777"
```

b) a proxy config file /etc/ocis/proxy.json with the contents:

```json
{
        "http": {
                "addr": "0.0.0.0:5200"
        },
        "debug": {
                "addr": "0.0.0.0:5201"
        }
}
```

Running everything:
1) run ocis server // What will happen? /etc/ocis/ocis.yaml will get parsed and all extensions will inherit their config from it
2) run ocis kill proxy // What will happen? supervised proxy will die
3) run ocis run proxy // What will happen? /etc/ocis/proxy.json gets parsed and the proxy subcommand will run with the changes (it will no longer run the values from /etc/ocis/ocis.yaml)
this works for me with the changes on this branch: https://github.com/owncloud/ocis/tree/parse-config-when-run

it also supports this use case:
1) run ocis server
2) run ocis run proxy
and you should end up with 2 proxy instances bound to different ports.

---

A known issue that needs to be considered is the following: What should we do when we have a global ocis.yaml config file configuring all services and individual config files i.e: proxy.yaml? What should be the outcome of the following sequence of commands:

1) `ocis server` // with a global ocis.yaml in preconfigured locations (it configures a proxy)
2) `ocis kill proxy` // with a single proxy.yaml in the expected preconfigured locations
3) `ocis run proxy`

What could we expect from running (3) ? Should the proxy config in the global ocis.yaml take precedence over the single more granular proxy.yaml? Should both be considered and have their values merged?

The conundrum here is that we wouldn't only be talking here about source priorities on ENV var vs. CLI vs. config file but also between config files.

### CODE REVIEW

**Comment by refs** [comment]
Semantics are still slightly confusing and will probably need to be worked upon to avoid misunderstandings within the code base.

**Comment by wkloucek** [comment]
> 1. run ocis server // What will happen? /etc/ocis/ocis.yaml will get parsed and all extensions will inherit their config from it
> 2. run ocis kill proxy // What will happen? supervised proxy will die
> 3. run ocis run proxy // What will happen? /etc/ocis/proxy.json gets parsed and the proxy subcommand will run with the changes (it will no longer run the values from /etc/ocis/ocis.yaml)

What if there is no /etc/ocis/proxy.json ? Will the proxy then be started with default settings? I find it confusing that `ocis run` does something different than `ocis server`.

**Comment by refs** [comment]
> What if there is no /etc/ocis/proxy.json ? Will the proxy then be started with default settings?

Yes, this is also an issue.

> I find it confusing that `ocis run` does something different than `ocis server`. 

Me too, and I don't like the inconsistency, that's why I added that last comment. It is confusing and it needs a better thought process, but we literally have our hands tied due to Viper not being thread safe setup for a bad design :/

**Comment by wkloucek** [comment]
After #1929 I also run into this because I cannot configure the proxy with its configuration file. Even if I explicitly set it via environment variable `PROXY_CONFIG_FILE=proxy.json`.

**Comment by refs** [comment]
A known issue that needs to be considered is the following: What should we do when we have a global ocis.yaml config file configuring all services and individual config files i.e: proxy.yaml? What should be the outcome of the following sequence of commands:

1) `ocis server` // with a global ocis.yaml in preconfigured locations (it configures a proxy)
2) `ocis kill proxy` // with a single proxy.yaml in the expected preconfigured locations
3) `ocis run proxy`

What could we expect from running (3) ? Should the proxy config in the global ocis.yaml take precedence over the single more granular proxy.yaml? Should both be considered and have their values merged?

The conundrum here is that we wouldn't only be talking here about source priorities on ENV var vs. CLI Vvs config file but also on config files.

**Review by wkloucek — APPROVED** [review]
LGTM as quick fix, create ADR as followup

**Pull request merged**
