### PR TITLE
Add ocis-graph

### PR DESCRIPTION
**Pull request by refs**
git-subtree-dir: ocis-graph
git-subtree-mainline: 8146241777b62782ef28ba5c4d86f40a7b275f03
git-subtree-split: f1efaddc27c74c9de4509cd864fc673ffdf52e19

### CODE REVIEW

**Review by wkloucek — APPROVED** [review]
LGTM

**Comment by wkloucek** [comment]
@refs CI should be green soon

**Comment by kulmann** [comment]
How do we handle changes in directory layout? I know that this PR was just about pulling over the repo, but e.g. `docs` live in a root level folder in the monorepo. I'm in favor of aligning with the monorepo structure before we merge this PR, i.e. bring the docs to the right place already with this PR. I'd be happy to do it, just didn't want to commit to your PR without asking first. ;-)

**Review by wkloucek — CHANGES_REQUESTED** [review]
Documentation should be moved to github.com/owncloud/ocis/docs before merging as @kulmann stated.

**Comment by C0rby** [comment]
The assets step was removed. Was that intentional?

**Comment by C0rby** [comment]
I bet when we rebase with master the failing pipelines will not fail anymore.

**Comment by C0rby** [comment]
Ugh...seems like we're playing a new round of randomly failing tests again...
https://drone.owncloud.com/owncloud/ocis/3433
https://drone.owncloud.com/owncloud/ocis/3437
It's always different ones...

**Review by wkloucek — APPROVED** [review]
LGTM, will also go over it in #1580

**Pull request merged**
