### PR TITLE
use more linters reborn

### PR DESCRIPTION
**Pull request by kobergj**
## Description

See last try: https://github.com/owncloud/ocis/pull/3054

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by C0rby** [comment]
When you go to the [Sonarcloud report](https://sonarcloud.io/summary/new_code?id=owncloud_ocis&pullRequest=4335) you can see this warning:

> Unable to import 3 GolangCI-Lint report file(s).
Please check that property 'sonar.go.golangci-lint.reportPaths' is correctly configured and the analysis logs for more details.

**Comment by kobergj** [comment]
Yeah. But that doesn't make sense. Nothing changed with the paths of the reports. The file is still on same place as it was before. There is probably some timeout or other issue while analyzing. But I can't find this "analysis log" that the warning is talked about...

**Comment by kobergj** [comment]
Oh. Also this warning is being shown on all other builds too.

**Comment by C0rby** [comment]
Maybe this warning is shown because we are still trying to load reports of services we have removed, like the accounts service.

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-10</strong>](https://drone.owncloud.com/owncloud/ocis/14196/53/1) failed. Further test are cancelled...

**Pull request merged**
