### PR TITLE
[tests-only][full-ci]Backport/tests related to antivirus service

### PR DESCRIPTION
**Pull request by SwikritiT**
This PR backports following PR:
- https://github.com/owncloud/ocis/pull/6467
- https://github.com/owncloud/ocis/pull/6439
- https://github.com/owncloud/ocis/pull/6454
- https://github.com/owncloud/ocis/pull/6463
- https://github.com/owncloud/ocis/pull/6485
- https://github.com/owncloud/ocis/pull/6484
- https://github.com/owncloud/ocis/pull/6506

part of: https://github.com/owncloud/ocis/issues/6255

### CODE REVIEW

**Review by SagarGi — COMMENTED** [review]
LGTM if CI is green :+1:

**Review by saw-jan — APPROVED** [review]
LGTM

**Review by SagarGi — APPROVED** [review]

**Comment by SwikritiT** [comment]
@ScharfViktor @phil-davis the `Codacy Static Code Analysis` keeps failing in `stable-3.0` branch maybe it's not enabled here? But these changes should be okay to be merged. If anyone of you have enough right to force merge this PR then that would help(after the CI is green).

**Comment by SwikritiT** [comment]
```bash
--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Given the config :arg1 has been set to :arg2
     */
    public function theConfigHasBeenSetTo($arg1, $arg2)
    {
        throw new PendingException();
    }
```

needs : https://github.com/owncloud/ocis/pull/6402 to be backported first

**Comment by phil-davis** [comment]
> needs : https://github.com/owncloud/ocis/pull/6402 to be backported first

PR #6527 dies that backport. CI is currently running there...

**Comment by phil-davis** [comment]
PR #6527 has been merged.
@SwikritiT please rebase this PR.

**Comment by SwikritiT** [comment]
> PR #6527 has been merged. @SwikritiT please rebase this PR.

done

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
