### PR TITLE
fixed WOPISERVER_INSECURE in entrypoint script for wopiserver

### PR DESCRIPTION
**Pull request by d7oc**
## Description
Currently setting `WOPISERVER_INSECURE` doesn't work. You will only see a line like 

```
ocis_wopi-wopiserver-1  | /entrypoint-override.sh: 9: [: true: unexpected operator
```

in the log file. The reason is that bash scripts ain't no sh skripts:

```
docker-compose exec wopiserver bash                                                                                                         
root@565a743c8ff2:/app# if [ "$WOPISERVER_INSECURE" == "true" ]; then echo test; fi
test
root@565a743c8ff2:/app# exit
docker-compose exec wopiserver sh
# if [ "$WOPISERVER_INSECURE" == "true" ]; then echo test; fi
sh: 1: [: true: unexpected operator
#
```

This PR fixes the issue by changing the execution shell of the skript from `sh` to `bash`

## Related Issue
- none

## Motivation and Context
Bugfix

## How Has This Been Tested?
Tested locally by setting `WOPISERVER_INSECURE` to `true` and checking if `sslverify` in `/etc/wopi/wopiserver.conf` becomes `false`.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by wkloucek** [comment]
@d7oc after merging master into your PR and trying to run it, I get:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown`

**Comment by d7oc** [comment]
> @d7oc after merging master into your PR and trying to run it, I get:
> `Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown`

Interesting. I tested this here, there was no such message. I will try again. Maybe there were some changes in master in the image which break this.

**Comment by d7oc** [comment]
I don't get the error message here. Anything special you have configured? Maybe a different wopiserver tag?

```
> docker run -d cs3org/wopiserver:v10.1.0
69e9b768eb1966081792843f4c8ffa117ff95527e0bf77f51705b83439e0b80c
docker exec -it 69e9b768eb1966081792843f4c8ffa117ff95527e0bf77f51705b83439e0b80c bash
root@69e9b768eb19:/app#
```

**Comment by d7oc** [comment]
Summarising the result of the research so far here:

Main problem is that the wopiserver has two base images, see linked issue above. The error I've written here only pops up with the `arm64` image at all. The `amd64` image doesn't even have the issue:

```
docker run -it --entrypoint /bin/sh --platform linux/arm64 cs3org/wopiserver:v10.1.0
# if [ "$WOPISERVER_INSECURE" == "true" ]; then echo test; fi
/bin/sh: 1: [: unexpected operator
root@d7-ubuntu-4gb-nbg1-2:~# docker run -it --platform linux/amd64 --entrypoint /bin/sh cs3org/wopiserver:v10.1.0
/app # if [ "$WOPISERVER_INSECURE" == "true" ]; then echo test; fi
---

```

This is because `sh` leads to different execution environments:

```
docker run -it --entrypoint /bin/sh --platform linux/arm64 cs3org/wopiserver:v10.1.0
# ls -la /proc/$$/exe
lrwxrwxrwx 1 root root 0 Aug 25 12:18 /proc/1/exe -> /bin/dash
---
root@d7-ubuntu-4gb-nbg1-2:~# docker run -it --platform linux/amd64 --entrypoint /bin/sh cs3org/wopiserver:v10.1.0
/app # ls -la /proc/$$/exe
lrwxrwxrwx    1 root     root             0 Aug 25 12:16 /proc/1/exe -> /bin/busybox
```

So the `sh` script is executed by `dash` on `arm64`.

**Comment by d7oc** [comment]
Changed approach with https://github.com/owncloud/ocis/pull/7084/commits/004ac82f304b959119f2486f71f1b3dfda0b69a6. Made the script compatible with `dash` and `busybox`.

**Review by micbar — APPROVED** [review]

**Pull request merged**
