### PR TITLE
[tests-only][full-ci]Extend tests related to assign role

### PR DESCRIPTION
**Pull request by amrita-shrestha**
## Description
This PR expand tests coverage for assign role

## Related Issue
- https://github.com/owncloud/ocis/issues/5564

## How Has This Been Tested?

- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by saw-jan — COMMENTED** [review]
LGTM
:information_source: Also, remember that we need to get these php code changes to the stable as well. Probably after #5671

**Comment by amrita-shrestha** [comment]
> LGTM information_source Also, remember that we need to get these php code changes to the stable as well. Probably after #5671

@saw-jan  Why backport unnecessary PHP code to a stable branch?

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Review by saw-jan — COMMENTED** [review]
LGTM

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
