### PR TITLE
[full-ci] add web url to graph api and update reva

### PR DESCRIPTION
**Pull request by micbar**
## Description

Add web URL to graph api.

Fixes: #4523 
Fixes: https://github.com/owncloud/product/issues/262

### Example

```sh
curl -L -X GET "https://localhost:9200/graph/v1.0/me/drives/" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```

```json
{
    "value": [
        {
            "driveAlias": "personal/admin",
            "driveType": "personal",
            "id": "1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000",
            "lastModifiedDateTime": "2022-09-13T23:19:02.486808+02:00",
            "name": "Admin",
            "owner": {
                "user": {
                    "id": "some-admin-user-id-0000-000000000000"
                }
            },
            "quota": {
                "remaining": 9888362496,
                "state": "normal",
                "total": 0,
                "used": 3146459
            },
            "root": {
                "eTag": "\"d654495040600828a17594d6041a7454\"",
                "id": "1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000",
                "webDavUrl": "https://localhost:9200/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000"
            },
            "webUrl": "https://localhost:9200/f/1284d238-aa92-42ce-bdc4-0b0000009157$some-admin-user-id-0000-000000000000"
        }
    ]
}
```

## Update reva

Fixes: #4545 
Fixes: #4357 
Fixes: #4473 

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by micbar** [comment]
@kulmann @michaelstingl FYI

**Comment by kulmann** [comment]
IMO this should not be merged at the moment. Web doesn't resolve private links for ocis / spaces, yet. Announcing the url to other clients will "unlock" features in clients which are then not supported in web.

**Comment by kulmann** [comment]
> IMO this should not be merged at the moment. Web doesn't resolve private links for ocis / spaces, yet. Announcing the url to other clients will "unlock" features in clients which are then not supported in web.

Discussed that we'll merge it since it's a GA blocker = the next ocis release (in this case a release candidate) will have the private link support in web, no earlier release possible.

**Review by rhafer — APPROVED** [review]

**Comment by ScharfViktor** [comment]
Request is without [local](https://localhost:9200/) `"webUrl": "f/1284d238-aa92-42ce-bdc4-0b0000009157$c3559ab4-3a67-490f-805c-e2fec84e94b5"`

**Pull request merged**
