### PR TITLE
chore!: remove deprecated configuration values

### PR DESCRIPTION
**Pull request by fschade**
@dragonchaser do i miss something or is it fine, ive also found some `removalVersion:"%%NEXT%%"`, are we in charge of that?

### CODE REVIEW

**Comment by dragonchaser** [comment]
@fschade yes we are, see https://github.com/owncloud/ocis/issues/9254

**Comment by fschade** [comment]
> @fschade yes we are, see #9254

thanks, makes sense!

**Review by dragonchaser — CHANGES_REQUESTED** [review]
Do not remove those now, change `removalVersion` to ```%%NEXT_PRODUCTION_VERSION%%``` because we only can remove variables in production versions not in rolling. And please add a ticket to change all other affected variables.

**Comment by dragonchaser** [comment]
@fschade we did not miss it, this plan is a leftover before we introduced rolling vs. production. They should have been updated, this is what we missed, not the removal.

**Review by micbar — APPROVED** [review]

**Review by dragonchaser — APPROVED** [review]

**Pull request merged**
