### PR TITLE
Update ocis reva + revert selenium

### PR DESCRIPTION
**Pull request by PVince81**
Combination of https://github.com/owncloud/ocis/pull/259 and https://github.com/owncloud/ocis/pull/254 to fix CI

### CODE REVIEW

**Comment by PVince81** [comment]
still failing:
```
Error: Could not create the file "test_sort/a space 文件" for user "user1". Status:500 Internal Server ```

**Comment by individual-it** [comment]
CC @dpakach

**Comment by PVince81** [comment]
@individual-it any update on the test issues ?

**Comment by individual-it** [comment]
it seems to be an issue with the updates, that started 4 days ago @dpakach is investigating

**Comment by PVince81** [comment]
closing as the Selenium thing did not help, going back to https://github.com/owncloud/ocis/pull/259

**Pull request closed without merging**
