### PR TITLE
Specify primary user type for all accounts

### PR DESCRIPTION
**Pull request by ishank011**

### CODE REVIEW

**Review by C0rby — APPROVED** [review]

**Comment by wkloucek** [comment]
@ishank011 the docs part of the CI will become green after https://github.com/owncloud/ocis/pull/2366

**Comment by phil-davis** [comment]
PR #2366 has been merged.

But we also have issue https://github.com/owncloud/web/issues/5640#issuecomment-894118384 - this PR comes from a fork, and the stop-recent-builds code does not work in that case. But if all the other CI passes then we can force-merge for now.

**Comment by ishank011** [comment]
@wkloucek @phil-davis the docs job passed but the rest were killed because `stop-recent-builds` failed

**Comment by wkloucek** [comment]
> @wkloucek @phil-davis the docs job passed but the rest were killed because `stop-recent-builds` failed

will be taken care of in https://github.com/owncloud/ocis/pull/2368

**Comment by wkloucek** [comment]
@ishank011 could you please rebase onto latest master? sorry for the inconvenience

**Comment by ishank011** [comment]
No worries @wkloucek! Thanks a lot for handling it so quickly!

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/6279
Looks good - "stop-recent-builds" has passed.

**Pull request merged**
