### PR TITLE
Add option to generate the demo users

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Include an option to generate the demo users and groups. Only a minimal set of users and groups will be generated automatically unless the new option is enabled.

So far the minimal set includes:
* for users -> the reva IOP, the Kopano IDP, and the admin user. (passwords remain unchanged)
* for groups -> the sysusers group, and the users group.

## Related Issue
https://github.com/owncloud/ocis/issues/2484

## How Has This Been Tested?
* Start a fresh installation with the new option activated -> the demo users will be generated as it has been happening until now.
* Start a fresh installation without the new option -> only a minimal set of users and groups will be generated.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by wkloucek** [comment]
@jvillafanez I'm not sure if we should stick with the default to create demo users as long as we are in the tech preview stage.
We also should mention this new config option in the docs here https://owncloud.dev/ocis/deployment/#secure-an-ocis-instance

**Comment by jvillafanez** [comment]
I agree. We can merge this (it seems there are tests to adjust) once we get close to the actual product release

**Comment by wkloucek** [comment]
> I agree. We can merge this (it seems there are tests to adjust) once we get close to the actual product release

No, I would love to have this right now. I just wanted to have the demo users as a default as of now ;-) So basically an opt-out instead of an opt-in to demo users...

**Comment by jvillafanez** [comment]
From a product perspective, I think this option is better. Usually, you don't want to create demo users that you need to delete afterwards. This is why we don't want to create the demo users by default.
The demo users are a convenience now during the tech preview, but later they'll be in the way.

I'd vote for keeping this behavior.

**Comment by C0rby** [comment]
> From a product perspective, I think this option is better. Usually, you don't want to create demo users that you need to delete afterwards.

That is true but currently we are still heavily in dev mode and are using the demo users during development. I think it would make developing a little bit more annoying if we have to explicitly generate the accounts every time we delete the ocis storage.

So I'm agreeing with @wkloucek here. I'd like to have an opt-out option for now and later on when we have more "productive" deployments we can always (and should) switch to opt-in.

We could then also move this code to a command in the accounts service like `./ocis accounts create-demo-users` or something like that.

**Comment by jvillafanez** [comment]
Turns out it's easier than initially thought... The default value is set to true, and we only need to change it to false (or remove it) when we no longer want to create the demo users by default. In any case, the environment variable will be respected if present.

**Comment by jvillafanez** [comment]
I think this is ready to review and merge.

**Review by C0rby — APPROVED** [review]
LGTM.

**Pull request merged**
