### PR TITLE
[full-ci] Bump web to v4.8.0

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
The next oCIS release is a bit away but we released a minor version of web which we should try to bring into oCIS to have all the Reva edge stuff test against it 👷🏽

### CODE REVIEW

**Review by wkloucek — APPROVED** [review]
I'm happy, if the CI is happy

**Comment by pascalwengerter** [comment]
I'm a bit surprised by _translations in the settings service_ appearing now 🤔

**Review by kulmann — APPROVED** [review]

**Comment by kulmann** [comment]
> I'm a bit surprised by _translations in the settings service_ appearing now 🤔

Well... in reality it's just modified translations in transifex. Those get pulled into `settings` and `accounts` in a nightly CI run of the `translation-sync` job, see e.g. https://drone.owncloud.com/owncloud/translation-sync/2211/36/1

The e2e tests for the settings UI compare hardcoded strings. Or in other words: some snapshot of the translations is basically cemented into the code. If contents change in transifex they need to be updated in the settings e2e tests. Which is awful. :-( To get the tests green, just streamline https://github.com/owncloud/ocis/blob/master/settings/ui/tests/acceptance/helpers/language.js to be the same as in transifex again. And if you have a better idea of how to test if a language setting works properly feel free to propose something. Happy to get this more resilient for the future...

**Comment by pascalwengerter** [comment]
> > I'm a bit surprised by _translations in the settings service_ appearing now thinking
> 
> Well... in reality it's just modified translations in transifex. Those get pulled into `settings` and `accounts` in a nightly CI run of the `translation-sync` job, see e.g. https://drone.owncloud.com/owncloud/translation-sync/2211/36/1
> 
> The e2e tests for the settings UI compare hardcoded strings. Or in other words: some snapshot of the translations is basically cemented into the code. If contents change in transifex they need to be updated in the settings e2e tests. Which is awful. :-( To get the tests green, just streamline https://github.com/owncloud/ocis/blob/master/settings/ui/tests/acceptance/helpers/language.js to be the same as in transifex again. And if you have a better idea of how to test if a language setting works properly feel free to propose something. Happy to get this more resilient for the future...

But the linked translation job (~10h ago, 10am German time) was the one I started for the web release so how come the translations have diverged between the two repos when the job updated them both to the most recent Transifex version?

**Comment by kulmann** [comment]
> But the linked translation job (~10h ago, 10am German time) was the one I started for the web release so how come the translations have diverged between the two repos when the job updated them both to the most recent Transifex version?

Settings ui translations are not in web. They are in ocis. Should be completely independent from the web update.

**Comment by wkloucek** [comment]
@pascalwengerter do you need help on this?

**Comment by pascalwengerter** [comment]
> @pascalwengerter do you need help on this?

Thanks for the reminder, can't hurt to give it a look tomorrow. Still confused why it failed, we'll most likely release web v4.8.0 tomorrow (Tuesday) so let me update this PR and ping you then

**Comment by pascalwengerter** [comment]
Will bump to v4.8.0 as soon as it's released, then this PR should be easily merge-able thanks to language changes in https://github.com/owncloud/web/pull/6176/commits/e1da7267b951d78157641f45a8cf2cef179dec5a

**Pull request merged**
