### PR TITLE
[full-ci] [tests-only] Bump core and web commit id

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Bumped commit IDs of `core` to get the latest core API test scenarios

part of https://github.com/owncloud/QA/issues/662
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
If PR #2205 passes CI and gets merged soon, then please rebase this PR so that we run all the tests with the latest code that is imported from reva into OCIS.

**Comment by saw-jan** [comment]
> If PR #2205 passes CI and gets merged soon, then please rebase this PR so that we run all the tests with the latest code that is imported from reva into OCIS.

Sure!!

**Comment by phil-davis** [comment]
Note: CI passed a few hours ago here: https://drone.owncloud.com/owncloud/ocis/5563

The PR has now been rebased. I expect it will pass again!

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Similar reva PR is https://github.com/cs3org/reva/pull/1816

**Review by kulmann — APPROVED** [review]
👍

**Comment by phil-davis** [comment]
Note: I will let the current CI finish - that is doing a "minimal" CI with just the web smoke tests. Then I will restart it to get a full run of web tests (I added "full-ci" to the title)

**Pull request merged**
