### PR TITLE
[test-only] apiTest. change own password

### PR DESCRIPTION
**Pull request by ScharfViktor**
- added api tests for changing own password

in case the user sends an incorrect current password, we get a 500 Server error.  @rhafer Is it correct? 

maybe we should return 400 with "incorrect current password"? 

in the comparison oc10 returns 200 and message: 
Screenshot 2022-08-31 at 09 31 41

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiGraph-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/15061/43/1) failed. Further test are cancelled...

**Comment by rhafer** [comment]
> in case the user sends an incorrect current password, we get a 500 Server error. @rhafer Is it correct?

Currently that is intentional. See https://github.com/owncloud/ocis/pull/3705#discussion_r868072910 . Though thinking about this again the reasoning (avoiding brute-force attacks) seems somehow wrong as the /me/changePassword endpoint is only exposed to authenticated users (an only for changing their own password). I am open to revisit that decision.

> maybe we should return 400 with "incorrect current password"?

Yeah. It might make sense. I'll open a PR for discussion.

> in the comparison oc10 returns 200 and message:

That's an interesting behaviour. Seems at least weird to me.

**Comment by ScharfViktor** [comment]
> Yeah. It might make sense. I'll open a PR for discussion.

Thank you, then the web can process the response and give the user a message-reason "wrong current password" what is wrong

> That's an interesting behaviour. Seems at least weird to me.

Me too. 200 is incorrect

**Comment by ScharfViktor** [comment]
How do you prefer, change the test to 400 and move it to expected failures? or will you change the test when you fix the bug?

**Comment by rhafer** [comment]
> or will you change the test when you fix the bug?

I'll update the test, with my PR.

**Review by rhafer — APPROVED** [review]
lgtm

**Pull request merged**
