### PR TITLE
Update ocis-konnectd and ocis-phoenix

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Strangely I cannot connect the graph-explorer ....

Getting: 400 Bad Request - unknown client_id: ocis-explorer.js

need to dig deeper ....

### CODE REVIEW

**Comment by IljaN** [comment]
Check your ./config/identifier-registration.yaml in the $PWD of ocis-konnectd binary. It writes this file to disk on launch if it does not exists. Maybe it is still using the older version from a previous run/build on your local machine.

**Comment by IljaN** [comment]
Could we merge https://github.com/owncloud/ocis-konnectd/pull/22 before updating?

**Comment by DeepDiver1975** [comment]
> Check your ./config/identifier-registration.yaml in the $PWD of the ocis/ocis-konnectd binary.

I don't get the relation - ocis-konnectd is grabbed from github and not from my local workspace.

**Comment by DeepDiver1975** [comment]
> Check your ./config/identifier-registration.yaml

ah - in the ocis workspace :+1:

**Comment by DeepDiver1975** [comment]
the oidc middleware required the insecure flag to be set:

```sh
GRAPH_OIDC_INSECURE=1 ./bin/ocis server

**Comment by DeepDiver1975** [comment]
> Could we merge [owncloud/ocis-konnectd#22](https://github.com/owncloud/ocis-konnectd/pull/22) before updating?

merged by @refs and this PR is updated as well

**Pull request merged**
