### PR TITLE
Update extensions thumbnails and reva to tagged versions

### PR DESCRIPTION
**Pull request by PVince81**
- ocis-thumbnails v0.1.2 (tag)
- ocis-reva v0.3.0 (tag)

### CODE REVIEW

**Comment by PVince81** [comment]
I also had to edit the Drone config to install the mime types, see last commit. (also done on ocis-reva)

**Comment by PVince81** [comment]
looks like another weird discrepancy:
```
    [1mExamples:[22m
      |[36;1m ocs_api_version [39;22m|[36;1m ocs_status_code [39;22m|
      |[32m 1               [39m|[32m 100             [39m|
        │ share_with_displayname has unexpected value 'Brian'
        │ 
[31m        share_with_displayname doesn't have value 'Brian Murphy'
        Failed asserting that false is true.[39m
      |[32m 2               [39m|[32m 200             [39m|
        │ share_with_displayname has unexpected value 'Brian'
        │ 
[31m        share_with_displayname doesn't have value 'Brian Murphy'
        Failed asserting that false is true.[39m
```

maybe the test users aren't 100% the same as in ocis-reva ?

@individual-it

**Comment by individual-it** [comment]
strange https://cloud.drone.io/owncloud/ocis/554 worked but after the merge not https://cloud.drone.io/owncloud/ocis/555 maybe that was just when https://github.com/owncloud/core/pull/37396 got merged

**Comment by individual-it** [comment]
I've added `'REVA_LDAP_SCHEMA_*` settings to drone that made it work I think the important for this case was specially `'REVA_LDAP_SCHEMA_DISPLAYNAME': 'displayName'`
I don't understand why this settings suddenly need to be added, they have been in reva but already for a long time https://github.com/owncloud/ocis-reva/pull/127/files#diff-74dc60589e0610c07e491b31f8693b2bR140

**Pull request merged**
