### PR TITLE
chore: prepare release v5.0.0-alpha.4

### PR DESCRIPTION
**Pull request by kulmann**
Merge back version bump after pre-release `v5.0.0-alpha.4`.

### CODE REVIEW

**Comment by kulmann** [comment]
@micbar I tagged the `v5.0.0-alpha.4` on the first commit of this PR, i.e. with changelog items being in an `5.0.0-2023-11-30` folder, so that the changelog can get generated correctly. After tagging, I added a second commit to this PR which moves back the changelog items to the `unreleased` folder, so that the `master` branch can continue to update existing changelog items (e.g. we do that for the web changelog item). What do you think about this proposal? Fine like that or do you want me to remove the second commit?

**Review by JammingBen — APPROVED** [review]

**Comment by micbar** [comment]
hmm, can you remove the last commit? I want to use the released versions with the new calens 0.4.0 release.

**Comment by kulmann** [comment]
> hmm, can you remove the last commit? I want to use the released versions with the new calens 0.4.0 release.

of course, done

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
search CI is failing, has already stablilized in master branch. Merging.

**Pull request merged**
