### PR TITLE
[full-ci] Prepare Release 5.0.1

### PR DESCRIPTION
**Pull request by micbar**
# Description

- [x] Run Full CI
- [x] Create tag
- [x] merge back into `stable-5.0`

### CODE REVIEW

**Comment by micbar** [comment]
@mmattel Patch release incoming 😏

**Comment by mmattel** [comment]
Thx. Q: will there be a changelog entry + content for 5.0.1 ?

**Review by d7oc — APPROVED** [review]
LGTM. But I don't know if my opinion should be rated that high 😉.

**Comment by micbar** [comment]
@d7oc  I wanted to keep you in the loop that you can see the release and the changelog. No code changes in this PR, except the version string.

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
Docs is prepared with the current changes known, see the referenced PR.

**Review by wkloucek — DISMISSED** [review]

**Comment by micbar** [comment]
@wkloucek please re test, should work now with the last push.

**Review by wkloucek — APPROVED** [review]
Tested with https://github.com/owncloud/ocis-charts/pull/526

**Review by dragonchaser — CHANGES_REQUESTED** [review]
Currently crashing with stack-overflow here, investigating.

**Comment by micbar** [comment]
> Currently crashing with stack-overflow here, investigating.

Run make generate. CI is running fine.

**Review by dragonchaser — APPROVED** [review]
thx @micbar for the hint, tested & works

**Pull request merged**
