### PR TITLE
Remove jarnaiz/behat-junit-formatter from acceptance tests

### PR DESCRIPTION
**Pull request by kiranparajuli589**
### Description
- composer allow plugins
- remove jarniaz/behat-junit-formatter

### Related Issue
- part of https://github.com/owncloud/QA/issues/737

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
IMO we don't want to commit all the source code of composer-bin-plugin

**Comment by kiranparajuli589** [comment]
> IMO we don't want to commit all the source code of composer-bin-plugin

removed all `vendor-php` stuffs

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/10794/38/15
@kiranparajuli589 
something in parallel deployment test pipelines still mentions jarnaiz/behat-junit-formatter0

**Review by phil-davis — APPROVED** [review]

**Comment by kiranparajuli589** [comment]
> https://drone.owncloud.com/owncloud/ocis/10794/38/15 @kiranparajuli589 something in parallel deployment test pipelines still mentions jarnaiz/behat-junit-formatter0

oh yes, there is the separate config for parallel deployment tests. Removed the formatter related config from there too.

**Pull request merged**
