### PR TITLE
[full-ci] [tests-only] Remove scenarios tagged skiponocis

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
This PR removes `@skipOnOcis` tagged scenarios from ocis.
We cannot set `Sharing settings` in ocis https://github.com/owncloud/ocis/issues/1328.

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/5337

## How Has This Been Tested?

- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by grgprarup** [comment]
- [ ] Forward port to master

**Comment by phil-davis** [comment]
https://github.com/owncloud/ocis/tree/remove-scenarios-tagged-skiponocis
"This branch is [128 commits ahead](https://github.com/owncloud/ocis/compare/master...remove-scenarios-tagged-skiponocis), [583 commits behind](https://github.com/owncloud/ocis/compare/remove-scenarios-tagged-skiponocis...master) master."

That is a bit scary. Please rebase to get really up-to-date CI. I don't want to merge this and then find that there is some unexpected problem.

**Comment by grgprarup** [comment]
> https://github.com/owncloud/ocis/tree/remove-scenarios-tagged-skiponocis "This branch is [128 commits ahead](https://github.com/owncloud/ocis/compare/master...remove-scenarios-tagged-skiponocis), [583 commits behind](https://github.com/owncloud/ocis/compare/remove-scenarios-tagged-skiponocis...master) master."
> 
> That is a bit scary. Please rebase to get really up-to-date CI. I don't want to merge this and then find that there is some unexpected problem.

I will make forward port pr to the master branch.

**Comment by phil-davis** [comment]
Oh, I forgot that this is to `stable-2.0` branch, sorry. The message about being behind is not relevant.

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Review by phil-davis — APPROVED** [review]

**Review by individual-it — APPROVED** [review]

**Pull request merged**
