### PR TITLE
[full-ci][k6-test] chore: prepare release, bump version

### PR DESCRIPTION
**Pull request by micbar**
## Description

- [x] Run Full CI
- [x] Create tag `v7.0.0-rc.2`
- [x] Merge back into `master`

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by mmattel — APPROVED** [review]
LGTM from a docs pov

**Review by ScharfViktor — APPROVED** [review]
LGTM but CI will be red due to this issue https://github.com/owncloud/ocis/issues/10545

**Comment by micbar** [comment]
@ScharfViktor i would create the new tag and keep the known issue.

**Comment by ScharfViktor** [comment]
> @ScharfViktor i would create the new tag and keep the known issue.

I'm fine with it. should we restart without [k6-test] or do you can merge?

**Pull request merged**
