### PR TITLE
Update ocis-phoenix to 0.13.0

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Review by kulmann — APPROVED** [review]
🚀

**Comment by LukasHirt** [comment]
Agh... tests always fails in a different scenario 😞

**Comment by PVince81** [comment]
conflicts

**Comment by phil-davis** [comment]
https://cloud.drone.io/owncloud/ocis/1355/5/7
```
runsh: Total unexpected passed scenarios throughout the test run:
apiTrashbin/trashbinFilesFolders.feature:136
```

That is really strange - why would this Phoenix change make a trashbin API test start passing???

**Comment by phil-davis** [comment]
I restarted CI.

And made PR #502 just to see if a regular CI run from current master is passing OK.

**Comment by phil-davis** [comment]
Passed, and #502 also passed. So that API test can fail randomly :(

**Comment by LukasHirt** [comment]
@phil-davis Thanks!

**Pull request merged**
