### PR TITLE
[full-ci] bump reva to v2.15.1-0.20230809113840-3ceaf17cf7fb

### PR DESCRIPTION
**Pull request by butonic**
bumping reva to make jsoncs3 more robust: https://github.com/cs3org/reva/pull/4101

### CODE REVIEW

**Comment by micbar** [comment]
please run with full-ci @butonic

**Comment by ScharfViktor** [comment]
https://drone.owncloud.com/owncloud/ocis/25234/74/13
You may have already found the problem, but anyway my findings:

We cannot open the `testavatar.JPG` file in preview, so the test fails: https://github.com/owncloud/ocis/assets/84779829/8f1e4bb1-e11d-4063-92c2-4823b911416f

**Comment by butonic** [comment]
@micbar reported this is a problem with the new extension based mimetype detection in reva introduced by @aduffeck

**Comment by micbar** [comment]
needs a new bump to reva latest edge

**Review by kobergj — APPROVED** [review]

**Review by micbar — APPROVED** [review]

**Pull request merged**
