### PR TITLE
[full-ci] Release 1.10.0

### PR DESCRIPTION
**Pull request by fschade**
merge back after https://github.com/owncloud/ocis/issues/2342

### CODE REVIEW

**Comment by phil-davis** [comment]
The title of this PR says "Release 1.9.0" but the changes bump the version to `1.10.0` - what is the situation?

**Comment by pascalwengerter** [comment]
> The title of this PR says "Release 1.9.0" but the changes bump the version to `1.10.0` - what is the situation?

Probably a copy-past error, thanks for the hint. We're releasing 1.10

**Comment by fschade** [comment]
> The title of this PR says "Release 1.9.0" but the changes bump the version to `1.10.0` - what is the situation?

fat finger error :( fixed

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-7</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
```
runsh: Total unexpected passed scenarios throughout the test run:
apiSharees/sharees.feature:157
apiSharees/sharees.feature:158
apiSharees/sharees.feature:430
apiSharees/sharees.feature:431
apiSharees/sharees.feature:450
apiSharees/sharees.feature:451
apiSharees/sharees.feature:475
apiSharees/sharees.feature:476
```

**Comment by phil-davis** [comment]
Note: I killed that `continuous-integration/drone/push `build  - it is duplicate CI and not needed.

**Comment by phil-davis** [comment]
I removed the passing tests from expected-failures. IMO CI should pass now.

**Review by phil-davis — APPROVED** [review]
LGTM - must be good when scenarios are deleted from expected-failures and CI passes!

**Review by wkloucek — APPROVED** [review]
LGTM

**Pull request merged**
