### PR TITLE
[docs-only] add docs for macOS ulimits

### PR DESCRIPTION
**Pull request by micbar**
## Description
add docs for macOS ulimits

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by micbar** [comment]
@mmattel JFYI

**Review by fschade — APPROVED** [review]
one smallish thing, not sure if its critical or not....

`ocis` || `oCIS`

expect that, LGTM 🚀

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-8</strong>](https://drone.owncloud.com/owncloud/ocis/12149/46/1) failed. Further test are cancelled...

**Comment by pascalwengerter** [comment]
Should we open a ticket to track this as technical debt (expecting that this will be handled differently in the future)?

**Comment by micbar** [comment]
> Should we open a ticket to track this as technical debt (expecting that this will be handled differently in the future)?

No, we cannot change that. We have about 30 services running in the oCIS fullstack server. The limits on mac are just too small. This problem does not occur when using docker because that hides it in the docker VM and the container has a running linux which has a default of `1024`

**Comment by pascalwengerter** [comment]
> > Should we open a ticket to track this as technical debt (expecting that this will be handled differently in the future)?
> 
> No, we cannot change that. We have about 30 services running in the oCIS fullstack server. The limits on mac are just too small. This problem does not occur when using docker because that hides it in the docker VM and the container has a running linux which has a default of `1024`

Ok, thx for clarification!

**Pull request merged**
