### PR TITLE
Pin acceptance test middleware version

### LINKED ISSUE #2983: pin test middleware
currently the latest version of the middleware  is used here, we should pin it like in other repos to avoid issues when changes are made

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #2983

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
CI failed with `generate nodejs: Error response from daemon: No such image: owncloudci/nodejs:14` restarting

**Comment by phil-davis** [comment]
`owncloudci/nodejs:14` - that is surprising. I thought that we were up to `owncloudci/nodejs:16` everywhere???

**Comment by individual-it** [comment]
same in web https://github.com/owncloud/web/blob/master/.drone.star#L9

**Comment by phil-davis** [comment]
Maybe it was the middleware that needed nodejs 16 - my brain is fried today.

**Comment by pascalwengerter** [comment]
> Maybe it was the middleware that needed nodejs 16 - my brain is fried today.

The middleware's own docker image is built using nodejs, I wouldn't be aware of that making the use of nodejs 16 necessary to build & run the acceptance test dependencies

**Pull request merged**
