### PR TITLE
chore: bump production version to v5.0.6 for ocis_full

### PR DESCRIPTION
**Pull request by kulmann**
Release `v5.0.6` is done, now updating the deployment example `ocis_full` for production demo.

### CODE REVIEW

**Comment by ScharfViktor** [comment]
do we need Forward port stable-5.0 changelog? https://github.com/owncloud/ocis/pull/9629/files#diff-43ed9d31bea2a6d518d69836bcd1a8e6bd81bf4df96c4745792c220ca5aa549c

to have `changelog/5.0.6_`

**Comment by kulmann** [comment]
superseded by https://github.com/owncloud/ocis/pull/9660

**Comment by kulmann** [comment]
> do we need port changelog from stable-5.0? https://github.com/owncloud/ocis/pull/9629/files
> 
> to have `changelog/5.0.6_`

don't know. @micbar how do you handle this here?

**Comment by micbar** [comment]
We need to copy that to the master branch.

**Pull request closed without merging**
