### PR TITLE
[full-ci] Bump web to v5.3.0-rc.1

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Pre-release to introduce a bunch of spaces UI improvements (huge kudos to @JanAckermann and @JammingBen ), alongside other fixes & stuff.

### CODE REVIEW

**Comment by pascalwengerter** [comment]
Damn, forgot to update the settings tests 🤦‍♂️ will do so tomorrow morning

**Comment by kulmann** [comment]
There's a typo in the german translations. Let's make an rc2 and wait with this PR for that. Objections?

**Review by JanAckermann — APPROVED** [review]

**Comment by pascalwengerter** [comment]
> There's a typo in the german translations. Let's make an rc2 and wait with this PR for that. Objections?

Nope, sounds good to me. CI is green but the typo would need to be fixed in `settings/ui/tests/acceptance/helpers/language.js` 🦖

**Comment by pascalwengerter** [comment]
> > There's a typo in the german translations. Let's make an rc2 and wait with this PR for that. Objections?
> 
> Nope, sounds good to me. CI is green but the typo would need to be fixed in `settings/ui/tests/acceptance/helpers/language.js` 🦖

Will follow up with an RC.2 (typo fixes and new features) soon

**Comment by kulmann** [comment]
Let's merge. The next rc is just around the corner, but this already unblocks other stuff.

**Pull request merged**
