### PR TITLE
[full-ci] update reva to v2.4.2-0.20220601110755-6b47effc3759

### PR DESCRIPTION
**Pull request by butonic**
update ocis to include https://github.com/cs3org/reva/pull/2888, https://github.com/cs3org/reva/pull/2909, https://github.com/cs3org/reva/pull/2905, https://github.com/cs3org/reva/pull/2903 and https://github.com/cs3org/reva/pull/2907

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/12029/37/1) failed. Further test are cancelled...

**Comment by micbar** [comment]
One unexpected fail, one unexpected pass.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12222/37/6
```
runsh: There were no unexpected failures.
runsh: Total unexpected passed scenarios throughout the test run:
apiSpaces/changeSpaces.feature:138
```
Remove that from expected-failures and this PR should pass CI.

**Comment by butonic** [comment]
fixes https://github.com/owncloud/ocis/issues/3810

**Review by micbar — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
