### PR TITLE
add note to duplicate STORAGE_FRONTEND_PUBLIC_URL

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Review by kulmann — COMMENTED** [review]
Hey wait, when was the storage frontend url removed?

**Comment by wkloucek** [comment]
> Hey wait, when was the storage frontend url removed?

No actually it is there twice! That's why I want to remove one ;-)

**Comment by butonic** [comment]
the gateway service and the frontend service both need access to that env var. when the two services are started in different environments, they both need to announce that and document it. We could clarify that ins the descriptions of the two commands, but we cannot drop any of them. 🤷‍♂️

**Review by butonic — DISMISSED** [review]
the gateway service and the frontend service both need access to that env var. when the two services are started in different environments, they both need to announce that and document it. We could clarify that ins the descriptions of the two commands, but we cannot drop any of them. 🤷‍♂️

**Comment by wkloucek** [comment]
> the gateway service and the frontend service both need access to that env var. when the two services are started in different environments, they both need to announce that and document it. We could clarify that ins the descriptions of the two commands, but we cannot drop any of them.

I did a revert and added notes to the two occurrences. @butonic could you please have a look again?

**Review by kulmann — APPROVED** [review]

**Pull request merged**
