### PR TITLE
Trigger CI

### PR DESCRIPTION
**Pull request by phil-davis**
Because I don't believe the unexpected test failure issue https://github.com/owncloud/core/issues/38657 that is happening in PR #1970 is due to the bump of the commit id.

Let's see what happens in current master.

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/4725/36/7
```
runsh: Total unexpected failed scenarios throughout the test run:
apiTrashbin/trashbinFilesFolders.feature:201
apiTrashbin/trashbinFilesFolders.feature:202
```

That fails in master! How did that happen? I will investigate.

**Comment by phil-davis** [comment]
They were removed from the expected-failures file yesterday by commit https://github.com/owncloud/ocis/commit/26ee19d6fee65f3ddc88484220184c0c29ae27dd

**Comment by refs** [comment]
> @refs how did that commit get on the head of master branch? I don't see a matching PR.

I honestly have no idea how that commit got into master 😅 it was definitely me, but master has branch protection, so I have no clue how that got in

**Comment by phil-davis** [comment]
@refs PR to revert: https://github.com/owncloud/ocis/pull/1973 - please review.

**Comment by phil-davis** [comment]
See #1973 for the fix.

**Pull request closed without merging**
