### PR TITLE
[full-ci] Updated MimeTypes configuration for AppRegistry

### PR DESCRIPTION
**Pull request by gmgigi96**
Follow up of https://github.com/cs3org/reva/pull/2138. This PR changes the type of the mime types config to a list, to ensure the order of mime types from the config.

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-8</strong> failed. The build is cancelled...</summary>

**Comment by wkloucek** [comment]
> Core-API-Tests-ocis-storage-3

@gmgigi96 the CI is failing (https://drone.owncloud.com/owncloud/ocis/7088/21/3)

```
{"level":"error","service":"storage","error":"unable to register services: rgrpc: grpc service appregistry could not be started,: 1 error(s) decoding:\n\n* 'mime_types' expected a map, got 'slice'","time":"2021-10-11T09:30:20Z","message":"error starting the grpc server"}
```

Do you need to update REVA for this to work?

**Comment by wkloucek** [comment]
> > Do you need to update REVA for this to work?
> 
> How can I do? Sorry it's the first time :)

`go get github.com/cs3org/reva@master`

**Comment by labkode** [comment]
@wkloucek we need help here to unblock the tests. Can you take the PR as it is and fix the CI? Thanks

**Comment by gmgigi96** [comment]
> > > @wkloucek we need help here to unblock the tests. Can you take the PR as it is and fix the CI? Thanks
> > 
> > 
> > We are on it
> 
> @labkode @gmgigi96 Will be unblocked by [cs3org/reva#2152](https://github.com/cs3org/reva/pull/2152), this PR needs a REVA update again after the merge.

@wkloucek  I do not understand why this PR is blocked by that reva PR. Could you go ahead with this (if only needs a reva update) and create an other one for only updating reva after that PR will be merged?

**Pull request merged**
