### PR TITLE
Public Link Data Service Command

### PR DESCRIPTION
**Pull request by refs**
## Disclaimer

Pushing for tracking. Beware, replaces to local path.

Dependency tree:

- https://github.com/owncloud/ocis-reva/pull/258
  - https://github.com/cs3org/reva/pull/822

### CODE REVIEW

**Comment by PVince81** [comment]
this does not compile for me:
```
rm -rf config/identifier-registration.yaml
go clean -i ./...
go: github.com/owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7 requires
        github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5: parsing ../../refs/reva/go.mod: open /home/vincent/Private/Work/refs/reva/go.mod: no such file or directory
make: *** [Makefile:62: clean] Error 1
```

**Comment by PVince81** [comment]
Tried to isolate the deps update here https://github.com/owncloud/ocis/pull/328

**Comment by alialqh** [comment]
Aas

**Comment by PVince81** [comment]
Obsolete, we don't need a data service for public links as the public storage provider relays everything to the regular storage provider + regular data service, see https://github.com/cs3org/reva/pull/822#issuecomment-648227346

**Pull request closed without merging**
