### PR TITLE
fix docker-compose.yml for beta9

### PR DESCRIPTION
**Pull request by jnweiger**
Add the fix found in https://github.com/owncloud-docker/compose-playground/pull/44 to the official docker-compose.yml here too.
Also fixes https://github.com/owncloud/ocis/issues/463 for me.

### CODE REVIEW

**Comment by phil-davis** [comment]
I tried performance tests with KONNECTD_TLS set back to '0'. The results are almost identical.

So this setting seems to be having no impact on making things work, or on performance at the levels I was testing (50 to 300 clients uploading)

I actually have no idea why that was changed in https://github.com/owncloud-docker/compose-playground/pull/44

Maybe that change should be removed here. (And in compose-playgorund)

**Comment by individual-it** [comment]
I just copied that setting from somewhere else, it used to be set to `0` but in CI etc. we always set it to `true`, so I done that

**Comment by phil-davis** [comment]
Can @somebody please advise about the setting of `KONNECTD_TLS` and we will do whatever they say :)

**Comment by jnweiger** [comment]
I am removing the KONNECTD_TLS change from this PR. It is not needed do make a login succeed. Only the PROXY setting is needed!

**Review by phil-davis — APPROVED** [review]

**Comment by IljaN** [comment]
Without quotes is the correct one. true/false should also work afair

**Comment by butonic** [comment]
KONNECTD_TLS defaults to false:
https://github.com/owncloud/ocis-konnectd/blob/d38132ebaaf8b8de8f4703a0192660465e27ba2d/pkg/flagset/flagset.go#L270-L276

it must be false to allow konnectd to run behind a proxy that does the tls offloading (which is what ocis-proxy does).

I'll still close this PR in favor of https://github.com/owncloud/ocis/pull/484 because we did more changes to fix sharing.

**Pull request closed without merging**
