### PR TITLE
reduce docker image volume permissions and update alpine

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
- reduce volume permissions
- update alpine base image

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by xoxys** [comment]
Does `710` makes sense? Exec permissions (1) or read permissions (4) without the other will cause issues to read a directory/list files and is therefore useless IMO.

**Comment by wkloucek** [comment]
> sues to read a directory/list files and is therefore useless IMO.

True, I took it from a random folder in my `/var/lib/`. Had another look at all of them and they have either 755 or 700. Therefore I'll change to 700

**Review by xoxys — APPROVED** [review]
As the directory group is `ocis-group` I would use 750 at least but that's maybe just my personal preference.

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-5</strong>](https://drone.owncloud.com/owncloud/ocis/11230/28/1) failed. Further test are cancelled...

**Pull request merged**
