### PR TITLE
starlark format linting

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
Add pipeline to ensure that .drone.star is properly formatted.
Format the .drone.start in order to pass the new CI step.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
Hopefully it just re-formatted `.drone.star` without injecting or taking away anything :)

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/4932
`unhandled index operation function[string] `

That is not a very helpful message - no clue about the line number...

My guess is that there was some single-quoted string that had double-quotes literally in the string. Now the string are surrounded by double-quotes, and literal double-quotes will need to be escaped. Or some other random thing!

**Comment by wkloucek** [comment]
> Hopefully it just re-formatted `.drone.star` without injecting or taking away anything :)

My changes are in these commits:
- https://github.com/owncloud/ocis/pull/2023/commits/9a7ceee45f62306cca5b76ac92c242d4436ffcac
- https://github.com/owncloud/ocis/pull/2023/commits/b01eefb91da53f029346e0c38214486ffb55a22c

> https://drone.owncloud.com/owncloud/ocis/4932
> `unhandled index operation function[string] `
> 
> That is not a very helpful message - no clue about the line number...
> 
> My guess is that there was some single-quoted string that had double-quotes literally in the string. Now the string are surrounded by double-quotes, and literal double-quotes will need to be escaped. Or some other random thing!

and this commit was to fix the invalid starlark, causing the cryptic drone error:
https://github.com/owncloud/ocis/pull/2023/commits/ba58cf890836a9007b9f307585c58167611f7418

**Review by phil-davis — APPROVED** [review]
LGTM now. CI got a "random" error in one of the UI test pipelines. I cancelled and restarted it.

**Pull request merged**
