### PR TITLE
[full-ci] update reva to v1.11.0

### PR DESCRIPTION
**Pull request by fschade**

### CODE REVIEW

**Comment by phil-davis** [comment]
I suggested that we merge #2353 - that should finish CI in about 20 minutes. Then rebase this PR, so that we get a full up-to-date set of CI.

**Comment by fschade** [comment]
> I suggested that we merge #2353 - that should finish CI in about 20 minutes. Then rebase this PR, so that we get a full up-to-date set of CI.

good point, CI canceled

**Review by wkloucek — APPROVED** [review]
Thanks for caring :-)

**Comment by phil-davis** [comment]
@fschade PR #2353 has been merged. Please rebase this and we can get it merged!

**Comment by fschade** [comment]
> @fschade PR #2353 has been merged. Please rebase this and we can get it merged!

done

**Comment by phil-davis** [comment]
I removed the passing tests from expected-failures. That gets CI running again, and it should pass.
```
runsh: Total unexpected passed scenarios throughout the test run:
apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature:22
apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature:23

runsh: Total unexpected passed scenarios throughout the test run:
apiTrashbinRestore/trashbinRestore.feature:309
apiTrashbinRestore/trashbinRestore.feature:310
apiTrashbinRestore/trashbinRestore.feature:478
apiTrashbinRestore/trashbinRestore.feature:479
```
https://drone.owncloud.com/owncloud/ocis/6231/28/6
https://drone.owncloud.com/owncloud/ocis/6231/36/6

There were no newly-passing tests on owncloud storage - so some stuff was fixed for ocis storage but not for owncloud storage. Anyway, testing "owncloud" storage is being removed in PR #2351 (which we can sort out after this PR is merged)

**Review by phil-davis — APPROVED** [review]

**Review by butonic — APPROVED** [review]

**Comment by phil-davis** [comment]
Anyone please feel free to merge this if CI goes green.

**Comment by fschade** [comment]
> Anyone please feel free to merge this if CI goes green.

Sitting in front of it and have my fingers crossed. I merge it one green

**Pull request merged**
