### PR TITLE
[tests-only][full-ci] Make graph api default in test

### PR DESCRIPTION
**Pull request by nabim777**
## Description

In this PR, the graph API is made the default API while testing. Also, this function `isTestingWithGraphApi()` is removed

## Related Issue

- related to https://github.com/owncloud/ocis/issues/8276

## How Has This Been Tested?

- test environment:
- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM

**Review by saw-jan — CHANGES_REQUESTED** [review]
LGTM. Please, check if ocis bump in reva works as well

**Review by SagarGi — COMMENTED** [review]
LGTM :+1:

**Comment by nabim777** [comment]
check in Reva https://github.com/cs3org/reva/pull/4484

**Review by saw-jan — APPROVED** [review]

**Review by amrita-shrestha — APPROVED** [review]

**Pull request merged**
