### PR TITLE
[stable-5.0] chore: adjust env vars so that check-env-var-annotations passes

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #8574 to `stable-5.0`

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/32664/9/6
go vulnerability scan is failing, same as in master.
IMO not related to this PR.

**Comment by mmattel** [comment]
@phil-davis 
Dont we want to add, as commented in the master branch, the corresponding PR's to this backport to make a one shot backport? These PR's are all about the envvars added table. Note, sequence to add is important, oldest first...

#8577 ([docs-only] Fix added envars table) and
#8582 ([docs-only] And more envvars that are added to the table)
**new:**
#8588 ([docs-only] More updates to the added envvar tables)

**Comment by phil-davis** [comment]
The backport of #8586 needs to be done and merged into `stable-5.0`
Then I will rebase this and add the various things that @mmattel has mentioned above.
Some time early tomorrow, hopefully.

**Review by micbar — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport of #8601 has been added.

**Review by dragonchaser — APPROVED** [review]

**Pull request merged**
