### PR TITLE
[tests-only][full-ci]fix flaky test apiSpacesShares/shareSpaces.feature:42

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR fixes the flaky test 

## Related Issue

- Fixes : https://github.com/owncloud/ocis/issues/5544

## Motivation and Context
The test was failing because it searched for the index `group` in the array it was looping through and the index doesn't exist in every loop so the check fails with `Undefined index: group in /drone/src/tests/acceptance/features/bootstrap/SpacesContext.php line 3285` this PR checks if the index is set . 

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by saw-jan — DISMISSED** [review]
LGTM

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
does this only happen in master or also in stable?

**Review by ScharfViktor — APPROVED** [review]
Looks good. Please wait to merge because https://github.com/owncloud/ocis/pull/5542/commits/f2f64fdcae054d920229d463cbf33071ca64376e may be conflicting.

**Comment by SwikritiT** [comment]
> does this only happen in master or also in stable?

only on master because I don't think this test is in a stable branch. @ScharfViktor should we port the tests to stable as well?

**Pull request merged**
