### PR TITLE
fix HTTP1.1 RFC 2616 for 401s

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
fix HTTP1.1 RFC 2616 for bodies when we issue a 401 because of invalid auth

from RFC 2616:
```
        If an origin server receives a request that does not include an
        Expect request-header field with the "100-continue" expectation,
        the request includes a request body, and the server responds
        with a final status code before reading the entire request body
        from the transport connection, then the server SHOULD NOT close
        the transport connection until it has read the entire request,
        or until the client closes the connection. Otherwise, the client
        might not reliably receive the response message. However, this
        requirement is not be construed as preventing a server from
        defending itself against denial-of-service attacks, or from
        badly broken client implementations.
```

see also
- https://github.com/golang/go/blob/d5de62df152baf4de6e9fe81933319b86fd95ae4/src/net/http/server.go#L1089-L1098
- https://www.rfc-editor.org/rfc/rfc7230#section-6.5 Failures and Timeouts
- https://www.rfc-editor.org/rfc/rfc7230#section-6.6 Teardown

## Related Issue
- Fixes https://github.com/owncloud/ocis/issues/5066

## How Has This Been Tested?

- set low access token lifetime (IDP_ACCESS_TOKEN_EXPIRATION=20) and sync a largish folder with the Desktop Client 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by dragotin — APPROVED** [review]
Interesting :-)

**Comment by TheGranadilla** [comment]
Hi.
I believe this fix isnt implemented in OCIS 2.0, since I had this issue on a fresh install.
Debian 11, behind a Nginx Proxy.

Since this bug is tested by using **IDP_ACCESS_TOKEN_EXPIRATION=20**....
I added IDP_ACCESS_TOKEN_EXPIRATION=20000000000 as startup parameter, and no issue anymore.
Is that a good approach?

**Comment by TheGranadilla** [comment]
I had issue when uploading large folders (10Gb, 1000~ files). After like 5 minutes, web interface start to show "unknown error" for files transfert, and client get disconnected, asked to login again. Server side, the error was saying that Access Token was expired (0.9sec, and increasing at each request). I had 0 issue when using The Desktop client, or to upload big files from web ui.

I'll recreate the bug to confirm, and to provide more informations.
_**Maybe** a change I did on my Nginx proxy (caching assets) is in relation with this._

**Comment by micbar** [comment]
Ok, but this issue here was only about the desktop client. So better open a new issue.

**Pull request merged**
