### PR TITLE
[full-ci] Bump reva  & merge unrestrict combined

### PR DESCRIPTION
**Pull request by micbar**
## Description
This combines

- #3624 
- #3629 

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: drone is struggling at the moment! The drone server is getting "random" `Error 1040: Too many connections`

**Review by phil-davis — APPROVED** [review]
LGTM - merge if you like. I am working on a full commit-id bump, but I can easily rebase that if this is merged first.

**Comment by micbar** [comment]
Thanks. I will first merge my reva PR, to revert the concurrent share fetching.

**Comment by micbar** [comment]
Then I will get rid of the replace.

**Comment by phil-davis** [comment]
@micbar I merged #3636 
The core commit id is now up-to-date, so you should have no problem with that. Just rebase this PR (and you won't need to touch `.drone.env`)

**Comment by micbar** [comment]
rebase pushed

**Review by kulmann — APPROVED** [review]

**Comment by kulmann** [comment]
CI is not happy with `downloadById` api tests, see https://drone.owncloud.com/owncloud/ocis/11203/23/6

**Pull request merged**
