### PR TITLE
[Tests-Only] Run web test with parts

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- run web tests using divide and parts system
- currently uses web `run-with-parts` branch to use part system

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/2107

## How Has This Been Tested?
- 🤖 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by individual-it** [comment]
PR in web #5188

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5254/19/6 17 scenarios (17 passed)
That's good - it ran the expected set of just the OCIS smoke test scenarios by default.

**Comment by phil-davis** [comment]
I added `[full-ci]` to the PR title, and pushed commits:
- set skip back to False for regular acceptance tests
- adjust comment about full-ci

We will see what CI does with this now.

**Comment by phil-davis** [comment]
Core API tests are running 10 parts like they did before, no regression there, 
e.g. https://drone.owncloud.com/owncloud/ocis/5256/37/7 `runsh: Total 491 scenarios (286 passed, 205 failed)`

I added in the expected-failures for web, copied from the current list in the web repo. We need that for when full-ci is run. Need to think what to do when just the smoke test scenarios are run...

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5257/42/6
Lots of `webUISharingExternal/federationSharing.feature` fails. We probably need to add some federated server or skip these tests in this case of webUI against an OCIS sevrer. I will look at what happens in `owncloud/web` for this.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5262/39/6
Checking expected failures in /drone/src/tests/acceptance/expected-failures-webUI-on-OCIS-storage-ocisSmokeTest.md

That is correct - it is using the correct expected failures file for the case when running `ocisSmokeTest` scenarios.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/5263/39/6
For full-ci it runs 10 pipelines of webUI tests.
"Checking expected failures in /drone/src/tests/acceptance/expected-failures-webUI-on-OCIS-storage.md"
And uses the correct expected-failures file to check the results.

**Review by phil-davis — APPROVED** [review]

**Comment by micbar** [comment]
@phil-davis @kiranparajuli589 awesome work!

Can we also trigger the full ci by default on tagging? But only if the tag has a format `v1.2.3` like in https://github.com/owncloud/ocis/blob/master/.drone.star#L999 ?

**Comment by phil-davis** [comment]
> Can we also trigger the full ci by default on tagging?

Yes, I updated the list of items to do in issue #2107 to make it clear that full-CI on tag needs to be done.

**Pull request merged**
