### PR TITLE
Merge back Version bump and Changelog for 2.0.0-beta.4

### PR DESCRIPTION
**Pull request by micbar**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>cs3ApiTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/12724/36/1) failed. Further test are cancelled...

**Review by kulmann — CHANGES_REQUESTED** [review]
Could you please delete the changelog file `update-web-beta.4.md`? The actual changelog of web for beta.4 is in `update-web-5.6.0-beta.4.md`. The other one only has some `TBD` content in it and slipped in accidentally I suppose.

**Comment by micbar** [comment]
> Could you please delete the changelog file `update-web-beta.4.md`? The actual changelog of web for beta.4 is in `update-web-5.6.0-beta.4.md`. The other one only has some `TBD` content in it and slipped in accidentally I suppose.

done

**Comment by micbar** [comment]
@kulmann We need to check it there is more to do here because of the resharing feature default value.

**Review by kulmann — APPROVED** [review]

**Pull request merged**
