### PR TITLE
Update JS dependencies

### PR DESCRIPTION
**Pull request by kulmann**
## Description
Upgrade JavaScript dependencies. This requires a `yarn build && make generate` until we have it automated, thus having this hand crafted PR. In particular this PR upgrades axios to 0.21.1 in the embedded bundles.

## Motivation and Context
Fix security warnings

## How Has This Been Tested?
Manually, clicking around in the UIs. Accounts UI will be tested in drone as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
Do we create a changelog for this sort of thing?

**Comment by kulmann** [comment]
> Do we create a changelog for this sort of thing?

We don't do that for dependency upgrades initiated by CI (dependabot/renovate). I'd say we skip that for manual dependency upgrades as well.

**Review by phil-davis — APPROVED** [review]
I rebased to get current CI

**Comment by phil-davis** [comment]
Rebased again - let's see if this PR gets a turn to be merged.

**Pull request merged**
