### PR TITLE
update reva to v1.6.1-0.20210326165326-e8a00d9b2368

### PR DESCRIPTION
**Pull request by C0rby**
* quota querying and tree accounting [cs3org/reva#1405](https://github.com/cs3org/reva/pull/1405)
* Fix webdav file versions endpoint bugs [cs3org/reva#1526](https://github.com/cs3org/reva/pull/1526)
* Fix etag changing only once a second [cs3org/reva#1576](https://github.com/cs3org/reva/pull/1576)
* Trashbin API parity [cs3org/reva#1552](https://github.com/cs3org/reva/pull/1552)
* Signature authentication for public links [cs3org/reva#1590](https://github.com/cs3org/reva/pull/1590)

### CODE REVIEW

**Comment by C0rby** [comment]
This PR might break because we need the "new" web version with the signed public link download feature.

**Review by refs — APPROVED** [review]

**Comment by refs** [comment]
restarting drone, seems like a fluke

**Comment by phil-davis** [comment]
drone had a whole list of pipelines that failed to startup nicely. I rebased and force pushed to get a clean drone run.

**Comment by phil-davis** [comment]
```
runsh: Total unexpected failed scenarios throughout the test run:
apiTrashbin/trashbinFilesFolders.feature:201
apiTrashbin/trashbinFilesFolders.feature:202
runsh: Total unexpected passed scenarios throughout the test run:
apiTrashbin/trashbinRestore.feature:258
apiTrashbin/trashbinRestore.feature:259
apiTrashbin/trashbinRestore.feature:260
apiTrashbin/trashbinRestore.feature:261
apiTrashbin/trashbinRestore.feature:262
apiTrashbin/trashbinRestore.feature:263
apiTrashbin/trashbinRestore.feature:411
apiTrashbin/trashbinRestore.feature:412
apiTrashbin/trashbinRestore.feature:450
apiTrashbin/trashbinRestore.feature:451
```
https://drone.owncloud.com/owncloud/ocis/4358/36/7
I will adjust that with another commit...

**Pull request merged**
