### PR TITLE
Parallel deployment sharing

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
re enables ocis / oc10 parallel deployment tests in CI and updates the deployment example.

It includes:
- fix the parallel deployment after it was broken because of the switch to REVA edge and spaces
- add the sharing functionality so that shares are shared between oCIS and oC10 :partying_face: 

## Related Issue

- Enabled by https://github.com/cs3org/reva/pull/2472
- Closes https://github.com/owncloud/ocis/pull/2951

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-5</strong>](https://drone.owncloud.com/owncloud/ocis/9031/26/1) failed. Further test are cancelled...

**Comment by wkloucek** [comment]
@saw-jan  @phil-davis I also enabled the sharing test suite because sharing across oC10 and oCIS should basicall work, but the test fails https://drone.owncloud.com/owncloud/ocis/9048/36/15:

```
Feature: sharing files and folders
  As a user
  I want to share files/folders with other users
  So that I can give access to my files/folders to others

  Background:                                                                                   # /drone/src/tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature:11
    Given using "oc10" as owncloud selector                                                     # ParallelContext::usingOwncloudSelector()
    And the administrator has set the default folder for received shares to "Shares"            # OccContext::theAdministratorHasSetTheDefaultFolderForReceivedSharesTo()
    And auto-accept shares has been disabled                                                    # FeatureContext::autoAcceptSharesHasBeenDisabled()
    And using OCS API version "1"                                                               # FeatureContext::usingOcsApiVersion()
    And using new DAV path                                                                      # FeatureContext::usingOldOrNewDavPath()
    And user "Alice" has been created with default attributes and without skeleton files        # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Brian" has been created with default attributes and without skeleton files        # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has uploaded file with content "ownCloud test text file" to "textfile.txt" # FeatureContext::userHasUploadedAFileWithContentTo()

  Scenario: accept a pending share                                                                # /drone/src/tests/parallelDeployAcceptance/features/apiShareManagement/acceptShares.feature:22
    Given user "Alice" has shared folder "/textfile.txt" with user "Brian"                        # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And using "ocis" as owncloud selector                                                         # ParallelContext::usingOwncloudSelector()
    When user "Brian" accepts share "/textfile.txt" offered by user "Alice" using the sharing API # FeatureContext::userReactsToShareOfferedBy()
      Sharing::userReactsToShareOfferedBy could not find share /textfile.txt, offered by Alice to Brian
      Failed asserting that null is not null.
    Then the OCS status code should be "100"                                                      # OCSContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"                                                      # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the sharing API should report to user "Brian" that these shares are in the accepted state # FeatureContext::assertSharesOfUserAreInState()
      | path                 |
      | /Shares/textfile.txt |
```

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/9048/37/15
"23 scenarios (23 passed)" - that's great.

For sharing, `apiShareManagement/acceptShares.feature:22` was already in `tests/parallelDeployAcceptance/expected-failures-API.md` so we could look into that after merging this PR.

**Review by phil-davis — APPROVED** [review]
LGTM - I did a full-ci run with this code rebased to current master in draft PR #3067 and that confirms that the full-ci functionality is still working OK with these drone changes.

**Comment by wkloucek** [comment]
> LGTM - I did a full-ci run with this code rebased to current master in draft PR #3067 and that confirms that the full-ci functionality is still working OK with these drone changes.

Thanks for looking into this! 

> For sharing, `apiShareManagement/acceptShares.feature:22` was already in `tests/parallelDeployAcceptance/expected-failures-API.md` so we could look into that after merging this PR.

Sharing wasn't implemented before this PR, therefore I expected that that I can remove the test from the expected failure file. I'll link to https://github.com/owncloud/ocis/issues/2387 to track further progress

**Pull request merged**
