### PR TITLE
[Tests-Only] Optimize the test Suite

### PR DESCRIPTION
**Pull request by micbar**
# Optimize the test Suite

1) Split Ui Tests in 4 parts
2) Do not run acceptance tests on merge commits

### CODE REVIEW

**Comment by phil-davis** [comment]
The starlark looks OK. But there were test fails in https://drone.owncloud.com/owncloud/ocis/228/25/7 phoenixWebUI2 pipeline. 
I restarted drone to see if this is an intermittent test problem.

**Comment by micbar** [comment]
Still the same random errors with messed up user accounts. @individual-it is working on it.

**Comment by micbar** [comment]
@phil-davis Seems something went wrong.

Part 3 is too long now.
You can see it by the number of lines.
Something went wrong with the split.

**Comment by individual-it** [comment]
`webUIAccount` has just a single test

**Review by kulmann — APPROVED** [review]
🚀

**Pull request merged**
