### PR TITLE
[full-ci] Update web to 4.0.0

### PR DESCRIPTION
**Pull request by kulmann**
Update web to release 4.0.0

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - I adjusted the expected-failures. All the needed adjustments were either due to adjustments of test scenarios in web, new test scenarios in web or tests that are now passing. They all looked like good and reasonable changes.

**Review by fschade — APPROVED** [review]
LGTM, lets wait for the ci then  🚀

**Comment by phil-davis** [comment]
One of the web test pipelines ran for 2 hours and drone auto-cancelled the pipeline. The drone agent seemed to be running very slowly - super frustrating. I have stopped the oldest drone agents, so they will not be given pipelines. I restarted CI. Let's see if we do better this time.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
I am fixing up the drone starlark to split web pipelines into more parts... (some are taking 2 hours!

**Pull request merged**
