### PR TITLE
[full-ci][tests-only]Change web branch to master

### PR DESCRIPTION
**Pull request by SwikritiT**
PR: https://github.com/owncloud/ocis/pull/5873 change the branch of the web which branch got deleted after the merge of this PR https://github.com/owncloud/web/pull/8658
So this PR changes the branch to master.
changing the commit id to the test fix https://github.com/owncloud/web/commit/ed2c175142de407463ff2664c76ba52e31b4ecae

### CODE REVIEW

**Comment by ownclouders** [comment]
E2E tests failed: https://drone.owncloud.com/owncloud/ocis/20714/86/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/20714/tracing/admin-creates-user-admin-2023-3-23-04-24-16.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/20714/tracing/users-can-navigate-web-via-tiles-alice-2023-3-23-04-37-09.zip 


</p></details>

**Comment by saw-jan** [comment]
```bash
locator.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('[data-test-id="create-user-btn"]')
============================================================
```
Looks like it needs a new web RC

**Comment by SwikritiT** [comment]
The `changeNotificationTest` branch in the web has been restored for now so that the PRs don't fail in CI. We might need to release the web to be able to run through master branch.

**Comment by ScharfViktor** [comment]
I get confused about this all the time and I would have some of instruction for that. I think we should to find an easier way to change e2e in ocis without web bump and create instructions to do so. 

In the case where ocis changes break the e2e test, I see two ways: 
first: 
- skip specific e2e scenario in the `drone.star` (ocis repo) - to make ocis CI green - I know how to do it.
- after merging ocis branch-> change OCIS_COMMITID in the `drone.env` (web repo) and fix test
- with next web beta-release in ocis we delete all skip tests

second (without web beta-release): 
-  create web PR from current `WEB_COMMITID` (see in `drone.env` in the ocis) and change  e2e test (web CI is red because backend need be changed) 
- in the ocis change to new `WEB_COMMITID` and `WEB_BRANCH=fixtest` (ocis CI is green - merge PR to master and get new `OCIS_COMMITID`)
- change `OCIS_COMMITID` in the web -  merge PR to master and get new `WEB_COMMITID`
- bump new `WEB_COMMITID` to ocis 

If I'm wrong, please correct me.

**Comment by ScharfViktor** [comment]
I created web beta-release. Thanks @fschade for help

here is guid how do it  to don't forget it (I put it in correct place when I found it)

- go to IDE - web repository
- `git checkout release-7.0.0`
- `git rebase -i master`

actions:
go to `changelog` folder
rename last folder(by time)- use current time like `7.0.0_2023-03-23`
move all files (except `.keep`) from unreleased folder to `7.0.0_2023-03-23`

change `OCIS_COMMITID` in the .drone.env
change version in the package.json  `"version": 7.0.0-rc.23"`
change version in the sonar-project.properties `sonar.projectVersion=7.0.0-rc.23`

- `git add .`
- `git commit -m "chore: prepare release-7.0.0-rc.23"`
- `git push origin release-7.0.0 --force-with-lease`

- `git checkout -b merge-back-7.0.0-rc.23`
- `git rebase -i release-7.0.0`

actions:
move all files from folder changelog/7.0.0_2023-03-23 to folder unreleased
delete folder 7.0.0_2023-03-23 

- `git add .` 
- `git commit -m "chore: move changelog items back to unreleased"`
- `git push origin merge-back-7.0.0-rc.23`

actions:
- go to https://github.com/owncloud/web/releases -> press button `draft a new release`
- create new tag - (!Important - set checkbox as "Set as pre-release") see screen: 
Screenshot 2023-03-23 at 11 15 46

Bump ocis: 
- change `WEB_COMMITID` in the drone.env
- change `WEB_ASSETS_VERSION = v7.0.0-rc.23` in the "services/web/Makefile"

**Pull request merged**
