### PR TITLE
[tests-only] [full-ci] latest core commit id bump

### PR DESCRIPTION
**Pull request by sakshamgurung**
## Description

Latest core commit id bump [Nov 17 2021]
## Related Issue

- PR for https://github.com/owncloud/QA/issues/699

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
@sakshamgurung please bump again to the latest commit id in core.

I just merged core PR https://github.com/owncloud/core/pull/39497 and it will be good to know if that test code passes here in oCIS.

**Comment by phil-davis** [comment]
I have a core fix for the `trim` error. I will make a PR...

**Comment by sakshamgurung** [comment]
> I have a core fix for the `trim` error. PR [owncloud/core#39498](https://github.com/owncloud/core/pull/39498)

I will wait for it to merge

**Comment by phil-davis** [comment]
I bumped again to the latest core commit id. Let's see what CI says.

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/39503 skips some app password test scenarios. We need to bump again after that is merged.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
