### PR TITLE
[tests-only] [full-ci] added breadcrumb issued scenario into the expected failures

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- updated expected to failures file

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/2944

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
How can this ever have worked? The acceptance test is ~13 months old

**Comment by kiranparajuli589** [comment]
> How can this ever have worked? The acceptance test is ~13 months old

the scenario is only run for the nightly build (not included in the normal builds)

you can see the failing builds in the related issue

**Comment by phil-davis** [comment]
I thought that we run [full-ci] whenever we update the web commit id, and when we update web into oCIS, and when we update the latest reva into oCIS. So we should have had regular full-ci runs of the web nightwatch tests.

So why is this only noticed just now?
Has it only started failing recently?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/8652/33/9
```
    Then breadcrumb for folder "0" should be displayed on the webUI
√ Element <#new-file-menu-btn> was visible after 35 milliseconds.
Timed out while waiting for element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'0')]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10015ms)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"ae4531e1d244a27962b2243a19d7ed19","status":0,"value":[]}
       at Proxy.isSideBarOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at assertBreadcrumbIsDisplayedFor (/srv/app/web/tests/acceptance/stepDefinitions/filesContext.js:780:22)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
undefinedTimed out while waiting for element <//button[@aria-label="Open sidebar to view details"]/ancestor::div//span[@class="oc-breadcrumb-drop-label-text" and text()='0']> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10011ms)
undefinedFailed [strictEqual]: (Resource //nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'0')] expected to be visible but is not visible .) - expected "true" but got: "false" (0ms)
undefined    ✖ failed
      Error while running "strictEqual" command: Failed [strictEqual]: (Resource //nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'0')] expected to be visible but is not visible .) - expected "true" but got: "false" (0ms)
          at assertBreadcrumbIsDisplayedFor (/srv/app/web/tests/acceptance/stepDefinitions/filesContext.js:797:24)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

That scenario does fail. I suppose it started failing in some "recent" oCIS change that was merged in a PR that did not run full-ci.

IMO we need to merge this to get full-ci green, and also look into the issue separately. When the cause of the issue and fix (either to back-end code, web code or test code) is ready, then `webUIFiles/breadcrumb.feature:50` will get removed from expected-failures.

Adding to expected-failures like this is not ideal. But IMO it is the process that happens when "something" gets into master that causes a test to start failing.

**Comment by individual-it** [comment]
@kiranparajuli589 please git bisect to find out when it started

**Comment by kiranparajuli589** [comment]
currently blocked due to  #2952 (cannot build over past commits)

**Comment by kiranparajuli589** [comment]
started from https://github.com/owncloud/ocis/pull/2739/

scenario line addition to the expected failures are already inserted inside from https://github.com/owncloud/ocis/pull/2739/files

**Pull request closed without merging**
