### PR TITLE
bump libre graph api

### PR DESCRIPTION
**Pull request by butonic**
bumping the libregraph api ... had some unexpected test failures. please double check the tests.

### CODE REVIEW

**Comment by phil-davis** [comment]
@ishabaral @nirajacharya2 please get someone to have a look at the failing API tests.
I think that the updated libre-graph-api is now returning some extra data etc., and test expectations will need to be updated.

**Comment by saw-jan** [comment]
>E2e tests are also failing because of that.

webUI actions are failing so I think that means, web also need to accomodate this new change

**Comment by rhafer** [comment]
> Looks like `displayName` is now required when:
> 
>     1. changing language
> 
>     2. changing username
> 
>     3. disabling users
> 
> 
> ```
> {"error":{"code":"invalidRequest","innererror":{"date":"2024-08-15T15:44:42Z","request-id":"apiGraphUserGroup/addUserToGroup.feature:281-285"},"message":"invalid request body: no value given for required property displayName"}}
> ```
> 
> E2e tests are also failing because of that.

That shouldn't be the case. I think this is a bug in the generated libregraph code.

**Review by rhafer — APPROVED** [review]
lgtm

**Comment by saw-jan** [comment]
@butonic 
you might have to rebase the PR with latest master. These e2e tests should not be running in ocis:
```
1) Scenario: access token renewal via iframe (attempt 2) # tests/e2e/cucumber/features/oidc/iframeTokenRenewal.feature:8
2) Scenario: access token renewal via refresh token (attempt 2) # tests/e2e/cucumber/features/oidc/refreshToken.feature:8
```
recent web bump: https://github.com/owncloud/ocis/pull/9832

**Comment by butonic** [comment]
@dragonchaser can we ignore the sonarcloud bug:
[copylocks: return copies lock value: github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1.User contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex](https://sonarcloud.io/project/issues?pullRequest=9822&open=AZFqn2crXxKdAA1Oa6Aj&id=owncloud_ocis)

**Comment by butonic** [comment]
ignoring the sonarcloud bug

**Pull request merged**
