### PR TITLE
quickfix for thumbnail generation when using different idp

### PR DESCRIPTION
**Pull request by C0rby**
Implemented a quickfix for generating thumbnails in a setup when a different idp than konnectd is used.
This is just a quick fix and the thumbnail service will be refactored in the near future.

### CODE REVIEW

**Review by wkloucek — APPROVED** [review]
Works with a Keycloak setup

**Comment by butonic** [comment]
@C0rby the protobuf tests now render with two spaces? wtf https://drone.owncloud.com/owncloud/ocis/3356/13/6

**Comment by C0rby** [comment]
> @C0rby the protobuf tests now render with two spaces? wtf https://drone.owncloud.com/owncloud/ocis/3356/13/6

Yeah WTF...
Anyway I deleted that test file. I don't see any value provided by that

**Comment by wkloucek** [comment]
@C0rby I think we should try to get it merged before 1.2.0 release. What do you think?

**Comment by C0rby** [comment]
Yes, I agree

**Pull request merged**
