### PR TITLE
quickfix root dockerfile to unblock docker based acceptance tests

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
applies a quick fix the Dockerfile in the repository root in order to unblock docker based acceptance test.

### CODE REVIEW

**Review by individual-it — COMMENTED** [review]
with that change the build fails for me with 
grafik

**Comment by wkloucek** [comment]
> with that change the build fails for me with grafik

looks like you vendor the go dependencies of oCIS and they are not up to date. Running `go mod vendor` to refresh the vendored dependencies should do the trick

**Comment by rhafer** [comment]
> with that change the build fails for me with

Can you check what's inside the `vendor` directory?

Actually it might just contain stuff from php's `composer` that interferes with with `go build`. I've seen that before. If that's the case you can try `rm -rf vendor` and rerun.

**Review by individual-it — APPROVED** [review]
after cleaning up the tests run

**Pull request merged**
