### PR TITLE
[tests-only][full-ci]Adjust expected failure for `apiWebdavProperties2` suites

### PR DESCRIPTION
**Pull request by amrita-shrestha**
## Description
This PR adjusts the expected failures files after the tests related to the spaces webDAV added in apiWebdavProperties2 suites.

includes expected failure related to:
- https://github.com/owncloud/core/pull/39724
- https://github.com/owncloud/core/pull/39727

## Related Issue
- https://github.com/owncloud/ocis/issues/3035
- https://github.com/owncloud/core/pull/39720
- https://github.com/owncloud/QA/issues/715

## How Has This Been Tested?
- CI
- https://github.com/owncloud/core/pull/39720/commits

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-1</strong>](https://drone.owncloud.com/owncloud/ocis/8970/22/1) failed. Further test are cancelled...

**Review by kiranparajuli589 — COMMENTED** [review]
looks good :+1:

**Comment by kiranparajuli589** [comment]
@amrita-shrestha can we bump up to this PR in core https://github.com/owncloud/core/pull/39727?

**Review by phil-davis — APPROVED** [review]
Note: the fails for https://github.com/owncloud/ocis/issues/3047 will change again after core https://github.com/owncloud/core/pull/39728 is merged and we bump again. That is fine.

**Pull request merged**
