### PR TITLE
[full-ci] update web to v5.7.0-rc.11

### PR DESCRIPTION
**Pull request by kulmann**
updating web to v5.7.0-rc.11 for the upcoming oCIS v2.0.0-beta.8 release.

### CODE REVIEW

**Comment by phil-davis** [comment]
CI failed because of https://github.com/owncloud/web/issues/6798#issuecomment-1237274048
https://drone.owncloud.com/owncloud/ocis/15218/70/14

I restarted again!

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/15219/70/14
```
Checking expected failures in //drone/src/tests/acceptance/expected-failures-webUI-on-OCIS-storage.md
Error: Scenario webUITextEditor/textFile.feature:21 failed but was not expected to fail.
Error: Scenario webUITextEditor/textFile.feature:29 failed but was not expected to fail.
runsh: Total unexpected failed scenarios throughout the test run:
webUITextEditor/textFile.feature:21
webUITextEditor/textFile.feature:29
```
These failed again - why is that? I will restart and we need to investigate.

**Comment by SagarGi** [comment]
@phil-davis failed on nightly too. https://drone.owncloud.com/owncloud/ocis/15221/69/14

**Comment by phil-davis** [comment]
> @phil-davis failed on nightly too. https://drone.owncloud.com/owncloud/ocis/15221/69/14

That is "good" - at least I know that the problem is not introduced by this PR! But it seems to be happening a lot now. It will be good to investigate again in issue #6798 and see if we can reproduce this somehow.

**Comment by micbar** [comment]
Needs https://github.com/cs3org/reva/pull/3195 and a reva update

**Comment by kulmann** [comment]
Rebased, since reva edge was bumped approx. an hour ago.

**Review by micbar — APPROVED** [review]
uh, big regression with the `&` character

**Pull request merged**
