### PR TITLE
Make Phoenix's command parse a list of available apps

### PR DESCRIPTION
**Pull request by refs**
Depends on https://github.com/owncloud/ocis-phoenix/pull/28

Usage:

`ocis phoenix --web-config-apps "files, markdown-editor, pdf-viewer, draw-io"`

### CODE REVIEW

**Comment by refs** [comment]
Builds will likely fail since it depends on https://github.com/owncloud/ocis-phoenix/pull/28 to be merged, as I was using a local version

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/phoenix.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4824379&bid=16034953)

**Comment by labkode** [comment]
That's super cool

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/phoenix.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis/pullRequest?prid=4824379&bid=16034953)

**Pull request merged**
