### PR TITLE
ignore local changelog changes

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
- [x] ignore local changelog changes
- [ ] force add CI changelog changes

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by wkloucek** [comment]
@micbar We first need to check if the push step in the CI ignores the gitignore...

**Comment by wkloucek** [comment]
the used plugin doesn't have an option to do force add...

It has the needed code but it isn't hooked up at all:

https://github.com/drone-plugins/drone-git-action/blob/efde5f72d26d72a2478b6a3d8efa3e0e2c5b6769/repo/commit.go#L9-L28

**Comment by micbar** [comment]
we can do something different, we can checkout always the tip of the master branch before generating the changelog

**Comment by wkloucek** [comment]
> we can do something different, we can checko

you mean before commiting the generated changelog? That should be already covered by the "plugins/git-action" as I remember when I look at the code the last time.

**Comment by micbar** [comment]
ok. let us just merge the ignore rule.

**Comment by wkloucek** [comment]
> ok. let us just merge the ignore rule.

Then CI won't update the cangelog anymore :-(

**Pull request closed without merging**
