### PR TITLE
add an expiration to the space member permissions

### PR DESCRIPTION
**Pull request by C0rby**
This PR changes the structure of the space permissions and adds an optional expiration date.
Now the `permissions` array holds one object per grant instead of holding one object per role like before.

### CODE REVIEW

**Comment by C0rby** [comment]
The UI needs some changes now that the permissions structure is different. Also the datepicker for the expiration date is shown but the value is not sent.

**Comment by micbar** [comment]
I am fine with merging backend and frontend updates independently.

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpacesShares-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/18489/46/1) failed. Further test are cancelled...

**Comment by C0rby** [comment]
> I am fine with merging backend and frontend updates independently.

This would break the spaces members since listing won't work properly without the proper changes.
Required for this PR are:
- https://github.com/cs3org/reva/pull/3628
- https://github.com/owncloud/web/pull/8320
  - https://github.com/owncloud/owncloud-sdk/pull/1204

**Comment by micbar** [comment]
My point was, that it would be ok if the ocis master / web combination is broken for some hours.

**Comment by micbar** [comment]
@C0rby Web bump was successful #5507

**Pull request merged**
