### PR TITLE
[tests-only] [full-ci] Remove webUIPreview/imageMediaViewer.feature:56

### PR DESCRIPTION
**Pull request by refs**
## Related Issue

- Fixes [#5840](https://github.com/owncloud/web/issues/5840)

## Motivation and Context

We fixed this scenario on #2557 

## How Has This Been Tested?
CI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Review by pascalwengerter — APPROVED** [review]
LGTM. @phil-davis could you please advise your team to be more careful about simply adding things to expected failures? This one should in retrospect have raised quite a bit of attention in the web/oCIS team since the underlying issue was quite grave

**Comment by phil-davis** [comment]
How did the add of that scenario get merged to master anyway? The test must have failed in CI? Was there some overlap of multiple PRs that were not all rebased after each other?

**Comment by pascalwengerter** [comment]
> How did the add of that scenario get merged to master anyway? The test must have failed in CI? Was there some overlap of multiple PRs that were not all rebased after each other?

You approved it when the commit IDs got updated recently since the test failed, yes. But just adding it to the expected failures "since it fails" is IMHO not a valid procedure

**Comment by phil-davis** [comment]
> You approved it when the commit IDs got updated recently since the test failed, yes. But just adding it to the expected failures "since it fails" is IMHO not a valid procedure

There was a linked issue. So anyone could then see the issue and work on it.

What I don't understand is that the test failed in the CI  of the commit-id-bump PR, but then the test was not failing after the PR was merged to master. Somehow I broke CI by merging a green PR.

**Pull request merged**
