### PR TITLE
[full-ci] Increase UI tests pipelines

### PR DESCRIPTION
**Pull request by saw-jan**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by pascalwengerter — CHANGES_REQUESTED** [review]
I don't think this is the way to go. It's not sustainable, we need to figure out how to speed up the tests inside `web`

**Comment by pascalwengerter** [comment]
Also, @phil-davis this is the third time in the last 24h that your team has made multiple PRs with identical changes in the same repo. Please coordinate this better

**Comment by phil-davis** [comment]
@saw-jan for now, I did this in #2353 because we are having trouble today just to get CI finished for that PR.

And we will have to look into the detail of the tests tomorrow.

**Comment by saw-jan** [comment]
Yeah, I noticed now.
I just took it because the issue was in our sprint

**Comment by phil-davis** [comment]
> Also, @phil-davis this is the third time in the last 24h that your team has made multiple PRs with identical changes in the same repo. Please coordinate this better

yes, sure. This one happened because of the struggle to get CI  finished for #2353 - I made a quick push to that PR only minutes ago to get it going in real-time. So I didn't have the chance yet to communicate that with others. And @saw-jan made this PR almost at the same time.

**Pull request closed without merging**
