### PR TITLE
[tests-only][full-ci]Add test to propfind the size of a folder

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR adds the tests to `PROPFIND` a folder with files in then and checks the size of the folder.

## Related Issue

- Test for: https://github.com/owncloud/ocis/issues/6215

## Motivation and Context
The bug https://github.com/owncloud/ocis/issues/6215 wasn't covered by the test yet, so this PR adds the test case .

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
@ScharfViktor @micbar OK  to merge?
It passes on drone CI. But I notice that some developers have reported varying results - maybe there is some "flaky" issue in a cache somewhere or?

**Comment by SwikritiT** [comment]
> @ScharfViktor @micbar OK to merge? It passes on drone CI. But I notice that some developers have reported varying results - maybe there is some "flaky" issue in a cache somewhere or?

maybe it was fixed by https://github.com/cs3org/reva/pull/3845 
reva bumped in ocis by https://github.com/owncloud/ocis/pull/6232

I tried running the test multiple times locally and it passes

**Comment by ScharfViktor** [comment]
> > @ScharfViktor @micbar OK to merge? It passes on drone CI. But I notice that some developers have reported varying results - maybe there is some "flaky" issue in a cache somewhere or?
> 
> maybe it was fixed by [cs3org/reva#3845](https://github.com/cs3org/reva/pull/3845) ? reva bumped in ocis by #6232
> 
> I tried running the test multiple times locally and it passes

then we should close #https://github.com/owncloud/ocis/issues/6215 and merge this PR

**Review by ScharfViktor — APPROVED** [review]

**Pull request merged**
