### PR TITLE
bump reva

### PR DESCRIPTION
**Pull request by dragonchaser**
Bugfix: Prevent copying a file to a parent folder

When copying a file to its parent folder, the file would be copied onto the parent folder, moving the parent to the trash-bin.

https://github.com/owncloud/ocis/issues/1230

### CODE REVIEW

**Comment by saw-jan** [comment]
Findings:
1. Some test failed because the expecetd statuscode was different (should be `409` now) - can be fixed in the test scenarios
2. **Cannot** do MOVE using `old`/`new` webdav endpoints in the `Shares` - (works from spaces) :x:

    `demo` is a sharee here:
    ```bash
    curl -XMOVE "https://localhost:9200/remote.php/webdav/Shares/parent" \                                                                
    -H"Destination: https://localhost:9200/remote.php/webdav/Shares/sharedParent" \        
    -udemo:demo -vk

    < HTTP/1.1 404 Not Found
    ```
    ```bash
    curl -XMOVE "https://localhost:9200/remote.php/dav/files/demo/Shares/parent" \                                                                
    -H"Destination: https://localhost:9200/remote.php/dav/files/demo/Shares/sharedParent" \        
    -udemo:demo -vk

    < HTTP/1.1 404 Not Found
    ```

**Comment by saw-jan** [comment]
I get the 404 from this line
https://github.com/owncloud/ocis/blob/2bd0191bbe9a56fb47032f92398a3a627aa1265a/vendor/github.com/cs3org/reva/v2/internal/http/services/owncloud/ocdav/move.go#L165-L169

**Comment by dragonchaser** [comment]
This is weird, this is not supposed to happen, almost the same code is running in line 144 of move.go....

**Comment by saw-jan** [comment]
> This is weird, this is not supposed to happen, almost the same code is running in line 144 of move.go....

Yeah, only difference is that the `src` and `dst` are exchanged. May be `client.Stat(` is not handling them properly while using old/new webdav

**Comment by dragonchaser** [comment]
@saw-jan yes but the same code is running in copy.go properly....

**Comment by dragonchaser** [comment]
@saw-jan https://github.com/cs3org/reva/pull/4582 @aduffeck saw the issue :)

**Comment by saw-jan** [comment]
https://drone.owncloud.com/owncloud/ocis/32956/18/6
COPY between spaces now give `409`. It should be possible to COPY cross spaces
```feature
Scenario Outline: user copies a file from a project space with a different role to a project space with the manager role              # /drone/src/tests/acceptance/features/apiSpacesShares/copySpaces.feature:47
    Given the administrator has assigned the role "Space Admin" to user "Brian" using the Graph API                                     # GraphContext::theAdministratorHasGivenTheRoleUsingTheGraphApi()
    And user "Brian" has created a space "Project1" with the default quota using the Graph API                                          # SpacesContext::theUserHasCreatedASpaceByDefaultUsingTheGraphApi()
    And user "Brian" has created a space "Project2" with the default quota using the Graph API                                          # SpacesContext::theUserHasCreatedASpaceByDefaultUsingTheGraphApi()
    And user "Brian" has uploaded a file inside space "Project1" with content "Project1 content" to "/project1.txt"                     # SpacesContext::userHasUploadedFile()
    And user "Brian" has shared a space "Project2" with settings:                                                                       # SpacesContext::userHasSharedSpace()
      | shareWith | Alice     |
      | role      | <to_role> |
    And user "Brian" has shared a space "Project1" with settings:                                                                       # SpacesContext::userHasSharedSpace()
      | shareWith | Alice       |
      | role      | <from_role> |
    When user "Alice" copies file "/project1.txt" from space "Project1" to "/project1.txt" inside space "Project2" using the WebDAV API # SpacesContext::userCopiesFileFromAndToSpaceBetweenSpaces()
    Then the HTTP status code should be "201"                                                                                           # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And for user "Alice" the space "Project2" should contain these entries:                                                             # SpacesContext::userTheSpaceShouldContainEntries()
      | /project1.txt |
    And for user "Alice" the content of the file "/project1.txt" of the space "Project2" should be "Project1 content"                   # SpacesContext::checkFileContent()

    Examples:
      | from_role | to_role |
      | manager   | manager |
        Failed step: Then the HTTP status code should be "201"
        HTTP status code 409 is not the expected value 201
        Failed asserting that 409 matches expected '201'.
```

**Comment by saw-jan** [comment]
These two tests also need statuscode adjustment:
```bash
apiSpacesDavOperation/moveByFileId.feature:741
apiSpacesDavOperation/moveByFileId.feature:742
```

**Review by 2403905 — APPROVED** [review]

**Pull request merged**
