### PR TITLE
[full-ci] Try acceptence tests

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
Remove testsuite dependencies from package.json files and pull it from Web

## Related Issue

- Needs https://github.com/owncloud/web/pull/6113

## Motivation and Context
Make version bumps of testsuite dependencies in one place

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>accountsUITests</strong>](https://drone.owncloud.com/owncloud/ocis/8224/34/1) failed. Further test are cancelled...

**Comment by pascalwengerter** [comment]
@individual-it could I ask you to take a look here? We got pretty far but couldn't manage to get nightwatch to accept being called from a different path IIRC

**Comment by individual-it** [comment]
Note for myself: The goal here is to remove all the acceptance test dependencies from accounts&settings service UIs since we're copying&installing them from web anyways

**Comment by phil-davis** [comment]
@individual-it this is in the backlog project - should it stay there, or move to the new QA sprint?

**Comment by individual-it** [comment]
I don't think we will be able to do this soon, we are pretty busy

**Comment by butonic** [comment]
closing for now

**Pull request closed without merging**
