### PR TITLE
[full-ci] chore: bump oC Web to v7.0.0-rc.30

### PR DESCRIPTION
**Pull request by kulmann**
bump oC Web to v7.0.0-rc.30

### CODE REVIEW

**Review by JammingBen — APPROVED** [review]

**Comment by micbar** [comment]
@kulmann This has the fix for "open In Web"?

**Comment by ownclouders** [comment]
E2E tests failed: https://drone.owncloud.com/owncloud/ocis/21392/88/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/21392/tracing/folder-alice-2023-4-17-01-00-49.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/21392/tracing/folder-brian-2023-4-17-01-01-03.zip 


</p></details>

**Comment by kulmann** [comment]
> @kulmann did you rebase? We fixed the ocis linting pipelines on friday.

I created the branch on top of `a08ea5647cd5da1b8b542717c3ef2116176ff8a6` from today 07:12:25. So a rebase shouldn't be necessary o_O

**Comment by ScharfViktor** [comment]
> E2E tests failed: https://drone.owncloud.com/owncloud/ocis/21392/88/1
> 
> 💥 To see the trace, please open the link in the console ...

fix here https://github.com/owncloud/web/pull/8835 
can we bring it to ocis if CI will be green?

**Comment by kulmann** [comment]
> E2E tests failed: https://drone.owncloud.com/owncloud/ocis/21392/88/1
> 
> 💥 To see the trace, please open the link in the console ...

@ScharfViktor I re-ran the CI to check if this test is flaky. Unfortunately it looks like that 🙈 Could you check this please?
`share.ocis.feature:9` failed in `And "Brian" should not see the version of the file # tests/e2e/cucumber/steps/ui/resources.ts:347` with `page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"`

**Comment by ScharfViktor** [comment]
> @ScharfViktor I re-ran the CI to check if this test is flaky. Unfortunately it looks like that 🙈 Could you check this please? `share.ocis.feature:9` failed in `And "Brian" should not see the version of the file # tests/e2e/cucumber/steps/ui/resources.ts:347` with `page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"`

Yes, I know. it's flaky. I fixed it here https://github.com/owncloud/web/pull/8835
see comment above

**Pull request merged**
