### PR TITLE
Unskip settings service acceptance tests

### LINKED ISSUE #4056: Unskip setting service UI/acceptance tests
I guess this happened around the time the accounts service was removed. We've been flying blind regarding the settings service UI ever since

https://github.com/owncloud/ocis/blob/a464a861284905f4da00f583b16c4424d6480a43/.drone.star#L100

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Reactivate currently skipped settings service (perhaps needs more work than a boolean switch)

Fixes #4056

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>settingsUITests</strong>](https://drone.owncloud.com/owncloud/ocis/12894/52/1) failed. Further test are cancelled...

**Review by rhafer — APPROVED** [review]
:man_facepalming:

**Comment by pascalwengerter** [comment]
Somehow never finishes building the JS assets for `arm`? https://drone.owncloud.com/owncloud/ocis/12903/57/3

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12905/20/3
`Error response from daemon: No such image: owncloudci/golang:1.18`
drone + docker is seriously annoying. The agents often do not find docker images that exist, and have existed for ages.

Restarted.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12906/57/3
some error in generate nodejs
Restarted

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12907/57/3
This time it got all the way to docker-arm and generate nodejs failed there.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12908/53/7
```
+ git clone -b $CORE_BRANCH --single-branch --no-tags https://github.com/owncloud/core.git /srv/app/testrunner
Cloning into '/srv/app/testrunner'...
error: RPC failed; curl 55 OpenSSL SSL_write: Connection reset by peer, errno 104
error: 6436 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

This is complete rubbish - the drone environment+network+docker+github gets too many "hiccups". And I have no idea how to improve it so that a whole set of pipelines can actually pass.

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
opened a new issue for caching also the core repo https://github.com/owncloud/ocis/issues/4059

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/12912/57/3
docker-arm generate nodejs seems to always fail.
That needs someone to investigate why.

**Pull request merged**
