### PR TITLE
[WIP] reva meta api

### PR DESCRIPTION
**Pull request by fschade**
Added support for fileid to filepath in [ocdav meta api](https://doc.owncloud.com/server/next/developer_manual/webdav_api/meta.html), check fork

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>settingsUITests</strong>](https://drone.owncloud.com/owncloud/ocis/8143/35/1) failed. Further test are cancelled...

**Comment by micbar** [comment]
@fschade how should we continue here?

**Comment by fschade** [comment]
> @fschade how should we continue here?

Just need some time :( I hope to be able to jump back after I managed my other prs

**Comment by micbar** [comment]
@fschade Still needed?

**Comment by fschade** [comment]
@micbar hea it’s needed for the url resource fallback where we need to resolve id to path. But it needs a rebase and different target branch. Let’s see if I find time tomorrow.

**Comment by fschade** [comment]
i close this here for now and create a updated pr

**Pull request closed without merging**
