### PR TITLE
[WIP] Enable accounts ui tests

### PR DESCRIPTION
**Pull request by micbar**

### CODE REVIEW

**Comment by micbar** [comment]
@kulmann I removed the pdf viewer

**Comment by kulmann** [comment]
I fixed some selector issues in the UI tests.

**Review by kulmann — APPROVED** [review]
👍

**Comment by kulmann** [comment]
Would be cool to simplify the ci pipeline. Looks like code duplication.. but that can happen later on in a separate PR.

**Comment by micbar** [comment]
> Would be cool to simplify the ci pipeline. Looks like code duplication.. but that can happen later on in a separate PR.

Yes, some duplication is happening. But the two contexts are slightly different.

I didn't want to blow up the config. We will add settings UI tests also in a following PR and then can optimize.

**Pull request merged**
