### PR TITLE
Fix env name for root tls cert for sharing service

### PR DESCRIPTION
**Pull request by bennycooly**
## Description

Looks like in https://github.com/owncloud/ocis/commit/d7139d41277094a98110be14ec250ac2bfd1e7b6 the actual deprecation replacement env var was removed instead of the deprecated env var for the root TLS cert for NATS. This fixes the issue by adding ` SHARING_EVENTS_TLS_ROOT_CA_CERTIFICATE` back in the config.

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by rhafer** [comment]
@dragonchaser This looks basically correct to me. Though in order to be able to backport this to 4.0 I guess we should to allow `SHARING_EVENTS_TLS_ROOT_CA_CERTIFICATE` and `SHARING_EVENTS_TLS_ROOT_CA_CERT` again now. And finally  deprecate again `SHARING_EVENTS_TLS_ROOT_CA_CERT` in 5.0.0. Thought?

**Comment by dragonchaser** [comment]
@rhafer yes you are correct, both should be allowed and `SHARING_EVENTS_TLS_ROOT_CA_CERT` should be deprecated by 5.0.0

**Review by dragonchaser — CHANGES_REQUESTED** [review]
Please do not just remove or rename variables please add the fields for: `removalVersion`, `deprecationVersion` and `deprecationReplacement`. see https://owncloud.dev/ocis/development/deprecating-variables/

**Comment by bennycooly** [comment]
> Please do not just remove or rename variables please add the fields for: `removalVersion`, `deprecationVersion` and `deprecationReplacement`. see https://owncloud.dev/ocis/development/deprecating-variables/

Sure, just added the deprecation parameters. I assumed since the original deprecation was incorrectly made we wouldn't need to go through the deprecation process again.

**Review by mmattel — APPROVED** [review]
LGTM from a docs POV 👍

**Comment by dragonchaser** [comment]
@bennycooly unfortunately we have to, otherwise this will result in broken documentation, but otherwise lgtm. Thanks for your contribution.

**Review by dragonchaser — APPROVED** [review]

**Comment by mmattel** [comment]
@dragonchaser do we need to backport this to stable-4.0 ?

**Comment by dragonchaser** [comment]
Branch needs a rebase to master.

**Comment by dragonchaser** [comment]
> @dragonchaser do we need to backport this to stable-4.0 ?

I do not think so, 4.0.3 is part of stable 4.0.x...

**Comment by micbar** [comment]
Thank you for the contribution!

**Pull request merged**
