### PR TITLE
adapt examples to non-root docker image

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
oCIS 1.11 uses a non root image and therefore the entrypoint script cannot write to some locations anymore. This PR ensures that it only writes to writable locations.

## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/2436

## How Has This Been Tested?

- `docker-compose up` locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by pascalwengerter** [comment]
WOPI:
- Getting an initial "bad gateway" when accessing `ocis.owncloud.test` for the first time, works on page reload
- Opening a file with WOPI from the sidebar fails with `opening file with WOPI failed Error: Request failed with status code 400`

HELLO:
- Getting an initial "bad gateway" when accessing `ocis.owncloud.test` for the first time, works on page reload
- Seems to work fine otherwise

**Comment by wkloucek** [comment]
The initial Bad Gateway is expected since Traefik starts up faster than oCIS and also the oCIS proxy is restarted once (leads to longer startup times than when just running oCIS from your normal dev enviroment).

**Comment by pascalwengerter** [comment]
> The initial Bad Gateway is expected since Traefik starts up faster than oCIS and also the oCIS proxy is restarted once (leads to longer startup times than when just running oCIS from your normal dev enviroment).

Thanks for clarification, then feel free to ignore it and/or add a quick note in the dev guide maybe? (Unless it's there already, but it gave both me and Gianmaria from CERN a "wtf" moment)

**Comment by wkloucek** [comment]
@pascalwengerter I digged into the problem that changes made to files are not stored. Turns out that this happens if one uses the CS3org WOPI server older than 7.1.0. Please try again with `CS3ORG_WOPISERVER_DOCKER_TAG=v7.1.0 docker-compose up`

**Review by pascalwengerter — APPROVED** [review]
LGTM, thanks for taking care!

**Pull request merged**
