### PR TITLE
[full-ci] update Reva to latest edge

### PR DESCRIPTION
**Pull request by micbar**
## Description

Update reva to latest edge.

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by butonic — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/15243/41/7
various scenarios that expect "out of quota" 507 status are failing.

**Comment by micbar** [comment]
@butonic @C0rby Seems that we broke some quota handling stuff.

**Comment by micbar** [comment]
@ScharfViktor I changed the space deletion logic in the GraphHelper.

**Comment by micbar** [comment]
Project spaces cannot be deleted atm, needs the next improvement https://github.com/cs3org/reva/pull/3203

**Comment by ScharfViktor** [comment]
Regarding deleting personal space: I will change it-> after each test the admin will delete all created users (personal space is deleted automatically). PR is ready

**Pull request merged**
