### PR TITLE
[full-ci] chore: bump web to v10.1.0

### PR DESCRIPTION
**Pull request by JammingBen**
As per title. See changelog item for changes.

Also enables the app store as default web app in web.

### CODE REVIEW

**Comment by JammingBen** [comment]
@ScharfViktor @SagarGi CI is failing on this one, do you have an idea why? Did some lines of expected failures change?

**Comment by ScharfViktor** [comment]
> @ScharfViktor @SagarGi CI is failing on this one, do you have an idea why? Did some lines of expected failures change?

to fix e2e test tests/e2e/cucumber/features/oidc/refreshToken.feature:8
 we need add extra envs to CI see here: https://github.com/owncloud/web/pull/11296/files#diff-6a968d4b7901c8526c8d9a86d1f434737dbfe2b00da21a7d3041ed4e3d58d62eR116-R128

**Comment by phil-davis** [comment]
Note: https://github.com/owncloud/web/pull/11366 has a small test code change to get it passing with the latest ocis master.
I suspect that that needs to be merged, and the web commit id for tests updated here, to get the web e2e tests to pass.

**Comment by ScharfViktor** [comment]
regarding apiTest: we should change coreApiWebdavOperations/downloadFile.feature:231-261
I can adapt apiTest for new headers and add extra envs to CI to fix e2e test.

I'll do it

**Comment by ScharfViktor** [comment]
> Note: [owncloud/web#11366](https://github.com/owncloud/web/pull/11366) has a small test code change to get it passing with the latest ocis master. I suspect that that needs to be merged, and the web commit id for tests updated here, to get the web e2e tests to pass.

these tests relate to `app-provider` suite which we don't run in ocis CI.

**Review by ScharfViktor — APPROVED** [review]
- CI is happy now
- checked changelog ✅️

**Review by phil-davis — APPROVED** [review]

**Comment by JammingBen** [comment]
Awesome, thanks for making CI green!

**Pull request merged**
