### PR TITLE
docs: use placeholder for next release

### PR DESCRIPTION
**Pull request by micbar**
## Description

Use placeholder for next version in env var descriptions.

refs #9254 

## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/9254

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - avoids the problem of predicting now if the changes will be in release 5.1 or 6.0

**Review by dragonchaser — APPROVED** [review]
Needs follow-up to adapt the tools in `docs/helpers` otherwise `%%NEXT%%` will show up in the docs.

**Comment by mmattel** [comment]
We also need to document this in owncloud.dev, need to look for the right place.

**Comment by mmattel** [comment]
Docs looks good, thanks for adding 👍

**Pull request merged**
