### PR TITLE
make image not using root user

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
The owncloud/ocis docker image now uses a non root user and enables you to set a different user with the docker `--user` parameter. The default user has the UID 1000 is part of a group with the GID 1000.

This is a **breaking change** for existing docker deployments. The permission on the files and folders in persistent volumes need to be changed to the UID and GID used for oCIS (default 1000:1000 if not changed by the user).

## Related Issue

- Needed for #2302 in order to run oCIS as the same UID / GID as oC10

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

### CODE REVIEW

**Comment by wkloucek** [comment]
@xoxys what do you think about that change? It will allow you to change the UID of your user with the docker `--user` run option. But the user needs to care about volume permissions and so on...

The alternative would be some init script which cares about permissions of files and then starts oCIS as a non root user. 
Any opinions?

**Comment by xoxys** [comment]
Yeah, would love to see it running with a non-root user!

1) I would not mess around with chown init foo, the user can handle it and changing the user later again is pretty uncommon
2) There were some issues in the past withing Kubernetes/OpenShift where it was better to use ` USER 700`  instead of the username. Not sure if this is still true and what the exact issue was.

**Comment by wkloucek** [comment]
> 2. There were some issues in the past using Kubernetes/OpenShift where it was required to use ` USER 700`  instead of the username. Not sure if this is still true and what the exact issue was.

This is an easy change. Any opinions on the UID itself? I picked 700 randomly as a default...

**Comment by xoxys** [comment]
The first non-root/non-system UID used by Alpine is `1000`  so I would use a UID >= 1000.

**Review by xoxys — APPROVED** [review]
LGTM

**Review by butonic — APPROVED** [review]

**Pull request merged**
