### PR TITLE
add the REPORT API with the filter-files filter

### PR DESCRIPTION
**Pull request by C0rby**
## Description

Updated reva to pull in the enhanced `REPORT` API. Also updated the `frontend` command to include the new config options for the `favorites manager`.

## Related Issue

- First steps for https://github.com/cs3org/reva/issues/2036 

## Motivation and Context

https://github.com/cs3org/reva/issues/2036

## How Has This Been Tested?

- reva ci

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Review by butonic — APPROVED** [review]

**Comment by C0rby** [comment]
This PR is still in the draft state because the required PR in reva got reverted. Once the new PR https://github.com/cs3org/reva/pull/2086 in reva is merged we can merge this here too.

**Pull request merged**
