### PR TITLE
[full-ci] update reva to 6a346676da20

### PR DESCRIPTION
**Pull request by butonic**
fix slowness introduced by [switching to cs3 shares driver](https://github.com/owncloud/ocis/pull/3697) by bringing in https://github.com/cs3org/reva/pull/2991

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiSpaces-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/12628/38/1) failed. Further test are cancelled...

**Comment by micbar** [comment]
We somehow broke resharing with this update, maybe introduced in https://github.com/cs3org/reva/pull/2991

**Comment by pascalwengerter** [comment]
> We somehow broke resharing with this update, maybe introduced in [cs3org/reva#2991](https://github.com/cs3org/reva/pull/2991)

These are unrelated failures already on master (see nightly and the web bump PR)

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/ocis/pull/4000

**Pull request closed without merging**
