### PR TITLE
[full-ci] Bump web to v5.5.0 final

### PR DESCRIPTION
**Pull request by kulmann**

### CODE REVIEW

**Review by micbar — APPROVED** [review]
LGTM, changelog still TBD

**Comment by saw-jan** [comment]
Local API tests are failing due to: https://github.com/owncloud/ocis/issues/3998#issuecomment-1161442467

**Comment by micbar** [comment]
This PR needs a rebase to get a green CI. The resharing issue has been fixed with #4000

**Comment by pascalwengerter** [comment]
> This PR needs a rebase to get a green CI. The resharing issue has been fixed with #4000

Taking care now

**Comment by pascalwengerter** [comment]
We'll most likely provide a `v5.6.0` later today, that & changelog update will come later separately

**Pull request merged**
