### PR TITLE
[full-ci] Bump web to v5.5.0-rc.2

### PR DESCRIPTION
**Pull request by kulmann**
Usually we only bump to final releases of oC Web. To get in sync for the beta and find out about blockers early, we'll update to a web release candidate for now.

### CODE REVIEW

**Comment by kulmann** [comment]
@pascalwengerter afaik the tests failing in https://drone.owncloud.com/owncloud/ocis/11325/48/9 are all flaky, is that correct?

**Comment by pascalwengerter** [comment]
> @pascalwengerter afaik the tests failing in https://drone.owncloud.com/owncloud/ocis/11325/48/9 are all flaky, is that correct?

The line 56/60 for sure, but given that one fails and one passes unexpectedly hints at a missing update of the expected failures 🤔🥸 line 172 needs investigation, could be it'll be dropped by updating expected failures, could be random or legit otherwise

**Comment by kulmann** [comment]
> > @pascalwengerter afaik the tests failing in https://drone.owncloud.com/owncloud/ocis/11325/48/9 are all flaky, is that correct?
> 
> The line 56/60 for sure, but given that one fails and one passes unexpectedly hints at a missing update of the expected failures 🤔🥸 line 172 needs investigation, could be it'll be dropped by updating expected failures, could be random or legit otherwise

Hm, true 🤔 line 172 has an issue linked that is already closed. Maybe there just was no full ci run in the meantime 🤔 Removed it from expected failures.

**Comment by pascalwengerter** [comment]
> > @pascalwengerter afaik the tests failing in https://drone.owncloud.com/owncloud/ocis/11325/48/9 are all flaky, is that correct?
> 
> The line 56/60 for sure, but given that one fails and one passes unexpectedly hints at a missing update of the expected failures 🤔🥸 line 172 needs investigation, could be it'll be dropped by updating expected failures, could be random or legit otherwise

Pushed a commit that sorted the 56/60 line thing, now let's hope the flakiness isn't too bad

**Review by pascalwengerter — APPROVED** [review]
LGTM, squash-able 🤓

**Pull request merged**
