### PR TITLE
Disable Multiparts uploads

### PR DESCRIPTION
**Pull request by kobergj**
Multipart uploads do cause extreme memory consumption

### CODE REVIEW

**Review by 2403905 — APPROVED** [review]

**Comment by mmattel** [comment]
Is there an envvar behind the change and if yes, should this/the behaviour be mentioned in the docs?

**Comment by kobergj** [comment]
@mmattel We need to find out how to mitigate the issue before we update docs or env descriptions.

**Comment by butonic** [comment]
AFAICT we should disable s3.concurrent_stream_parts not
s3.disable_multipart

**Comment by butonic** [comment]
https://github.com/owncloud/ocis/pull/8666/files#diff-1bcbf5887e19b4fa234e42541fb15612f1391532ddc02348b738b5a6d7b6a51dR116 should be false.

**Pull request merged**
