### PR TITLE
Added the ShareUpdate activity in the space context.

### PR DESCRIPTION
**Pull request by 2403905**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by 2403905** [comment]
@tboerger The few questions about the activity templates
When a user updates the `permission` and `expiration` the ocis emit a single event.
Then the activity uses the template for this event like `MessageShareUpdated    = l10n.Template("{user} updated {field} for the {resource}")`
1. Can we join the fields enum by comma? `permission` and `expiration` => `permission, expiration`
2. We translate the activity message template on the server side. Should we also translate the field data that represents as updated field ( `permission, expiration`) in this case? 

Now: 
| **admin** updated **expiration, permissions** for **the New folder** |
 translated as 
| **admin** оновив **expiration, permissions** для **the New folder** |

Could be:
| **admin** updated **expiration, permissions** for **the New folder** |
 translated as
| **admin** оновив **термін дії, дозволи** для **the New folder** |


Screenshot 2024-09-19 at 09 46 35

**Comment by tbsbdr** [comment]
@2403905 1,2:yes 🙂

**Comment by micbar** [comment]
who mentioned @tboerger here?

**Comment by micbar** [comment]
This needs a rebase to get a green CI, we need #10131

**Review by micbar — APPROVED** [review]

**Pull request merged**
