### PR TITLE
[docs-only] Correct the removal version according semver to 4.0.0

### PR DESCRIPTION
**Pull request by mmattel**
References: #6077 ([docs-only] update the deprecation description (removal version rule))

This corrects the version in the services in _master_.

### CODE REVIEW

**Review by dragonchaser — APPROVED** [review]
lgtm

**Review by kobergj — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-2</strong>](https://drone.owncloud.com/owncloud/ocis/21507/67/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>wopiValidatorTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/21507/47/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-7</strong>](https://drone.owncloud.com/owncloud/ocis/21507/62/1) failed. Further test are cancelled...

**Pull request merged**
