### PR TITLE
[Tests-Only]Add earlyFail

### PR DESCRIPTION
**Pull request by jasson99**
## Description
This PR enables fail-early system for tests running in CI.
When ever a test suite fails, it stops the particular build so that the resources are not wasted.
The drone.star is adjusted such that for the suites where earlyFail feature is set to True, any test failure in that suite stops the build. If we do not want the failing tests in a suite to stop the build, we can adjust `earlyFail: False` for the particular test suite.
Whenever a test suite fails, a github comment is generated which helps us identify which test failure actually stopped the build.

## Related Issue
- https://github.com/owncloud/QA/issues/672

## How Has This Been Tested?
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by micbar** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-owncloud</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-owncloud</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Web-Tests-ocis-ocis-storage-1</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-ocis</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>localApiTests-apiAccountsHashDifficulty-owncloud</strong> failed. The build is cancelled...</summary>

**Review by wkloucek — APPROVED** [review]
LGTM

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>Core-API-Tests-owncloud-storage-9</strong> failed. The build is cancelled...</summary>

**Review by phil-davis — APPROVED** [review]

**Review by dpakach — APPROVED** [review]

**Pull request merged**
