### PR TITLE
Add focus to input elements on login page

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue
- Fixes https://github.com/owncloud/web/issues/4322

## Screenshots (if appropriate):

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by kulmann — CHANGES_REQUESTED** [review]
Please run `make generate` within the `idp` dir once, so that the login page gets compiled into the `embed.go` file of the idp service. That needs to be committed as well.

Other than that: LGTM 👍  Choosing white as focus color makes sense. Color contrast to the background is 16.58:1, which is probably the best we can get 😁

**Review by kulmann — APPROVED** [review]
Awesome 🚀

**Comment by kulmann** [comment]
> > Please run make generate within the idp dir once, so that the login page gets compiled into the embed.go file of the idp service. That needs to be committed as well.
> 
> Alright 👍
> 
> How do you keep it with rebasing in OCIS repos? "Keep it real" or ideally one commit per PR?

Keep all the commits. ;-) Most of us love to have a history and to be able to bisect with useful, small result sets. ;-)

**Comment by JammingBen** [comment]
> Keep all the commits. ;-) Most of us love to have a history and to be able to bisect with useful, small result sets. ;-)

Yeees, nice! :)

**Pull request merged**
