### PR TITLE
add version command and add build information to metrics

### PR DESCRIPTION
**Pull request by C0rby**
The cli version command for the proxy service.

### CODE REVIEW

**Comment by C0rby** [comment]
Argh... for some reason I didn't see the changelog folder in the proxy module.
Should I move it from the root changelog folder or what is the process now? @micbar

**Comment by micbar** [comment]
move it to the extension, yes.

**Review by IljaN — APPROVED** [review]

**Review by refs — COMMENTED** [review]
nice! thanks for porting the changes from `ocis-proxy`

**Comment by jnweiger** [comment]
Leaves me puzzled. How can #310 be solved using this?

**Pull request merged**
