### PR TITLE
Update extensions 2020-05-20

### PR DESCRIPTION
**Pull request by PVince81**
- ocis-graph v0.0.0-20200505154959-2efcd929c1e9
- ocis-migration v0.1.1-0.20200519133726-4c6b7daff23c
- ocis-reva v0.2.2-0.20200519090125-efaa4fa209da
- ocis-thumbnails v0.1.3-0.20200519093216-7867c5389055
- ocis-accounts v0.1.2-0.20200511104221-f537f420c409
- ocis-proxy v0.3.2-0.20200422152849-f2d1c0a1be6b

### CODE REVIEW

**Comment by PVince81** [comment]
seems I picked the old versions for the description... fixing...

**Comment by PVince81** [comment]
hmmm... no idea:
```

build github.com/owncloud/ocis/cmd/ocis: cannot load github.com/micro/go-micro/v2/api/resolver/micro: module github.com/micro/go-micro/v2@latest found (v2.7.0), but does not contain package github.com/micro/go-micro/v2/api/resolver/micro
--


```

**Comment by refs** [comment]
> hmmm... no idea:
> 
> ```
> 
> build github.com/owncloud/ocis/cmd/ocis: cannot load github.com/micro/go-micro/v2/api/resolver/micro: module github.com/micro/go-micro/v2@latest found (v2.7.0), but does not contain package github.com/micro/go-micro/v2/api/resolver/micro
> --
> ```

https://github.com/owncloud/ocis/pull/282/files#diff-37aff102a57d3d7b797f152915a6dc16R16

We cannot upgrade to `go-micro` 2.5 just yet

**Comment by PVince81** [comment]
I didn't ask it to. All I did was run `go get` with the name of the listed extensions + `@master`.

Is one of the extensions triggering the update ?

**Comment by PVince81** [comment]
it seems that ocis-hello is the one triggering the go-micro upgrade, I've excluded it now.

**Comment by PVince81** [comment]
I realize that this update here might be futile as for a true release we'll likely want to rely on actually released versions of extensions. Still, I want to let this through and see CI green.

Then in a next step we could release each of these extensions' commit hashes as we have the confirmation that they work together. (and disregard any new commits on these extensions)

**Comment by PVince81** [comment]
more weirdness in make vet:
```
/srv/app/pkg/mod/github.com/owncloud/ocis-proxy@v0.3.1/pkg/proxy/policy/selector.go:103:46: unknown field 'Key' in struct literal of type "github.com/owncloud/ocis-accounts/pkg/proto/v0".Query
```

this reminded me to also update ocis-accounts, but then it brings in further errors:
```
go vet github.com/owncloud/ocis/cmd/ocis github.com/owncloud/ocis/pkg/command github.com/owncloud/ocis/pkg/config github.com/owncloud/ocis/pkg/flagset github.com/owncloud/ocis/pkg/micro/runtime github.com/owncloud/ocis/pkg/register github.com/owncloud/ocis/pkg/tracing github.com/owncloud/ocis/pkg/version
# github.com/owncloud/ocis-proxy/pkg/proxy/policy
../../../../go/pkg/mod/github.com/owncloud/ocis-proxy@v0.3.1/pkg/proxy/policy/selector.go:66:4: undefined: "github.com/owncloud/ocis-accounts/pkg/proto/v0".NewSettingsService
../../../../go/pkg/mod/github.com/owncloud/ocis-proxy@v0.3.1/pkg/proxy/policy/selector.go:97:65: undefined: "github.com/owncloud/ocis-accounts/pkg/proto/v0".SettingsService
../../../../go/pkg/mod/github.com/owncloud/ocis-proxy@v0.3.1/pkg/proxy/policy/selector.go:103:46: unknown field 'Key' in struct literal of type "github.com/owncloud/ocis-accounts/pkg/proto/v0".Query
# github.com/owncloud/ocis-migration/pkg/command
../../../../go/pkg/mod/github.com/owncloud/ocis-migration@v0.1.0/pkg/command/import.go:128:10: undefined: "github.com/owncloud/ocis-accounts/pkg/proto/v0".NewSettingsService
make: *** [Makefile:75: vet] Error 2
```

not sure what's going on...

if there is no quick solution I'll then reduce the update to only working extensions

**Comment by PVince81** [comment]
ok, I've now also updated ocis-migration

**Comment by PVince81** [comment]
also updated ocis-proxy then

**Comment by PVince81** [comment]
in the meantime I've split ocis-reva and ocis-thumbnails to a separate PR: https://github.com/owncloud/ocis/pull/285

**Comment by PVince81** [comment]
fails here and there is no further updates I can attempt:
/srv/app/pkg/mod/github.com/owncloud/ocis-proxy@v0.3.2-0.20200422152849-f2d1c0a1be6b/pkg/proxy/policy/selector.go:103:46: unknown field 'Key' in struct literal of type "github.com/owncloud/ocis-accounts/pkg/proto/v0".Query

if there is any set of commits across the extensions where it's supposed to work together, let me know. we could then tag those

**Pull request closed without merging**
