### PR TITLE
harden accounts cache security

### PR DESCRIPTION
**Pull request by fschade**

### CODE REVIEW

**Comment by fschade** [comment]
another thing we can do to speed things up for every request is to finetune the mutex... this also brings huge performance impacts if we keep the isPasswordValid as it is.

https://github.com/owncloud/ocis/blob/4fa86f8a44e9be3bf5b63e5657591cebf65f439e/accounts/pkg/service/v0/accounts.go#L136

**Comment by C0rby** [comment]
This looks good. :+1:

**Review by C0rby — APPROVED** [review]

**Comment by phil-davis** [comment]
do we need a changelog for this? or is this a follow-on from yesterday's PR and the changelog of yesterday is enough?

**Comment by fschade** [comment]
> do we need a changelog for this? or is this a follow-on from yesterday's PR and the changelog of yesterday is enough?

the code still does the same, its the underlying implementation that has changed. In my opinion no

**Comment by kulmann** [comment]
> > do we need a changelog for this? or is this a follow-on from yesterday's PR and the changelog of yesterday is enough?
> 
> the code still does the same, its the underlying implementation that has changed. In my opinion no

Sidenote: you can also add more PR urls to an already existing changelog, if it extends it.

**Comment by fschade** [comment]
> > > do we need a changelog for this? or is this a follow-on from yesterday's PR and the changelog of yesterday is enough?
> > 
> > 
> > the code still does the same, its the underlying implementation that has changed. In my opinion no
> 
> Sidenote: you can also add more PR urls to an already existing changelog, if it extends it.

shit my fault, yes this make sense. I do it in the future

**Pull request merged**
