### PR TITLE
[not-for-merge] check core pr 40185

### PR DESCRIPTION
**Pull request by kiranparajuli589**
Related: https://github.com/owncloud/core/pull/40185

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-0</strong>](https://drone.owncloud.com/owncloud/ocis/13217/4/1) failed. Further test are cancelled...

**Comment by kiranparajuli589** [comment]
Found the following issues on the multiple runs (https://drone.owncloud.com/owncloud/ocis/13221/4/7):
- Expected stored etag for user Brian at `/Shares` to be some string but found null! (Exception)
- even after 10 attempts, the etag did not change
    ```console
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ waiting for a second before retrying
    │ 
    WebDavPropertiesContext::theseEtagsShouldHaveChanged
    The etag '"99ffa2cecf21d5fda07e19e667142bdf"' of element '/upload' of user 'Alice' did not change.
    ```

**Comment by kiranparajuli589** [comment]
After using retry for storing etag and increasing retry limit to 20:

- Same errors are found

Summary:
```
294 scenarios (264 passed, 30 failed)
4368 steps (4140 passed, 30 failed, 198 skipped)
22m30.37s (23.53Mb)
```

**Comment by kiranparajuli589** [comment]
Scenarios with error: `Expected stored etag for user Brian at /Shares to be some string but found null! (Exception)` failing locally to.

Not an intermittent but a hard failure.

**Comment by kiranparajuli589** [comment]
While using `spaces` as dav version, I think `Shares` is no longer a folder in the root. It's more a share space.
I'm confused if this `/Shares` contains etag for comparisons.

**Comment by individual-it** [comment]
If that is an issue with spaces and the `Shares` folder then its a problem in the test suite, there should not be any tests that uses spaces and the `Shares` folder. Those tests need to be in ocis and using the shares space

**Comment by kiranparajuli589** [comment]
```
300 scenarios (300 passed)
4200 steps (4200 passed)
```
looks more stable now

**Comment by kiranparajuli589** [comment]
```console
912 scenarios (903 passed, 9 failed)
12864 steps (12846 passed, 9 failed, 9 skipped)
46m12.79s (23.32Mb)
runsh: Total 912 scenarios (903 passed, 9 failed)
runsh: Exit code of main run: 1
```

- All failed on etag comparisions.
- For all failed comparisons full-retry of 20 times has been executed
- In each next try 1 sec delay had been done -> but yet the etag has not match the expected one.
- Not a single test passed with some retry. Every other passing tests has passed without going in the loop of rety

| scenario | dav | times |
| ----- | ----- | --- |
| copying a file inside a publicly shared folder by public changes etag for the sharer | old | 1 |
| copying a file into a subfolder changes the etags of all parents | old|new | (1 + 1 +1) + (1 +1) |
| copying a file inside a publicly shared folder by public changes etag for the sharer | old/new | (1) + (1+1) |

**Comment by kiranparajuli589** [comment]
closing as it's purpose is finished

**Pull request closed without merging**
