### PR TITLE
[full-ci] Bump web to v4.6.0

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
See changelog item

### CODE REVIEW

**Comment by wkloucek** [comment]
@pascalwengerter no '[full-ci]' ? :thinking:

**Comment by pascalwengerter** [comment]
> @pascalwengerter no '[full-ci]' ? thinking

Ouch, good point. I'll "try again" :D

**Comment by phil-davis** [comment]
I raised issue #2847 - it is late here now, @dpakach should be able to sort it out in the morning.

**Comment by dpakach** [comment]
this needs some extra setup for the middleware
Please cherry-pick the commit from https://github.com/owncloud/ocis/pull/2848

**Comment by phil-davis** [comment]
> this needs some extra setup for the middleware Please cherry-pick the commit from #2848

done - CI is running.

**Comment by pascalwengerter** [comment]
Stopping CI since this needs more changes

**Comment by phil-davis** [comment]
> Stopping CI since this needs more changes

@dpakach please look

**Comment by pascalwengerter** [comment]
> > Stopping CI since this needs more changes
> 
> @dpakach please look

I'll push something in a second, too...

**Comment by pascalwengerter** [comment]
I'll take over here, it should be a matter of untangling expected failures until CI gets green. @phil-davis @dpakach thanks for th support

**Review by wkloucek — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
LGTM. drone is currently waiting for docker-arm64 pipeline to start. I guess drone is struggling to find a place to run that right now???

**Comment by pascalwengerter** [comment]
> LGTM. drone is currently waiting for docker-arm64 pipeline to start. I guess drone is struggling to find a place to run that right now???

Cancelled and restarted, the `nightly` was also waiting for ~1h already with multiple pipelines **pending**. I suppose restarting all the hung nightly pipelines at the same time led to resource constraints that blocked stuff so it needs to get stopped and restarted yet again

**Pull request merged**
