### PR TITLE
[full-ci] Bump reva to latest edge

### PR DESCRIPTION
**Pull request by rhafer**
https://github.com/cs3org/reva/pull/3960
https://github.com/cs3org/reva/pull/3959
https://github.com/cs3org/reva/pull/3955

### CODE REVIEW

**Comment by micbar** [comment]
Can you restart with `full-ci`?

**Comment by phil-davis** [comment]
Note: you need to force-push something - if you just restart drone, running on the same commit id, then it does not re-read the updated PR title.

**Comment by rhafer** [comment]
> Note: you need to force-push something - if you just restart drone, running on the same commit id, then it does not re-read the updated PR title.

Done

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiAntivirus-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/23121/57/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Core-API-Tests-ocis-storage-1</strong>](https://drone.owncloud.com/owncloud/ocis/23121/58/1) failed. Further test are cancelled...

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>Web-Tests-ocis-smoke-ocis-storage-1</strong>](https://drone.owncloud.com/owncloud/ocis/23121/68/1) failed. Further test are cancelled...

**Review by micbar — APPROVED** [review]

**Pull request merged**
