### PR TITLE
Tweak go-micro behavior

### PR DESCRIPTION
**Pull request by refs**
There are a few building blocks that we were relying on default behavior, such as `micro.Registry` and the go-micro client. In order for oCIS to work in any environment and not relying in black magic configuration or running daemons we need to be able to:

- Provide with a configurable go-micro registry.
- Use our own go-micro client adjusted to our own needs (i.e: custom timeout, custom dial timeout, custom transport...)

This PR is relying on 2 env variables from Micro: `MICRO_REGISTRY` and `MICRO_REGISTRY_ADDRESS`. The latter does not make sense to provide if the registry is not `etcd`.

The current implementation only accounts for `mdns` and `etcd` registries, defaulting to `mdns` when not explicitly defined to use `etcd`.

The new custom client raises the timeout from 5 to 10 seconds.

## Try It!

1. checkout this branch
2. start etcd
3. run ocis: on owncloud/ocis/ocis -> `> MICRO_REGISTRY=etcd go run cmd/ocis/main.go server`
4. open your browser and do the things you usually do, like login and uploading funny gifs

giphy

TODO:

- get to the bottom of `com.owncloud.api.storage` using mdns

Disclaimer:

When using `etcd` deregistering services might take a while.

### CODE REVIEW

**Review by IljaN — APPROVED** [review]

**Review by kulmann — APPROVED** [review]
🚀

**Comment by phil-davis** [comment]
I am tempted to press merge, but there is no changelog.
Should this have a changelog?

**Comment by refs** [comment]
> I am tempted to press merge, but there is no changelog.
> Should this have a changelog?

yes, please do not merge yet ^^ still got changes.

**Comment by kulmann** [comment]
I dismissed the reviews/approvals since you added commits. Ready for review? :-)

**Comment by refs** [comment]
> I dismissed the reviews/approvals since you added commits. Ready for review? :-)

@kulmann sure!

**Comment by dragotin** [comment]
Works on openSUSE Tumbleweed with etcd started by systemd from the (manually fixed) package.

Seeing this log line in the sys logs tells me that etcd is really used:
```
etcd[13905]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
```
Uploading funny gif works, trying to view it results in an rather unfunny experience ;-)

**Review by IljaN — APPROVED** [review]

**Pull request merged**
